MentorEmbedded/meta-mentor

meta-mel/classes/cml1-config.bbclass
=> cml1-config: fix for separate builddir

meta-mel/conf/local.conf.append.ls1021atwr
JIRA: SB-4626
These fixes are covered in meta-fsl-networking layer. Do not
keep redundant changes.
=> ls1021atwr: delete un-wanted changes from local.conf

meta-mel/recipes-kernel/linux/kernel-host-dev.bb
=> kernel-host-dev: pass required flags to build for t4240rdb-64b

scripts/bb-determine-layers, setup-environment
=> bb-determine-layers: show paths for duplicated layers

scripts/bb-determine-layers
=> bb-determine-layers: fix layer dep recursion handling

pre-setup.ls1021atwr, scripts/setup-mel-builddir
=> Include fsl-networking by default for ls1021atwr

pre-setup.ls1021atwr, scripts/setup-mel-builddir
meta-fsl-networking's setup environment changes for birch release.
=> Birch sb 5077

meta-mentor-staging/fsl-ppc/recipes-devtools/qemu/qemu_fslgit.bbappend
=> qemu_fslgit: fix build breakage due to --disable-opengl

meta-mel/classes/extra_layerinfo.bbclass, meta-mel/classes/isolated-sstate-dir.bbclass, meta-mel/classes/mentor-updates-check.bbclass, meta-mel/classes/restore-dumped-headrevs.bbclass, meta-mel/classes/sstate-mirror-sites.bbclass, meta-mel/classes/user_features.bbclass, meta-mel/conf/distro/include/gdbserver-gplv3.inc, meta-mel/conf/distro/include/kernel-link.inc, meta-mel/conf/distro/include/sourcery-version-check.inc, meta-mel/conf/distro/include/sstate.inc, meta-mentor-staging/fsl-ppc/recipes-devtools/qemu/qemu_fslgit.bbappend
Requires https://github.com/MentorEmbedded/mel-manifest/pull/173.
=> Adjust for upstream layer updates

meta-mel/conf/local.conf.append.ls1021atwr, meta-mel/fsl-arm/recipes-multimedia/alsa/alsa-plugins_1.0.29.bbappend
Pulse audio changes for LayerScape BSP because of which we are seeing a hang in the core-image-sato boot of LS1.
=> Pulse audio changes

meta-mel/recipes-core/packagegroups/packagegroup-base.bbappend
=> packagegroup-base: obey the pulseaudio distro feature

meta-mel/fsl-ppc/recipes-connectivity/connman/connman_%.bbappend
Conditionally add systemd to PACKAGECONFIG as in the original recipe
=> connman: use PACKAGECONFIG to control systemd option

meta-mentor-staging/classes/image_types_wic.bbclass, meta-mentor-staging/recipes-kernel/linux/linux-dtb.inc
=> Wic support fixups / improvements

meta-mel/conf/local.conf.append.mel-dra7xx-evm, meta-mel/recipes-graphics/images/weston-image.bb
=> weston-image: introduce new graphics image recipe

meta-mel/fsl-arm/recipes-kernel/linux/files/ipv6.cfg, meta-mel/fsl-arm/recipes-kernel/linux/linux-ls1_3.12.bbappend
=> linux-ls1: defconfig: enable IPv6 support

meta-mel/conf/distro/include/gdbserver-gplv3.inc, meta-mentor-staging/classes/autotools.bbclass
This fixes it properly, superceding https://github.com/MentorEmbedded/meta-mentor/pull/548.
=> Fix GPLv3 build failures with gettext macros

meta-mel/conf/include/e500v2-wic.inc, meta-mel/conf/local.conf.append.p1020rdb, meta-mel/scripts/lib/wic/canned-wks/p1020rdb-2g.wks, meta-mel/scripts/lib/wic/canned-wks/p1020rdb-4g.wks, meta-mel/scripts/lib/wic/canned-wks/p1020rdb-8g.wks, meta-mel/scripts/lib/wic/canned-wks/p1020rdb.wks
=> p1020rdb: Add WIC support and wks files

meta-mel/conf/local.conf.append.p2020rdb, meta-mel/scripts/lib/wic/canned-wks/p2020rdb-2g.wks, meta-mel/scripts/lib/wic/canned-wks/p2020rdb-4g.wks, meta-mel/scripts/lib/wic/canned-wks/p2020rdb-8g.wks, meta-mel/scripts/lib/wic/canned-wks/p2020rdb.wks
=> p2020rdb: Add WIC support and wks files

meta-mel/conf/local.conf.append.p1010rdb, meta-mel/scripts/lib/wic/canned-wks/p1010rdb-2g.wks, meta-mel/scripts/lib/wic/canned-wks/p1010rdb-4g.wks, meta-mel/scripts/lib/wic/canned-wks/p1010rdb-8g.wks, meta-mel/scripts/lib/wic/canned-wks/p1010rdb.wks
=> p1010rdb: Add WIC support and wks files

meta-mel-support/recipes-core/meta/archive-release.bb
=> archive-release: version sub-layer tarballs

meta-mel/conf/distro/include/mel.conf
This was unintentionally removed by #547.
JIRA: SB-6044
=> mel: resurrect archive-release-downloads

meta-mel/classes/archive-release-downloads.bbclass
=> archive-release-downloads: fix logic for non-mirror-tarballs

meta-mentor-staging/recipes-extended/rrdtool/rrdtool_1.5.4.bb
Add updated recipe from meta-oe as of commit id
ff477aa4e6199b3433ab315a5533ed89f09ad9c9 to fix a number of
QA warnings(file-rdeps, useless-rpaths, installed-vs-shipped).
JIRA: SB-6141
=> rrdtool: add recipe from meta-oe, as of ff477aa

meta-mel/conf/local.conf.append.ls1021atwr
=> local.conf.append.ls1021atwr: Add WKS_FILE examples

meta-mentor-staging/recipes-support/lowpan-tools/lowpan-tools_git.bbappend
=> lowpan-tools: Add missing runtime dependency

meta-mel/conf/local.conf.append.p1010rdb, meta-mel/conf/local.conf.append.p1020rdb, meta-mel/conf/local.conf.append.p2020rdb
Build all supported uboot binaries as CB-5466 has been resolved
JIRA: SB-6190
=> p1010rdb, p1020rdb, p2020rdb: build all supported uboot binaries

meta-mel/conf/distro/include/mel.conf
=> mel: remove sstate from RELEASE_ARTIFACTS

meta-mentor-staging/recipes-connectivity/samba/samba_4.1.12.bbappend
JIRA: http://jira.alm.mentorg.com:8080/browse/SB-6233
=> samba: add dependency on acl

meta-mel-support/recipes-core/meta/archive-release.bb
It turns out the do_build[recrdeptask] was unconditionally sucking in the
do_package_write_* tasks for the image regardless of how the image was pulled
in, whether DEPENDS or explicit 'depends'. Be more explicit in our deps, and
remove the recrdeptask so we can properly archive-release just the downloads
for our qemu builds.
JIRA: SB-6266
=> archive-release: handle RELEASE_ARTIFACTS=downloads

meta-mentor-staging/recipes-devtools/syslinux/syslinux_6.03.bbappend
=> syslinux: obey our binutils vars

meta-mel/conf/distro/include/mel.conf
=> mel: alter DISTRO_VERSION to 2015.12 for the release

meta-mel/conf/distro/include/mel.conf
=> mel: keep ADE_VERSION numeric

meta-mel/conf/distro/include/mel.conf
Signed-off-by: Sean Hudson <sean_hudson@mentor.com>
=> Add Windows ADE class to mel.conf

meta-mentor-staging/recipes-bsp/grub/files/0001-Fix-CVE-2015-8370-Grub2-user-pass-vulnerability.patch, meta-mentor-staging/recipes-bsp/grub/grub-efi_2.00.bbappend, meta-mentor-staging/recipes-bsp/grub/grub_2.00.bbappend
http://git.savannah.gnu.org/cgit/grub.git/commit/?id=451d80e52d851432e109771bb8febafca7a5f1f2
JIRA Ticket: INTAMDDET-1144
=> grub2: Fix CVE-2015-8370

meta-mentor-staging/recipes-kernel/perf/perf.bbappend
=> perf: obey LD

conf/local.conf.sample
Prep for MELMR-179 changes. @cp-mentor , look sane?
=> local.conf.sample: also pull dl & sstate from machine dir

meta-mel/conf/local.conf.append.cyclone5, meta-mel/meta-altera/recipes-bsp/u-boot/u-boot_2016.01.bbappend, meta-mel/scripts/lib/wic/canned-wks/Cyclone-V.wks
This pull request also contains a couple of minor fixes related to u-boot.
=> Wic image support for Cyclone5

meta-mel/conf/local.conf.append.cyclone5, meta-mel/scripts/mk-cyclone5-boot-part.sh
Add script to create boot partition and correct the dtb name used in wic image.
=> Wic cyclone v

meta-mel/meta-altera/recipes-core/psplash/psplash_git.bbappend, meta-mel/meta-altera/recipes-kernel/linux/files/enable-nfs-server.cfg, meta-mel/meta-altera/recipes-kernel/linux/linux-altera_4.1.bbappend
These fixes are from Abdur Rehman.
=> Fix the services failing at bootup on Cyclone-5

meta-mel/meta-altera/recipes-graphics/images/core-image-weston.bbappend, meta-mel/meta-altera/recipes-graphics/wayland/weston_1.8.0.bbappend, meta-mel/meta-altera/recipes-support/freerdp/freerdp.inc, meta-mel/meta-altera/recipes-support/freerdp/freerdp/0001-FindGStreamer_1_0-fix-build-failure-for-new-gstreame.patch, meta-mel/meta-altera/recipes-support/freerdp/freerdp/winpr-makecert-Build-with-install-RPATH.patch, meta-mel/meta-altera/recipes-support/freerdp/freerdp_git.bb
=> sb-6540: weston RDP backend support

meta-mel/classes/libtool-garbage.bbclass, meta-mel/conf/distro/include/mel.conf
We can drop our own bits for this now.
=> Use oe-core's libtool-remove class

meta-mel/classes/image-wic.bbclass, meta-mel/conf/local.conf.append.intel-corei7-64, meta-mel/intel/recipes-core/images/console-image.bbappend, meta-mel/intel/recipes-core/images/core-image-sato.bbappend
@Noor-Ahsan Kindly review and merge.
=> Minnow wic image

meta-mel/conf/local.conf.append.cyclone5
=> local.conf.append.cyclone5: use hard-float

meta-mel/meta-altera/recipes-kernel/linux/files/0001-ARM-8425-1-kgdb-Don-t-try-to-stop-the-machine-when-s.patch, meta-mel/meta-altera/recipes-kernel/linux/linux-altera_4.1.bbappend
Upstream-Status: Ported from v4.1.11
JIRA: SB-6973
=> linux-altera: Fix machine hang during KGDB process

meta-mel/conf/distro/include/mel.conf
=> Mask out a couple recipes to fix parsing issues

meta-mel/meta-altera/recipes-sato/images/core-image-sato.bbappend
We only provide support for webkit framework, any webkit based front end
application will be added by the user.
=> core-image-sato: Remove Ephiphany from image

meta-mel/conf/local.conf.append.cyclone5, meta-mentor-staging/recipes-multimedia/mplayer/mpv_0.15.0.bb
I have addressed a couple of build time warnings in this pull request.
=> Cyclone-5 MPV

meta-mel/lib/recipetool/kernel.py
=> recipetool.kernel: auto include linux-dtb.inc when needed

meta-mentor-staging/meta-java/recipes-core/classpathx/gnumail_1.1.2.bbappend, meta-mentor-staging/meta-java/recipes-core/classpathx/inetlib_1.1.1.bbappend, meta-mentor-staging/meta-java/recipes-core/openjdk/openjdk-7_91b01-2.6.2.bbappend
=> fix warnings seen during jre build

meta-mel/conf/local.conf.append.cyclone5, meta-mel/scripts/lib/wic/canned-wks/Cyclone-V-4g.wks, meta-mel/scripts/lib/wic/canned-wks/Cyclone-V-8g.wks
=> Cyclone-5: Add 4g and 8g versions of .wks files

meta-mel/conf/local.conf.append.cyclone5
=> local.conf.append.cyclone5: prefer 4.1 ltsi kernel

meta-mel/intel/recipes-kernel/linux/linux-yocto_4.1.bbappend
=> Enable KGDB by default for MinnowMAX

meta-mel-support/recipes-core/meta/archive-release.bb
This is needed to prepare for mentor-bsp handling.
=> Archive release fixups

meta-mel/conf/local.conf.append.cyclone5
=> local.conf.append.cyclone5: modify the wording of disclaimer

meta-mentor-staging/multimedia-layer/recipes-multimedia/sox/sox_%.bbappend, meta-mentor-staging/networking-layer/recipes-support/ctdb/ctdb_2.5.1.bbappend, meta-mentor-staging/openembedded-layer/recipes-graphics/fbida/fbida_2.10.bbappend
=> sox,ctdb,fbida: drop bits merged upstream

meta-mel-support/conf/layer.conf, meta-mel/conf/layer.conf, meta-mentor-staging/conf/layer.conf
LAYERDIR_RE, a newly introduced bitbake variable, is a regex-escaped version
of LAYERDIR.
=> Use LAYERDIR_RE

meta-mel/conf/distro/include/mel.conf
=> mel: update supported hosts

meta-mel/recipes-connectivity/openssh/openssh_%.bbappend
Changes in the distro layer need to be conditional upon the distro.
=> openssh: use mel override

meta-mel/conf/distro/include/mel.conf
=> mel: add sourcery tc version to ade env script

meta-mentor-staging/skeleton/recipes-skeleton/service/service_%.bbappend
=> service: drop, this is upstream

meta-mel-support/recipes-extended/chkconfig/chkconfig-alternatives_1.3.59.bb, meta-mentor-staging/recipes-extended/chkconfig/chkconfig-alternatives-native_%.bbappend
=> chkconfig-alternatives*: fix fallout from 'dirs' flag default change

meta-mentor-staging/recipes-support/libsoup/libsoup-2.4_%.bbappend
Remove the libsoup changes as it is available upstream
JIRA: SB-7198
=> libsoup: Remove libsoup changes as it is available upstream

meta-mentor-staging/meta-java/recipes-core/xml-commons/xpp2_%.bbappend, meta-mentor-staging/meta-java/recipes-core/xml-commons/xpp3_%.bbappend
This change can be removed safely, as the
changes are merged upstream:
http://git.yoctoproject.org/cgit/cgit.cgi/meta-java/commit/?id=aa3c79568dfaeb9c8747d49d12ac0396eaf6a4ea
=> xpp[23]: Changes have been merged upstream

meta-mel-support/recipes-core/meta/archive-release.bb
=> archive-release: add PDK_DISTRO_VERSION to local.conf.sample if set

meta-mel-support/recipes-core/meta/archive-release.bb
=> archive-release: add a note to BB_SRCREV_POLICY about its impact

scripts/setup-mel-builddir, scripts/setup-rh, scripts/setup-ubuntu, scripts/toaster_configuration
Depends upon https://github.com/MentorEmbedded/meta-mentor/pull/865, to avoid conflicts between the two pull requests. Only the last 3 commits are unique to this branch.
=> Automate setup of the virtualenv for toaster

scripts/setup-ubuntu
Discovered these issues when testing with a freshly constructed ubuntu chroot. Tested on xenial and trusty.
=> Various fixups for setup-ubuntu

scripts/toaster_configuration
This change will help to customize our image after the build.
=> toaster_configuration: Update script to handle image customization

meta-mel/conf/local.conf.append
Update to align with the changed default in mel.conf.
=> local.conf.append: update the default ADE_IDENTIFIER

meta-mel-support/recipes-core/meta/archive-release.bb
=> Include uninative tarball downloads in our release

meta-mel/conf/distro/include/mel.conf
Signed-off-by: Yasir-Khan <yasir_khan@mentor.com>
=> mel.conf: drop MACHINE_FEATURES for PowerPC targets

meta-mel/classes/sdk_extra_vars.bbclass, meta-mel/conf/distro/include/mel.conf
=> mel: add TOOLCHAIN_VERSION to sdk/ade as base SOURCERY_VERSION

meta-mentor-staging/recipes-connectivity/connman/connman_%.bbappend, meta-mentor-staging/recipes-support/rng-tools/rng-tools/rngd.service, meta-mentor-staging/recipes-support/rng-tools/rng-tools_%.bbappend
patch set to fix: ip assignment delay issue
JIRA-ID: SB-8389,SB-8351
=> fix ip assignment delay issue

meta-mentor-staging/recipes-devtools/dosfstools/dosfstools/dosfstools-disable-iconv-conversion.patch, meta-mentor-staging/recipes-devtools/dosfstools/dosfstools_%.bbappend
Fix the message coming on consoe:
CP437: Invalid argument
JIRA: SB-8456
=> dosfstools: Fix code page 437 message coming on console

meta-mel/conf/distro/include/mel.conf, meta-mentor-staging/recipes-core/meta/buildtools-tarball.bbappend
=> Fix issues with buildtools-tarball

meta-mel/conf/distro/include/mel.conf
=> mel: fix virtual-runtime for nativesdk-opkg-utils

meta-mel/conf/distro/include/mel.conf, meta-mentor-staging/classes/terminal_override.bbclass, meta-mentor-staging/lib/oe/__init__.py, meta-mentor-staging/lib/oe/terminal_override.py
=> Apply oe.terminal.Gnome workaround for Ubuntu 14.04

meta-mentor-staging/recipes-graphics/xorg-lib/libx11/CVE-2016-7942-libx11-oob-read-operations.patch, meta-mentor-staging/recipes-graphics/xorg-lib/libx11/CVE-2016-7943-libx11-out-of-boundary-access.patch, meta-mentor-staging/recipes-graphics/xorg-lib/libx11_1.6.3.bbappend, meta-mentor-staging/recipes-graphics/xorg-lib/libxfixes/CVE-2016-7944-libXfixes.patch, meta-mentor-staging/recipes-graphics/xorg-lib/libxfixes_5.0.2.bbappend, meta-mentor-staging/recipes-graphics/xorg-lib/libxi/CVE-2016-7945-CVE-2016-7946-libxi-OOB-memory-access.patch, meta-mentor-staging/recipes-graphics/xorg-lib/libxi_1.7.6.bbappend, meta-mentor-staging/recipes-graphics/xorg-lib/libxrandr/CVE-2016-7947-CVE-2016-7948-libxrandr.patch, meta-mentor-staging/recipes-graphics/xorg-lib/libxrandr_1.5.0.bbappend, meta-mentor-staging/recipes-graphics/xorg-lib/libxtst/CVE-2016-7951-CVE-2016-7952-libxtst.patch, meta-mentor-staging/recipes-graphics/xorg-lib/libxtst_1.2.2.bbappend
All the CVEs addressed in this pull request have been addressed in the respective upstream projects and the patches are backported for each package.
=> Dogwood CVEs

conf/local.conf.sample
update sourcery source file variable name from CSL_SRC_FILE to
SOURCERY_SRC_FILE.
ref: https://github.com/MentorEmbedded/meta-sourcery/blob/morty/
README.md#optional-functionality
JIRA: SB-8703
=> local.conf.sample: update sourcery source file variable name

meta-mentor-staging/recipes-multimedia/x264/x264/Fix-X32-build-by-disabling-asm.patch
=> x264: fix patch application

meta-mel/conf/distro/include/mel.conf
This fixes the ability to include meta-mel without meta-mentor-staging.
=> mel.conf: make mentor-staging inherits conditional

meta-mel-support/recipes-core/meta/archive-release.bb, meta-mel/conf/distro/include/mel.conf, meta-mel/mel-support/recipes-core/meta/archive-release.bbappend, scripts/release/mel-checkout, scripts/release/setup-environment, scripts/setup-mel-builddir
This should not be merged until #1001 and #1000 are merged, as it depends upon those.
=> Implement git repository delivery for MEL

scripts/setup-ubuntu
It's useful to run this as root rather than as a user in some contexts, i.e. when in a chroot.
=> setup-ubuntu: handle being run as root

meta-mel-support/recipes-extended/chkconfig/chkconfig-alternatives/0001-alternatives.c-obey-sysroot-for-facility-in-removeLi.patch, meta-mel-support/recipes-extended/chkconfig/chkconfig-alternatives_1.3.59.bb, meta-mentor-staging/recipes-extended/chkconfig/chkconfig-alternatives-native/0001-alternatives.c-obey-sysroot-for-facility-in-removeLi.patch, meta-mentor-staging/recipes-extended/chkconfig/chkconfig-alternatives-native_%.bbappend
=> chkconfig-alternatives*: fully obey the sysroot for removeLinks

meta-mentor-staging/recipes-devtools/diffstat/diffstat_%.bbappend, meta-mentor-staging/recipes-devtools/gcc/gcc_%.bbappend
=> gcc, diffstat: fix warnings

scripts/setup-mel-builddir, setup-environment
From https://github.com/MentorEmbedded/adit-custom/pull/580
=> setup-environment: add layer search paths argument

meta-mel/conf/distro/include/mel.conf
Signed-off-by: ijaved <iqra_javed@mentor.com>
=> Changes required to build glibc from sources

scripts/setup-mel-builddir, setup-environment
Various fixes and improvements needed to be able to use the scripts for isar as well as oe. Don't merge yet, as I still need to rename setup-environment.conf.
=> setup-environment: improve flexibility

scripts/setup-mel-builddir, setup-environment
These are general improvements, but which improve functionality in non-MEL/non-OE setups like isar.
=> setup-environment: further improvements

meta-mel-support/recipes-core/meta/archive-release.bb
=> Fix bugs in do_archive_release

conf/conf-notes.txt
=> conf-notes.txt: only list the new supported images

conf/local.conf.sample
=> local.conf.sample: add commented lines to use internal toolchain

meta-mel/conf/distro/include/mel.conf, meta-mel/conf/local.conf.append
=> X11: Remove x11 configuration from MEL distro

meta-mentor-staging/classes/sdk_auto_relocate.bbclass
- disable relocation if no libdir exists. this isn't ideal, as it's
possible to install nativesdk packages that install scripts which should
be relocated, but don't depend on glibc, but this is necessary until
toolchain-shar-relocate.sh is fixed
- rework and simplify sdk_auto_relocate to avoid the find error:
```
find: `$scriptdir/sysroots/x86_64-melsdk-linux/lib': No such file or directory
```
JIRA: SB-8455
=> sdk_auto_relocate.bbclass: fix multiple errors/issues with relocation

meta-mentor-staging/classes/bbpath-intercepts.bbclass
This ensures that adding an intercept to a higher priority layer will change the checksums.
=> postinst-intercepts.bbclass: include search candidates in file checksums

meta-mel/conf/distro/include/mel.conf, meta-mel/conf/local.conf.append
=> mel: fall back from wayland to x11 based on vendor support

conf/local.conf.sample, meta-mel/conf/distro/include/mel.conf
=> meta-mel: added Multimedia as image feature.

meta-mentor-staging/lib/recipetool/edit.py
This edits the recipe and any bbappends for the specified target.
=> recipetool: add 'edit' subcommand

meta-mentor-staging/efibootguard/recipes-bsp/efibootguard/efibootguard.bbappend, meta-mentor-staging/efibootguard/recipes-bsp/efibootguard/efibootguard/0001-ebgpart-fix-conflict-with-__unused-in-system-headers.patch, scripts/setup-ubuntu
=> Host support fixups

meta-mel/recipes-core/images/core-image-minimal-initramfs.bbappend
* Update package_install accordingly to latest available packages
=> initramfs: Update "iperf" to "iperf2"

scripts/toaster_configuration
This fixes toaster based builds with the elm installer structure. For details of the patches submitted upstream additionally for this work please see the JIRA ticket below.
JIRA Ticket: INTAMDDET-2413
=> Elm: initial toaster support

meta-mentor-staging/recipes-core/systemd/systemd_%.bbappend
=> systemd: fix stack-prot build failure with sourcery toolchain

meta-mel/conf/distro/include/mel.conf, meta-mentor-staging/classes/sdk_auto_relocate.bbclass, meta-mentor-staging/classes/toolchain_shar_relocate_bbpath.bbclass, meta-mentor-staging/files/toolchain-shar-relocate.sh
=> toolchain-shar-relocate: fix reloc with an empty nativesdk libdir

conf/local.conf.sample, meta-mel/conf/distro/include/mel.conf
=> mel.conf: Virtualization Imagefeature added.

meta-mel/conf/distro/include/mel.conf
We don't base on poky anymore.
JIRA: SB-11374
=> mel: drop reference to poky baseline

meta-mel/lib/bblayers/dl.py
=> bitbake-layers.dump-downloads: add append and filename args

meta-mel/conf/distro/include/mel.conf
=> QT EGLFS: Add enable EGLFS switch to config qpa

conf/local.conf.sample
=> local.conf.sample: drop now-unsupported sysvinit configuration sample

scripts/release/setup-builddir, scripts/release/setup-mel
=> setup-{mel,builddir}: checkout into workspace, build in workspacedir/build

scripts/release/setup-builddir, setup-environment
=> Remove new workspace/builddir on failure

meta-mentor-staging/security/recipes-security/checksecurity/checksecurity/check-setuid-use-more-portable-find-args.patch, meta-mentor-staging/security/recipes-security/checksecurity/checksecurity_%.bbappend, meta-mentor-staging/security/recipes-security/clamav/clamav/tmpfiles.clamav, meta-mentor-staging/security/recipes-security/clamav/clamav_%.bbappend, meta-mentor-staging/security/recipes-security/scapy/scapy_%.bbappend, meta-mentor-staging/security/recipes-security/suricata/suricata/tmpfiles.suricata, meta-mentor-staging/security/recipes-security/suricata/suricata_%.bbappend
=> Fix a few bugs in meta-security

meta-mel/conf/distro/include/mel.conf
=> mel.conf: Update RELEASE_IMAGE to development-image.

scripts/capdebuginfo
JIRA : SB-10632
Capdebuginfo script is added at meta-mentor/scripts/ The script
collects host and build information and zips into a tar file
which the customer can attach with support ticket for
debugging purpose at our side.
=> capdebuginfo: Added new script

meta-mel/conf/distro/include/mel.conf, meta-mel/mel-support/recipes-core/meta/archive-release.bbappend
=> Restore DISTRO_VERSION change and adjust mel-scripts filename

meta-mel/conf/distro/include/mel.conf
We aren't using update or addon manifests, drop this.
=> mel: drop INDIVIDUAL_MANIFEST_LAYERS

meta-mel/conf/distro/include/mel.conf
=> mel.conf: Added gstreamer-plugins-good to Multimedia feature packagegroup

meta-mel/conf/distro/include/mel.conf
=> mel.conf: added a gst plugin for video sink in multimedia image feature

conf/local.conf.sample, meta-mel/conf/local.conf.append
=> local.conf: move IMAGE_FEATURES_DEVELOPMENT to local.conf.sample

meta-mel-support/recipes-core/meta/archive-release.bb, meta-mel-support/recipes-core/meta/archive-release/runqemu.in
This was broken by the move to qemuboot and recipe-specific-sysroots.
JIRA: SB-12046
=> Fix runqemu with prebuilt binaries

meta-mentor-common/classes/image-root-password.bbclass
JIRA: SB-12130
Don't merge yet, still testing.
=> image-root-password.bbclass: skip the QA check for initramfs images

meta-mel-support/gplv2/recipes-devtools/binutils/binutils_2.17.50.0.12.bb
=> binutils: kill redundant rpath warnings

meta-mel/lib/oeqa/selftest/__init__.py, meta-mel/lib/oeqa/selftest/cases/recipetool_mel.py, meta-mel/lib/recipetool/kernel.py
=> Fix recipetool kernel commands and selftests

meta-mel/conf/local.conf.append, meta-mentor-staging/recipes-connectivity/connman/connman_%.bbappend, meta-mentor-staging/recipes-connectivity/connman/files/fix-resolv-link.patch
=> Kill Volatile Files and Directories Failure status

meta-mel/conf/distro/include/mel.conf
=> mel.conf: Update PDK_LICENSE_VERSION_DATE.

meta-mentor-staging/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
=> qtbase: fix PACKAGECONFIG_OPENSSL typo

meta-mentor-staging/recipes-devtools/valgrind/valgrind/0001-Guard-against-__GLIBC_PREREQ-for-musl-libc.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0001-Make-local-functions-static-to-avoid-assembler-error.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0001-Remove-tests-that-fail-to-build-on-some-PPC32-config.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0001-fix-opcode-not-supported-on-mips32-linux.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0001-makefiles-Drop-setting-mcpu-to-cortex-a8-on-arm-arch.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0001-memcheck-arm64-Define-__THROW-if-not-already-defined.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0001-sigqueue-Rename-_sifields-to-__si_fields-on-musl.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0001-str_tester.c-Limit-rawmemchr-test-to-glibc.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0002-context-APIs-are-not-available-on-musl.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0002-memcheck-x86-Define-__THROW-if-not-defined.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0003-correct-include-directive-path-for-config.h.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0003-tests-seg_override-Replace-__modify_ldt-with-syscall.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0004-Fix-out-of-tree-builds.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0004-pth_atfork1.c-Define-error-API-for-musl.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0005-Modify-vg_test-wrapper-to-support-PTEST-formats.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0005-tc20_verifywrap.c-Fake-__GLIBC_PREREQ-with-musl.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/0006-pth_detached3.c-Dereference-pthread_t-before-adding-.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/Added-support-for-PPC-instructions-mfatbu-mfatbl.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/avoid-neon-for-targets-which-don-t-support-it.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/fixed-perl-path.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/run-ptest, meta-mentor-staging/recipes-devtools/valgrind/valgrind/use-appropriate-march-mcpu-mfpu-for-ARM-test-apps.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind/valgrind-make-ld-XXX.so-strlen-intercept-optional.patch, meta-mentor-staging/recipes-devtools/valgrind/valgrind_3.15.0.bb
add the latest version recipe valgrind_3.15.0 pulled in
from oe-core master branch,
link: https://github.com/openembedded/openembedded-core/tree/
master/meta/recipes-devtools/valgrind
JIRA-ID: SB-12968
=> valgrind_3.15.0: add new recipe

meta-mel-support/README.md, meta-mel/README.md, meta-mel/conf/distro/include/mel.conf, meta-mel/recipes-graphics/images/weston-image.bb, meta-mentor-staging/README.md, scripts/setup-mel-builddir
=> Remove poky instances from mentor layers.

meta-mel/classes/cve-check.bbclass, meta-mel/recipes-core/meta/cve-update-db-native.bb
add new cve-check-analysis class and cve-update-db-native.bb recipe
to get the latest json feeds from NVD for database update
JIRA-ID: SB-13919
=> cve-check: add new class and recipe file

conf/local.conf.sample
=> local.conf.append: enable initramfs as default

meta-mentor-staging/classes/cve-check.bbclass, meta-mentor-staging/recipes-core/meta/cve-update-db-native.bb
add updated cve-check class and cve-update-db-native recipe file
to report Cedar CVEs
Usage - add "INHERIT += "cve-check"" in <path-to-build-dir>/conf/local.conf file
=> cve-check: add cve-check class and cve-update-db-native recipe

meta-mel/conf/distro/include/mel.conf, scripts/release/mel-checkout, scripts/release/setup-workspace
Also add a `-a` argument to show all versions.
JIRA: SB-7235
=> setup-mel: by default only show the latest version for each machine

meta-mentor-staging/classes/features_check.bbclass, meta-mentor-staging/recipes-connectivity/bluez5/bluez5.inc, meta-mentor-staging/recipes-connectivity/bluez5/bluez5/0001-Allow-using-obexd-without-systemd-in-the-user-sessio.patch, meta-mentor-staging/recipes-connectivity/bluez5/bluez5/0001-test-gatt-Fix-hung-issue.patch, meta-mentor-staging/recipes-connectivity/bluez5/bluez5/0001-tests-add-a-target-for-building-tests-without-runnin.patch, meta-mentor-staging/recipes-connectivity/bluez5/bluez5/init, meta-mentor-staging/recipes-connectivity/bluez5/bluez5/run-ptest, meta-mentor-staging/recipes-connectivity/bluez5/bluez5_5.52.bb
=> bluez5_5.52: update from v5.48/5.49 to v5.52

meta-mentor-staging/freescale-layer/recipes-security/optee-imx/optee-os_%.bbappend
=> optee-os: fix build with gcc 10.1

meta-mel/conf/distro/include/mel.conf
mel-swupdate.conf contains configurations for meta-mentor-swupdate layer
=> mel.conf: add mel-swupdate.conf

meta-mentor-staging/freescale-layer/recipes-security/optee-imx/optee-os_%.bbappend
=> Adjust for layer updates

meta-mel/conf/local.conf.append
=> mel: local.conf.append: enable the virtualization feature with the layer

meta-mel-support/recipes-bsp/96boards-tools/96boards-tools_0.12.bb
=> 96boards-tools: bump SRCREV for interactive parted prompt fix

scripts/bb-determine-layers
- bb-determine-layers: handle version-specific LAYERDEPENDS
- bb-determine-layers: include version in Layer objects
=> bb-determine-layers: handle version-specific LAYERDEPENDS

meta-mel/conf/distro/include/mel.conf
=> mel: set general.yocto.sdk.value in the ADE cb-mbs-options

scripts/setup-debian
=> setup-debian: add initial script

conf/local.conf.sample, meta-mel/conf/distro/include/mel.conf, meta-mel/recipes-core/images/mel-initramfs-image.bb
The plan is to implement this through meta-mentor-bsp.
=> drop encrypted-fs feature from the layer

meta-mel/conf/distro/include/mel.conf
=> mel: use contains to reduce vardeps

meta-mentor-staging/meta-python/recipes-devtools/python/python3-pyudev_%.bbappend, meta-mentor-staging/recipes-support/curl/curl_%.bbappend
- curl: add from meta-mentor-swupdate
- python3-pyudev: add from meta-mentor-swupdate
=> curl, python3-pyudev: move fixes from meta-mentor-swupdate

meta-mentor-staging/meta-java/recipes-core/jamvm/jamvm_%.bbappend, meta-mentor-staging/security/recipes-ids/tripwire/tripwire_%.bbappend, meta-mentor-staging/security/recipes-security/nikto/nikto_%.bbappend
- tripwire: avoid nano dependency
- nikto: move rdepends fix from meta-mentor-security
=> Fixes from meta-mentor-{security,iot}

meta-mentor-staging/files/relocate_sdk.sh
=> relocate_sdk.sh: handle additional errors

scripts/setup-rh
This aligns with the current required programs in the dunfell oe-core sanity.bbclass.
JIRA: SB-15260
=> setup-rh: update for rhel8/centos8

conf/local.conf.sample
This reverts commit 0b5fea069828e1249a1e7aad1958571aac1ce808.
=> Revert "local.conf.sample: disable external toolchain until the changes are complete"

meta-mel/lib/recipetool/kernel.py
=> recipetool.kernel: correct copyright range

conf/local.conf.sample
* Remove logic to add virtualization in USER_FEATURES as the logic
has been remove to virtualization layer.
=> local.conf.sample: Remove login to add virtualization in USER_FEATURES.

meta-mel/conf/distro/include/mel.conf
=> mel: inherit archive_ade_downloads from mentor-private

meta-mentor-common/classes/archive-release-downloads.bbclass
=> archive-release-downloads: process git submodules

meta-mentor-staging/openembedded-layer/recipes-extended/collectd/collectd_%.bbappend
Disabling rrdtool in collectd as it is not necessary.
=> collectd: disable rrdtool

meta-mel/lib/bblayers/mel_utils.py
=> bblayers.mel_utils: process git submodules 

scripts/setup-rh
=> setup-rh: remove codeready repo setup

setup-environment
This reverts commit 67c892be88168b0d1e4a64628e7da393c78be001.
JIRA: https://jira.alm.mentorg.com/browse/SB-15959
=> Revert "setup-environment: disable meta-tracing until it's fixed"

meta-mel/recipes-support/db/db_%.bbappend
=> mel: db: use our fork

meta-mentor-common/classes/cml1-config.bbclass
JIRA: SB-15328
Re-opening to apply to master for post-fir.
=> cml1-config.bbclass: operate against unpacked configs

meta-mel/lib/recipetool/kernel.py, scripts/capdebuginfo, scripts/multi-machine, scripts/setup-mel-builddir, scripts/setup-rh, scripts/setup-ubuntu
Signed-off-by: Karim, Hafiz Abdul <HafizAbdul_Karim@mentor.com>
=> Update Mentor Copyright dates

meta-mentor-common/classes/feature_overrides.bbclass
=> feature_overrides.bbclass: add bbclass to mentor-common layer

scripts/setup-ubuntu
This reverts commit 062cb868596d1589c191924d05ea6786f178b63c.
We no longer support toaster.
JIRA: SB-16292
=> Revert "setup-ubuntu: install virtualenv for toaster setup"

scripts/setup-ubuntu
=> setup-ubuntu: fix sudo handling so it's used for locale-gen

meta-mel/recipes-core/kbd/kbd_2.2.0.bbappend
=> kbd: use our fork, add missing bison-native dep

conf/local.conf.sample, meta-mel/conf/distro/include/mel.conf
* adjust IMAGE_FEATURES_DEVELOPMENT per machine features
* set SPLASH using an override
=> Various minor updates to help Yocto BSP build scenarios

meta-mel/conf/distro/include/mel.conf
=> mel: update ADE_PROVIDER for new branding

meta-mel/lib/recipetool/kernel.py, meta-mentor-staging/README.md, scripts/capdebuginfo, scripts/multi-machine, scripts/setup-mel-builddir, scripts/setup-rh, scripts/setup-ubuntu
Signed-off-by: Karim, Hafiz Abdul <HafizAbdul_Karim@mentor.com>
=> update product owner's name to "Siemens Digital Industries Software"

meta-mel/openembedded-layer/recipes-support/lvm2/lvm2/lvm2-mel.service, meta-mel/openembedded-layer/recipes-support/lvm2/lvm2_%.bbappend, meta-mel/recipes-core/initrdscripts/initramfs-framework/lvm, meta-mel/recipes-core/initrdscripts/initramfs-framework_%.bbappend
Ref: https://stash.alm.mentorg.com/projects/MEL/repos/mel-meta-mentor-swupdate/pull-requests/148/commits/5a17affce9b9b04e1437d9facc9f209f720dea48 & https://stash.alm.mentorg.com/projects/MEL/repos/mel-meta-mentor-swupdate/pull-requests/148/commits/05b8fd82d8cb3bf553dd038acee20e4e1f007970
=> [dunfell] Add recipes dropped from meta-mentor-swupdate

meta-mel/lib/recipetool/kernel.py, scripts/capdebuginfo, scripts/multi-machine, scripts/setup-mel-builddir, scripts/setup-rh, scripts/setup-ubuntu
* Update Copyright according to the following
Copyright 2021 Siemens
* SB-16493
=> [dunfell] Update Copyright string according to Siemens requirement.

meta-mel/conf/distro/include/mel.conf
=> mel.conf: set ADE_PROVIDER to DISTRO_NAME

meta-mel-support/conf/layer.conf
=> mel-support: layer.conf: include appends

meta-mel/classes/cve-check.bbclass, meta-mel/lib/oe/cve_check.py, meta-mel/lib/oeqa/selftest/cases/cve_check.py, meta-mel/recipes-core/meta/cve-update-db-native.bb
Backport cve-check and dependent files from oe-core's branch
dunfell - https://github.com/openembedded/openembedded-core/
blob/dunfell/meta/classes/cve-check.bbclass
JIRA-ID: SB-17174
=> cve-check: backport updated cve-check

meta-mel/recipes-core/meta/cve-update-db-native.bb
update cve-update-db to remove progress handler changes in reference
to commit - https://github.com/openembedded/openembedded-core/commit/
694f5107388c5301b82581007ff5fe96dfa8769d#diff-
ee0f9e9fc7ae17a14c3044c4df9d692057662a393b1ea360403e97ab70a74d5b
JIRA-ID: SB-17256
=> cve-update-db: revert progress handler changes

meta-mel/conf/distro/include/mel.conf, scripts/release/mel-checkout, scripts/release/setup-workspace
=> Add and fix `setup-mel -a` for fir/dunfell

meta-mel/openembedded-layer/recipes-connectivity/libwebsockets/libwebsockets_4.2.2.bbappend
=> libwebsockets: 4.2.1 -> 4.2.2

meta-mel-support/recipes-core/meta/archive-release.bb
This drops false initializations of SUBLAYERS_INDIVIDUAL_ONLY variable
JIRA-ID: PSP-12481
Signed-off-by: ansar-rasool <ansar_rasool@mentor.com>
=> [dunfell]: archive-release: drop false initialization of SUBLAYERS_INDIVIDUAL_ONLY variable

scripts/setup-rh, scripts/setup-ubuntu
Bitbake now requires some additional command line compression
tools. See 58f5389e3c6b0e5b29df8850c2056b5fc41b618f in oe-core.
=> scripts:setup-ubuntu/rh: add new host tools
