MentorEmbedded/meta-mentor

- meta-mel/classes/qoriq_build_64bit_kernel.bbclass
- meta-mel/conf/local.conf.append.t4240rdb-64b
- meta-mel/conf/machine/include/e6500-64b.inc
- meta-mel/recipes-support/libunwind/libunwind-1.1/Fix-test-case-link-failure-on-PowerPC-systems-with-Altivec.patch
- meta-mel/recipes-support/libunwind/libunwind_1.1.bbappend
- meta-mentor-staging/conf/layer.conf
- meta-mentor-staging/fsl-ppc/recipes-bsp/u-boot/u-boot-qoriq_2014.01.bb
- meta-mentor-staging/fsl-ppc/recipes-dpaa/usdpaa/files/usdpaa_makefile.patch
- meta-mentor-staging/fsl-ppc/recipes-dpaa/usdpaa/usdpaa_git.bbappend
From 4c62c4a9556f92495d93eddc7641497e1ce1e35c Mon Sep 17 00:00:00 2001
From: Ulrich Weigand <uweigand@de.ibm.com>
Date: Tue, 17 Dec 2013 15:00:54 +0100
Subject: [PATCH] Fix test case link failure on PowerPC systems with Altivec
Upstream-Status:backport
On systems where the system compiler supports Altivec by default,
the libunwind Makefile will attempt to build an extra test case
ppc64-test-altivec.  Unfortunately, the link step will fail since
the Makefile does not actually link against the libunwind library.
Fixed by adding the appropriate LDADD macro.
Signed-off-by: Ulrich Weigand <uweigand@de.ibm.com>
> libunwind: fix linker error by linking against libunwind library

- meta-mel/fsl-ppc/scripts/prepare-boot-media.sh
Made the script independent of machine name, now user would have to specify
the complete image name with path while invoking the script.
> prepare-boot-media.sh: adapt the script for p1020/p2020rdb

- meta-mel/fsl-ppc/recipes-bsp/u-boot/files/p2020rdb-pca-u-boot-nand-fix.patch
- meta-mel/fsl-ppc/recipes-bsp/u-boot/u-boot-qoriq_2014.01.bbappend
Add support for NAND memory with 2KB page size, found on p2020rdb-pca.
This problem is documented as a known issue in Freescals's "P2020RDB-PCA
Quick Start Guide", document number: 928-26831.
Jira: http://jira.alm.mentorg.com:8080/browse/SB-4039
> u-boot-qoriq: fix u-boot nand for p2020rdb-pca

- meta-mel/fsl-arm/recipes-kernel/linux/files/unionfs-2.6_for_3.12.26.patch
- meta-mel/fsl-arm/recipes-kernel/linux/linux-ls1_3.12.bbappend
Union-Fs support for the LS1 has been enabled and verified on
the target.
Also corrected right way of appending the kernel config fragments,
else would result in compilation errors.
JIRA:SB-4334.
> ls1021atwr: Enable unionfs support for the LS1

- meta-mentor-staging/fsl-ppc/recipes-bsp/u-boot/u-boot-qoriq_2014.01.bb
U-boot binary name for nand image on some of the newer targets is
'u-boot-with-spl.bin' however for older configurations it is 'u-boot.bin'.
The u-boot recipe expects 'u-boot-with-spl.bin' for all configurations of
certain boards and fail if we use older variants like P2020RDB and P1020RDB.
This patch only fixes the problem for P2020RDB and P1020RDB, other tarigets
might also require a similar fix.
JIRA: http://jira.alm.mentorg.com:8080/browse/SB-4564
UPSTREAM STATUS: Pending.
> u-boot-qoriq: fix recipe for older u-boot confs

- meta-mel/fsl-arm/recipes-devtools/qemu/qemu-fsl_git.bbappend
The qemu-fsl is intended for use into the target. The native and
nativesdk flavours are not supported and should rely on the OE-Core
provided ones.
This disables the recipe parsing for native and nativesdk build,
fixing the following warning:
,----
| WARNING: Unable to get checksum for qemu-fsl-native SRC_URI entry
|     fix-libcap-header-issue-on-some-distro.patch: file could not
|     be found
`----
Upstream:
http://git.yoctoproject.org/cgit/cgit.cgi/meta-fsl-arm/commit/?h=dizzy&id=9eb08907e291fe049d5d83f76c9e2dd63f4496dc
> qemu-fsl: Disable native and nativesdk builds

- scripts/mksdboot_ls1.sh
mksdboot_ls1 script was copying the rcw_1000.bin from the
SSR_PPN_20 which is generally used for display and lpuart.
While booting from bank0 we need to use rcw from RSR_PPS_70.
RSR_PPS_70 is abbrevation for following:
RSR: eTSEC1:RGMII, eTSEC2:SGMII,eTSEC3:RGMII
PPS: PCIe1@slot:Supported PCIe2@slot:Supported SATA:Supported
70 : SERDES Protocol
JIRA:SB-4731.
> mksdboot_ls1: use correct rcw while booting from bank0

- meta-mel/fsl-ppc/scripts/prepare-boot-media.sh
Do not set a default value for dtb file and sdk directory, we expect the
user to always provide these values via respective command-line arguments
JIRA: http://jira.alm.mentorg.com:8080/browse/SB-4643
> prepare-boot-media.sh: remove default values

- meta-mel/fsl-arm/recipes-bsp/u-boot/u-boot-ls1_2014.01.bb
With u-boot-2014.07, toolchain version GCC-4.9.0 issues have been
encountered in the kernel where recursive rcu stalls are observed.
Several key features, fixes are also missing in the SDK-V1.7 u-boot.
So, switching to a stable u-boot from layersacpe.
JIRA:SB-4638
> ls1021a: Switchback to u-boot-2014.01 for stability

- meta-mel/fsl-ppc/recipes-kernel/skmm-host/skmm-host_git.bbappend
skmm-host has Freescale-EULA license so we can only ship binary
and can't distribute the source code.
> skmm-host: adding recipe to provide binaries only and no source

- meta-mel/fsl-arm/recipes-core/images/console-image.bbappend
Alsa utils which are requied for playback and record is added.
JIRA:SB-4642
> ls1021a: Add alsa utils to the console-image

- meta-mel/conf/local.conf.append.ls1021atwr
- meta-mel/fsl-arm/recipes-core/images/console-image.bbappend
Alsa/Audio packages should not be installed directly, Corrected the
installation of Alsa into image using the machine features.
JIRA:SB-4642
> LS1021A: Install Alsa package through Machine features

- conf/local.conf.sample
- meta-mel/conf/include/drop-toolchain-from-sdk.inc
As we're using an external toolchain, we don't want to ship a newly built
toolchain inside a Yocto SDK.
This is an _remove, becuase I didn't want to hardcode the full package list
for TOOLCHAIN_HOST_TASK. The problem with this is, once an _remove is defined,
there's no way to undo it, so a user wouldn't be able to undo this. It's
placed in a local.conf.append to ensure it's user visible, letting them
comment it out or delete the line to undo it if they choose to.
> mel: remove toolchain from Yocto SDK for external

- meta-mentor-staging/recipes-core/udev/udev-extraconf/mount_modified.sh
- meta-mentor-staging/recipes-core/udev/udev-extraconf_%.bb
Adding modified version of mount.sh to handle devices
without label. Its taken care with the help of UUID,
using blkid command.
JIRA: SB-4637
Signed-off-by: Sujith H <Sujith_Haridasan@mentor.com>
> udev-extraconf: Adding modified version of mount.sh

- meta-mel/conf/local.conf.append.ls1021atwr
Add 'vfat' to MACHINE_FEATURES which in turn includes
dosfstools via packagegroup-base
JIRA: SB-4678
> mel.conf: Enable vfat support for ARM targets

- meta-mel/conf/distro/mel-lite.conf
Validated host for mel-lite 2014.12 is only Ubuntu 14.04
so we make the adjustment accordingly.
> mel-lite.conf: fix validated host distro

- meta-mentor-staging/recipes-extended/xen/xen_4.5.0.bb
The upstream recipe does a local require of xen.inc, so it cannot cross
layer-boundaries the way we could if it was including
recipes-extended/xen/xen.inc
> xen: temporarily override recipe until upstream fix goes in

- meta-mel-support/recipes-core/meta/archive-release.bb
- meta-mel/conf/local.conf.append.ls1021atwr
For layerscape bsp rcw should also be flashed along with
rcw for board to boot.
RCW was missing from pre-built binaries, so added RCW through
EXTRA_IMAGES.
JIRA: SB-4773
> archive-release: Install rcw into pre-built binaries

- meta-mel-support/recipes-connectivity/connman/connman_1.28.bb
- meta-mel-support/recipes-connectivity/connman/files/0001-Revert-dhcp-Keep-the-retry-timeout-nor-the-ipv4ll-ta.patch
- meta-mel-support/recipes-connectivity/connman/files/0001-plugin.h-Change-visibility-to-default-for-debug-symb.patch
- meta-mel-support/recipes-connectivity/connman/files/0011-service-Connect-ethernet-networks-when-created.patch
- meta-mel-support/recipes-connectivity/connman/files/add_xuser_dbus_permission.patch
- meta-mel/conf/distro/include/mel-versions.conf
- meta-mentor-staging/recipes-connectivity/connman/connman_%.bbappend
- meta-mentor-staging/recipes-connectivity/connman/connman_1.25.bbappend
Move to connman 1.28 plus a couple of extra patches to address the network issues reported in SB-4740.
> connman 1.25 -> connman 1.28 (v2)

- meta-mel/recipes-connectivity/connman/connman_%.bbappend
Use PACKAGECONFIGs to handle runtime dependencies. This was dropped
earlier in favor of RDEPENDS handling in connman.inc from poky but we still
need this for our building-block implementation.
> connman: Use PACKAGECONFIGs to handle dependencies

- meta-mentor-staging/conf/layer.conf
We don't want systemd and everything that depends on it rebuilding whenever
DISTRO_VERSION changes.
> os-release: add to SIGGEN_EXCLUDERECIPES_ABISAFE

- meta-mentor-staging/recipes-extended/watchdog/watchdog_5.14.bbappend
Fixes a dependency on a nonexistent initscripts-functions package.
> watchdog: kill update-rc.d when not using sysvinit

- meta-mel/fsl-arm/recipes-devtools/tcf-agent/files/0001-tcf-client-Add-LDFLAGS-to-fix-QA-Warning.patch
- meta-mel/fsl-arm/recipes-devtools/tcf-agent/tcf-agent_git.bbappend
tcf-agent obey LDFLAGS needed to quiet 'No GNU_HASH in the elf binary'
warnings.
JIRA: SB-4884.
> tcf-agent: Fix LDFLAGS warning during QA_PACKAGE stage

- meta-mel/conf/distro/include/mel.conf
Some machines use +=, and due to parse order, this will cause our classes to
no longer be inherited. We always want our image classes inherited, so use +=
here instead.
> mel: use += for IMAGE_CLASSES, not ?=

- meta-mel/conf/distro/include/mel.conf
Now that poky no longer hardcodes the list, we no longer need to hardcode the
list, but can instead use the `WARN_TO_ERROR_QA` variable they added.
This commit ends up enabling other QA checks which we inadvertently missed by
overriding the variables.
> mel: don't hardcode *_QA

- meta-mel/conf/distro/include/mel.conf
The main test coming from there at the moment is a check for host user
ownership contamination.
JIRA: SB-4185
> mel: enable meta-sourcery's QA test(s)

- meta-mentor-staging/recipes-core/systemd/systemd/add-argument-for-valgrind.patch
- meta-mentor-staging/recipes-core/systemd/systemd_%.bbappend
Add an argument to avoid the autodetected dependency on valgrind headers, to
avoid a race encountered in our builds, and add an associated PACKAGECONFIG.
> systemd: fix valgrind build race

- meta-mentor-staging/recipes-graphics/xorg-xserver/files/0001-Fix-subwindow-in-Xi-emulated-events.patch
- meta-mentor-staging/recipes-graphics/xorg-xserver/xserver-xorg_1.15.1.bbappend
Matchbox window manager did not recognize attempts to close an open window
using the X button at the top-right of the application. This patch addresses
this problem.
JIRA: http://jira.alm.mentorg.com:8080/browse/SB-4571
Community Bugzilla link: https://bugs.freedesktop.org/show_bug.cgi?id=70790
> xserver-xorg: fix close-window problem with X

- meta-mel/conf/distro/include/ade-version.inc
- meta-mel/conf/distro/include/mel.conf
The unnecessary immediate expansion of DATETIME_SECS was causing the timestamp
in seconds to end up in the configuration metadata checksum. While we can add
it to BB_HASHCONFIG_WHITELIST, we can just skip the immediate expansion
instead, as the time savings should be miniscule.
> mel: fix parse cache problem

- meta-mentor-staging/recipes-devtools/openjade/openjade-native_%.bbappend
Openjade has an issue being built on x86_64 host
due to a shared lib linking issue (libogrove.so),
which fixed by using static linking.
reference:
https://bugzilla.yoctoproject.org/show_bug.cgi?id=2972#c0
http://pastebin.com/cUb1x2Qj
JIRA: SB-5027
Signed-off-by: Neeraj Sharma <neeraj.sharma@alumni.iitg.ernet.in>
Signed-off-by: Shrikant Bobade <Shrikant_Bobade@mentor.com>
> docbook-utils-native: build fix by static linking openjade

- meta-mel/conf/distro/include/mel.conf
This works around the sstate_stage_all->sstate_stage_dirs case.
> mel: work around bitbake missing vardep bug

- meta-mentor-staging/recipes-devtools/openjade/openjade-native_%.bbappend
This patch provide static link of openjade with its local libs,
it is required to fix the link issue specific with gold linker.
In case of gold linker we unable to get dynamic link with local lib:
libogrove.so, which results in build break of its consumers.
Overriding do_install to handle the disable shared libs.
reference:
https://bugzilla.yoctoproject.org/show_bug.cgi?id=2972#c0
http://pastebin.com/cUb1x2Qj
JIRA: SB-5027
Signed-off-by: Neeraj Sharma <neeraj.sharma@alumni.iitg.ernet.in>
Signed-off-by: Shrikant Bobade <Shrikant_Bobade@mentor.com>
> openjade-native: fix link issue with ld.gold by static link

- meta-mel/recipes-multimedia/pulseaudio/pulseaudio/disable_autospawn_by_default.patch
- meta-mel/recipes-multimedia/pulseaudio/pulseaudio_5.0.bbappend
- meta-mentor-staging/recipes-multimedia/pulseaudio/pulseaudio/avoid-specifically-starting-PA-rely-on-autospawn.patch
- meta-mentor-staging/recipes-multimedia/pulseaudio/pulseaudio/consolidate-startup-scripts.patch
- meta-mentor-staging/recipes-multimedia/pulseaudio/pulseaudio/remove-kde-references.patch
- meta-mentor-staging/recipes-multimedia/pulseaudio/pulseaudio_5.0.bbappend
The autostart behavior for PA is fixed with the help of some patches from upstream. One additional patch that strictly targets MEL is to disable the auto-spawning feature of PA so it is completely controllable through systemd.
> pulseaudio: make starting up PA deterministic

- meta-mel/recipes-core/systemd/systemd_%.bbappend
Add udev-extraconf package which provides rules and scripts to mount storage
devices as they are connected.
JIRA: http://jira.alm.mentorg.com:8080/browse/SB-5114
> systemd: Add udev-extraconf to RDEPENDS

- meta-mel/conf/distro/include/mel.conf
One can't use a variable expansion inside inline python with an undefined
variable, or we get parse failures. Either I could have changed it to use
d.getVar(), or ensure the variable always have a value, which is what this
does.
> mel: fix builds without meta-sourcery

- meta-mel/conf/distro/include/mel-versions.conf
The AMD platforms utilize connman 1.28 when built on
mel or mel-lite so we set the version generically rather
than from each BSP layer.
> mel-versions.conf: use connman 1.28 for AMD platforms

- meta-mel/conf/distro/include/mel-versions.conf
* connman 1.25 is unable to assign IP automatically at
boot and needs to be restarted manually
> mel-versions.conf: use connman v1.28 for T4240RDB

- meta-mel/classes/extra_layerinfo.bbclass
- meta-mel/classes/restore-dumped-headrevs.bbclass
- meta-mel/conf/distro/include/gdbserver-gplv3.inc
- meta-mel/conf/distro/include/kernel-link.inc
This fixed builds with current layers, though upstream has since fixed the
code to be more tolerant. Even so, event handlers should all be using
eventmask anyway to avoid their running for events they don't care about.
> Add eventmask to some event handlers

- meta-mentor-staging/openembedded-layer/recipes-navigation/gpsd/gpsd_3.14.bbappend
gpsd uses libbluetooth, which is compatible between bluez4 & bluez5.
> gpsd: dep on bluez5

- meta-mel/lib/recipetool/kernel.py
All these commands rely on the appendsrc recipetool plugin to do the real work
of adding sources to the kernel in the appropriate place, and all will operate
against the current preferred provider of virtual/kernel. They expect, as the
first argument, the path to a layer where these changes will be placed.
- kernel_set_defconfig: Override the kernel's defconfig. Does not yet function
for linux-yocto kernels. This command copies the supplied defconfig into the
layer, adds it to SRC_URI if not already there, and if the kernel recipe
defines `DEFCONFIG` or `KERNEL_DEFCONFIG`, will set those to the full
absolute path to the unpacked file. Ex.:
$ recipetool kernel_set_defconfig meta-mylayer /path/to/defconfig
- kernel_add_fragments: Add supplied kernel configuration fragments (.cfg
files) to …
> recipetool.kernel: add kernel convenience sub-commands

- meta-mel/classes/sstate-mirror-sites.bbclass
If SSTATE_MIRROR_DISTROS or SSTATE_MIRROR_SITES used inline python, the
generated SSTATE_MIRRORS could have invalid syntax. Fix by using expanded
versions of those variables. Also add a check to skip empty sites.
> sstate-mirror-sites: fix lack of needed expansions

- meta-mentor-staging/fsl-arm/recipes-graphics/imx-gpu-viv/imx-gpu-viv_%.bbappend
This recipe copies binary files with `cp`, including `cp -a`, so the file
ownership can end up being the same as the build user. Work around this by
chown'ing everything to root:root.
This avoids a package_qa failure.
JIRA: SB-5184
> imx-gpu-viv: correct file ownership

- setup-environment
Each layer may contain a post-setup-environment script that can modify,
among other things, the build directory's setup-environment script.  The
script is sourced after being generated, but isn't sourced again following
the processing of post-setup-environment.  Adding in a second source (and
dumping the initial one to /dev/null so the same message doesn't appear
twice, adds minimal overhead and allows post-setup-environment scripts an
opportunity to make changes to setup-environment (eg. to append to
environment variables such as MANPATH).
Signed-off-by: Joe MacDonald <joe_macdonald@mentor.com>
> setup-environment: process updates from post scripts

- meta-mel/classes/user_features.bbclass
When finalization was removed, I missed a reference to the old copy of d: l.
Fixes #497
> user_features: fix NameError

- meta-mel/fsl-arm/recipes-bsp/u-boot/u-boot-ls1_2014.01.bb
For cedar release u-boot 2014.01 version shall be used because
with the latest release u-boot and gcc-4.9 rcu stall crash is still
observed, also updated the license infomation with the latest
sdk-v1.8
Jira: SB-5436
> u-boot-ls1: update the licence and md5 info for u-boot ls1

- meta-mentor-staging/recipes-extended/sed/sed_4.2.2.bbappend
Remove sed_4.2.2.bbappend as fixes in this file have been merged
in upstream.
> sed: remove sed_4.2.2.bbappend

- meta-mel/fsl-arm/recipes-bsp/u-boot/u-boot-ls1_2014.01.bb
lpuart u-boot is required for the the DCU/HDMI  support in the
layerscape scenario, if we want to use hdmi we need to boot
from LP uart rather than normal uart then we can have console-images +hdmi.
We need to pass console as console=ttyLP0,115200 hdmi as parameter for hdmi
support
Jira:SB-5450
> u-boot-ls1: Add support for lpuart u-boot

- meta-mentor-staging/recipes-support/gnutls/gnutls_%.bbappend
* We were adding a new package gnutls-xssl for libgnutls-xssl.so library.
That library has been removed since version 3.3.0. Poky now has 3.3.14.
> gnutls: Remove bbappend

- meta-mentor-staging/recipes-extended/xinetd/xinetd_2.3.15.bbappend
* Upstream recipe now inherit systemd.bbclas so now we don't need
our local fix.
Signe-off-by: Noor Ahsan <noor_ahsan@mentor.com>
> xinetd: Remove local fix of setting INHIBIT_UPDATERCD_BBCLASS

- meta-mel-support/recipes-core/meta/archive-release.bb
The dash shell does not support usage of '==' for
string comparisons, doing so results in erronous
outcomes.
We now fix this by using a single '=' which is
supported across different shells.
> archive-release: fix few bashism issues

- scripts/setup-mel-builddir
The local.conf.sample file no longer explicitly includes
oprofile.  We don't need to filter it out for MEL Lite.
Signed-off-by: Drew Moseley <drew_moseley@mentor.com>
> setup-mel-builddir: Drop removal of oprofile

- meta-mel/conf/local.conf.append.ls1021atwr
Wic tool reads IMAGE_BOOT_FILES which wll make up the boot-partition
of the sd-card. In the layerscape case it contains kernel image
dtb, uboot & rcw for both lpuart and general configuration.
Jira: SB-5407
> ls1021atwr: Add IMAGE_BOOT_FILES which will be used by wic tool

- meta-mel/fsl-arm/recipes-bsp/u-boot/u-boot-ls1_2015.01.bbappend
Install u-boot images for lpuart and nor images which shall
and also remove support for sd-card, since in latest u-boot
we can write directly to Nor from nor u-boot
Jira:SB-5407
> u-boot-ls1: Deploy u-boot for lpuart and nor images

- meta-mel/conf/local.conf.append.ls1021atwr
This has been fixed in meta-mentor commit:
Commit ID: 7e80f58cc56498485b8ed37a55871fd66292a71f
> 1021atwr: remove redundant change of PA exclusion

- meta-mel/conf/local.conf.append.ls1021atwr
- meta-mel/fsl-arm/recipes-bsp/u-boot/u-boot-ls1_2015.01.bbappend
To UBOOT_CONFIG_append for adding lpuart space was missing
and it will throw the compliation error, also made change
to pick freescale suggested rcw for nor booting.
> u-boot-ls1: Fix compilation issue and pick correct rcw

- meta-mentor-staging/recipes-devtools/tcf-agent/files/0001-tcf-agent-obey-LDFLAGS.patch
- meta-mentor-staging/recipes-devtools/tcf-agent/tcf-agent_git.bbappend
Makefile for the package was changed so that the previous
patch was no longer applicable. That patch has been removed
in a previous commit
* Add new patch according to the updated source
* JIRA: SB-5561
> tcf-agent: obey LDFLAGS

- meta-mentor-staging/fsl-ppc/recipes-connectivity/ipsec-demo/ipsec-demo_0.1.bbappend
All files in the test_setkey directory are being copied with
ownership preserved (cp -a).
* Change ownership of all files in test_setkey directory to
root:root
* JIRA: SB-5562
> ipsec-demo: fix host contamination

- meta-mel/fsl-arm/recipes-bsp/alsa-state/alsa-state.bbappend
- meta-mel/fsl-arm/recipes-bsp/alsa-state/alsa-state/ls1021atwr/asound.conf
This will avoid card selection via alsa-mixer before playing
audio.
> ls1021: Add simple asound.conf to select default sound card

- meta-mentor-staging/recipes-kernel/blktrace/blktrace/0001-blktrace-obey-LDFLAGS.patch
- meta-mentor-staging/recipes-kernel/blktrace/blktrace_git.bbappend
Add back the portion of previous ldflags.patch that fixes
the GNU_HASH warning on iowatcher binary
JIRA: SB-5688
> blktrace: fix GNU_HASH warning on iowatcher

- meta-mentor-staging/fsl-ppc/recipes-core/udev/udev-rules-qoriq.bbappend
udev-extraconf installs file mount.blacklist too.
commit id 874231a5063b1888cd25e5bb27da55b440bb4bb8 in upstream
meta-fsl-ppc layer fixes this file conflict. Once MEL has been
updated to that commit, this bbappend should be removed.
JIRA: SB-5483
> udev-rules-qoriq: avoid conflict with udev-extraconf

- meta-mentor-staging/meta-python/recipes-devtools/python/python-lxml_%.bbappend
The setupinfo.py code was written for xml-config/xslt-config, but we're
passing in pkg-config. To get the version of the package, the former want
--version, but the latter needs --modversion. Fix this in setupinfo.py.
This fixes a build failure encountered while building the ADE.
> python-lxml: fix version check for xml/xslt

- meta-mel/conf/distro/include/mel.conf
- meta-mentor-staging/classes/image_types_wic.bbclass
The upstream function hardcodes the wks path, making foolish assumptions and
really not aligning with how things are done in the layering scheme. This
alters it, as a start, to use a variable for the path. I have a local
prototype of a version that leverages a file:// wks URI to find it in the
FILESPATH rather than hardcoding a full path, as well, but am working out some
kinks in that method before merging it. This will work in the meantime, as one
can use inline python to get the wks path by searching BBLAYERS.
> image_types_wic: add class to fix IMAGE_CMD_wic

- meta-mel-support/recipes-kernel/firmware-wireless/firmware-wireless_git.bb
Firmware binaries are not architecture specific and
we inherit allarch for the same reason. In this case
we cannot use architecture specific paths such as
base_libdir which makes the firmware search fail
when it is required. To be clear the current approach
would be incorrect on 64bit systems.
We now use a non architecture specific path to fix
this issue.
> firmware-wireless: fix firmware installation path

- meta-mel/classes/archive-release-downloads.bbclass
This prepares archive-release bits to handle it, and is harmless in the case
where the shallow git support isn't available, or isn't used.
> Adjust for the shallow git mirror tarball support

- meta-mel/conf/distro/mel-tiny.conf
This also changes the include order to ensure that mel.conf isn't undoing any
of the things mel-tiny is doing.
> mel-tiny: update to current poky-tiny

- meta-mentor-staging/meta-python/recipes-devtools/python/python-lxml_%.bbappend
Apparently the fix is on master-next, not master, at the moment.
> python-lxml: bring back the fix for now

- meta-mel/recipes-core/systemd/systemd_225.bbappend
There are systemd unit failures observed on multiple platforms
when built with GCC-5.x toolchain, bug reported in yocto:
https://bugzilla.yoctoproject.org/show_bug.cgi?id=8291
Workaround Will remain here until we get fix for #8291 bug.
> systemd: arm: disable -O2 optimization when built with GCC-5.x

- meta-mentor-staging/fsl-ppc/recipes-core/udev/udev-rules-qoriq.bbappend
Remove udev-rules-qoriq.bbappend as fixes in this file
have been merged in upstream meta-fsl-ppc as of 874231a
> udev-rules-qoriq: remove bbappend

- meta-mel/recipes-kernel/kmod/kmod/fix_return_code_in_error_path.patch
- meta-mel/recipes-kernel/kmod/kmod_git.bbappend
Fix the following error seen during boot:
"Failed to insert module 'kdbus': Function not implemented"
See https://github.com/systemd/systemd/issues/203 for details
JIRA: SB-5927
> kmod: fix return code

- meta-mel/conf/local.conf.append.ls1021atwr
The resulting value of IMAGE_BOOT_FILES variable was being computed without
spaces between each of the file names, so add an extra space at the end of
each file-name.
> ls1021atwr: add spaces between file-names in IMAGE_BOOT_FILES

- meta-mentor-staging/classes/image_types_wic.bbclass
Now upstream uses scripts/lib/wic/canned-wks instead of
scripts/lib/image/canned-wks as a standard path for keeping
wks files.
Signed-off-by: Yasir-Khan <yasir_khan@mentor.com>
> image_types_wic.bbclass: update the WKS_SEARCH_PATH

- meta-mel/recipes-core/systemd/systemd_225.bbappend
oe-core has this worked around with more specific arguments.
> systemd: drop optimization workaround

- meta-mentor-staging/classes/image_types_wic.bbclass
We override its method, so the parse order is important. Without this, our
IMAGE_CMD_wic wasn't being used.
> image_types_wic: inherit image_types

- meta-mentor-staging/recipes-graphics/mesa/mesa-demos/0010-sharedtex_mt-fix-rendering-thread-hang.patch
- meta-mentor-staging/recipes-graphics/mesa/mesa-demos_8.2.0.bbappend
This patch fixes a deadlock that occurs between the main
thread and rendering threads of the sharedtex_mt demo.
This patch has been submitted upstream to mesa-demos
and will probably appear in >8.2.0. A submission has
been made to the poky as well.
http://patchwork.openembedded.org/patch/105011/
JIRA Ticket: INTAMDDET-957
> mesa-demos: fix deadlock in sharedtex_mt

- pre-setup.p1010rdb
- pre-setup.p1020rdb
- pre-setup.p2020rdb
- pre-setup.t4240rdb-64b
Pull in meta-fsl-networking for all four PPC BSPs currently
supported by MEL i.e p1010rdb, p1020rdb, p2020rdb and t4240rdb-64b
> pull in fsl-networking by default for mel ppc bsps

- meta-mel/conf/distro/include/mel.conf
We had logic to avoid prepending when RECIPE_LAYERDIR wasn't valid, but our
logic for creating RECIPE_LAYERDIR has changed, so that logic no longer
worked. Update it to work again.
> mel: don't prepend UNKNOWN/downloads to PREMIRRORS

- meta-mel/scripts/lib/wic/canned-wks/sdimage-bootpart-2g.wks
- meta-mel/scripts/lib/wic/canned-wks/sdimage-bootpart-4g.wks
- meta-mel/scripts/lib/wic/canned-wks/sdimage-bootpart-8g.wks
Certain SD-Cards have less actual capacity than what they claim, so reduce
the size of rootfs partition so that we may not run out of space.
> canned-wks: reduce the size of rootfs partition

- meta-mentor-staging/recipes-kernel/linux/files/powerpc_align_TOC_to_256_bytes.patch
- meta-mentor-staging/recipes-kernel/linux/linux-qoriq_3.12.bbappend
Backport commit id 5e95235 from mainline kernel to fix hang
caused by TOC misalignment.
Recent toolchains force the TOC to be 256 byte aligned. We need
to enforce this alignment in our linker script, otherwise pointers
to our TOC variables (__toc_start, __prom_init_toc_start) could
be incorrect
JIRA: SB-6017
> linux-qoriq: backport patch to fix toc alignment

- scripts/setup-mel-builddir
- scripts/toaster_configuration
This patch creates a work around to run toaster.
The toaster_configuration patch creates temporary git
repos for the layers used by the user in bblayers.conf.
It never forces user to use toaster and it also doesn't
erases the git history for the development environment.
> setup-environment: Adding toaster work around fix

- meta-mentor-staging/fsl-ppc/recipes-bsp/u-boot/u-boot-qoriq_2015.01.bb
Make u-boot-qoriq dependent upon virtual/${TARGET_PREFIX}gcc
unconditionally as it is required for all ppc targets irrespective
of the contents of ${TOOLCHAIN}.
> u-boot-qoriq: add dependency virtual/${TARGET_PREFIX}gcc

- meta-mel/recipes-connectivity/openssh/openssh/sshd_config
- meta-mel/recipes-connectivity/openssh/openssh_%.bbappend
Enable following KexAlgorithms in sshd_config for a successful
ssh connection with eclipse RSE:
a) diffie-hellman-group-exchange-sha1
b) diffie-hellman-group1-sha1
do_configure_prepend in openssh recipe copies sshd_config
from ${WORKDIR} to ${B}. This overrides any patch that is
applied to sshd_config during do_patch. As a workaround we
override the original source file with the modified one in
our bbappend.
JIRA: SB-6146
> openssh: enable KexAlgorithms

- meta-mentor-staging/recipes-support/libtdb/libtdb_1.3.0.bbappend
- meta-mentor-staging/recipes-support/libtevent/libtevent_0.9.21.bbappend
- meta-mentor-staging/recipes-support/talloc/talloc_2.1.1.bbappend
Fix following warnings:
WARNING: QA Issue: libtevent rdepends on libattr, but it isn't a build dependency? [build-deps]
WARNING: QA Issue: python-tevent rdepends on libattr, but it isn't a build dependency? [build-deps]
WARNING: QA Issue: tdb-tools rdepends on libattr, but it isn't a build dependency? [build-deps]
WARNING: QA Issue: libtdb rdepends on libattr, but it isn't a build dependency? [build-deps]
WARNING: QA Issue: python-tdb rdepends on libattr, but it isn't a build dependency? [build-deps]
WARNING: QA Issue: pytalloc rdepends on libattr, but it isn't a build dependency? [build-deps]
WARNING: QA Issue: libtalloc rdepends on libattr, but it isn't a build dependency? [build-deps]
JIRA: SB-6141
> libtevent, libtdb, talloc: Fix build-deps warnings

- meta-mentor-staging/recipes-connectivity/samba/samba_4.1.12.bbappend
Add missing dependency avahi to fix following warnings:
WARNING: QA Issue: samba rdepends on libavahi-common, but it isn't a build dependency? [build-deps]
WARNING: QA Issue: samba rdepends on libavahi-client, but it isn't a build dependency? [build-deps]
Add missing dependency libaio to fix following warning:
WARNING: QA Issue: samba rdepends on libaio, but it isn't a build dependency? [build-deps]
JIRA: SB-6141
> samba: fix build-deps qa warnings

- meta-mentor-staging/recipes-devtools/opkg/opkg/0001-md5-Add-md5_to_string-function.patch
- meta-mentor-staging/recipes-devtools/opkg/opkg/0002-sha256-Add-sha256_to_string-function.patch
- meta-mentor-staging/recipes-devtools/opkg/opkg/0003-opkg_download-Use-md5sum-of-src-URI-as-cache-file-na.patch
- meta-mentor-staging/recipes-devtools/opkg/opkg_0.3.0.bbappend
His patch series from the opkg-devel list changes the package cache to use
checksums rather than the url for the filename, avoiding the filename length
issue.
JIRA: SB-6120
I tested this locally, and it fixed the problem here.
> opkg: apply Paul Barker's cache fixes

- meta-mel/conf/distro/include/mel.conf
This requires a patched bitbake, as the changes have not yet been merged
upstream.
JIRA: SB-5999
> mel: enable shallow git tarballs

- meta-mel-support/recipes-core/meta/archive-release.bb
- scripts/setup-mel-builddir
Rather than relying on it being set in the templates coming out of
archive-release, we can just check to see if the codebench path actually
exists, and if so, adjust it when creating local.conf from local.conf.sample
in our setup scripts.
This fixes EXTERNAL_TOOLCHAIN not being set correctly for the qemu machines.
JIRA: SB-6115
> setup-mel-builddir: set EXTERNAL_TOOLCHAIN here

- meta-mentor-staging/recipes-graphics/mesa/mesa_11.0.4.bb
JIRA: SB-5983
Upstream-Status: pending
This enables EGL/GLES2 functionality on ARMv7 platforms.
The GCC-5.2 has issue with alignment on ARMv7 hence
causing traps to occur that leads to EGL/GLES2 failures.
> mesa: update to version 11.0.4 for armv7 platforms

- scripts/toaster_configuration
Toaster is not following the DL_DIR in local.conf. Hence
creating symlink of downloads folder if available outside
build directory.
> toaster_configuration: Create sym link to downloads folder

- meta-mel/fsl-arm/recipes-kernel/linux/linux-ls1/0001-serial-fsl_lpuart-Remove-unneeded-check-for-res.patch
- meta-mel/fsl-arm/recipes-kernel/linux/linux-ls1/0002-serial-fsl_lpuart-Remove-unneeded-registration-messa.patch
- meta-mel/fsl-arm/recipes-kernel/linux/linux-ls1/0003-tty-serial-fsl_lpuart-clear-receive-flag-on-FIFO-flu.patch
- meta-mel/fsl-arm/recipes-kernel/linux/linux-ls1_3.12.bbappend
JIRA: SB-6248
The receive interrupt function lpuart_rxint checks the
FIFO count, which is 0 at that point (due to the flush
during initialization). The problem does not manifest
when using DMA to receive characters.
Explicitly read the status register, which leads to
clearing of the RDRF flag.
> linux-ls1: Fix LPUART RX flag on FIFO Flush

- meta-mentor-staging/meta-ti/recipes-graphics/libgles/libgles-omap3_5.01.01.02.bbappend
Some of the libs require libxext/libdrm/libxfixes even though this is the
no-x11 recipe. Normally only the x11 recipe pulls those in. The remaining
file-rdeps are seemingly harmless, quiet them.
JIRA: SB-6260
> libgles-omap3: dep on libxext/libdrm, kill remaining file-rdeps

- scripts/toaster_configuration
Earlier download dir was referred from the BUILDDIR. Now
it has been referred from MELDIR. So if user creates build dir
in any location, the downloads dir will be created with reference
of MELDIR.
> toaster-configuration: Fix downloads dir

- meta-mentor-staging/fsl-ppc/recipes-kernel/linux/files/0001-powerpc-module-avoid-memmove-in-dedotify.patch
- meta-mentor-staging/fsl-ppc/recipes-kernel/linux/linux-qoriq_3.12.bbappend
memmove() is essentially a memcpy() on powerpc64. dedotify() does
a memmove() to remove the leading dot from undefined symbol names
it is simply more efficient to offset st_name and arguably more
correct (other ELF objects could be pointing to this string). At
some point, a correct memmove() implementation is needed for power
(especially for cases like this where the source and destination
overlap). There are indeed other memmove() calls in the kernel...
Upstream-Status: Pending
JIRA: SB-6226
Signed-off-by: Cedric Hombourger <Cedric_Hombourger@mentor.com>
> linux-qoriq: powerpc/module: avoid memmove() in dedotify()

- meta-mentor-staging/recipes-devtools/python/python/0001-ensure-usage-of-native-modules-while-cross-compiling.patch
- meta-mentor-staging/recipes-devtools/python/python_2.7.9.bbappend
During build of shared modules the interpreter is trying to
import modules from the freshly built target side directories.
This fails where the generated module code is target architecture
specific and the build fails with an illegal instruction error.
The issue can be reproduced for any machine by adding the
-march=bdver4 flag inserted in the TUNE_CC_ARGS which generates
quite target specific code.
We fix this by modifying the PYTHONPATH variable which augments
the default search path.
> python: ensure usage of native modules while cross compiling

- meta-mentor-staging/recipes-graphics/mesa/mesa-demos/0001-drop-demos-dependant-on-obsolete-MESA_screen_surface.patch
- meta-mentor-staging/recipes-graphics/mesa/mesa-demos_8.2.0.bbappend
mesa-demos using EGL_MESA_screen_surface should be dropped
as the mentioned surface extension has been obsoleted in
mesa and the demos do not work.
Patch imported and backported from
http://cgit.freedesktop.org/mesa/demos/commit/?id=74443c6ee79f3251f643ea05e94df58183e37d0d
> mesa-demos: drop obsolete demos

- meta-mel-support/recipes-graphics/mesa/mesa-demos_8.2.0.bbappend
- meta-mentor-staging/recipes-graphics/mesa/mesa-demos/0002-only-build-GLX-demos-if-needed.patch
- meta-mentor-staging/recipes-graphics/mesa/mesa-demos_8.2.0.bbappend
We do not support GLX on MEL rather we use EGL. Although
some of the GLX demos still work but we should remove
these to clearly cleanup things that are irrelevant for
our distro.
JIRA Ticket: INTAMDDET-1047
> mesa-demos: disable GLX demos

- meta-mentor-staging/classes/metadata_scm.bbclass
We don't want the user to see errors from the git commands run by
metadata_scm on their console, so we need to capture or suppress stderr as
well as stdout. This was the case prior to the rewrite of the git hash
logic, but the 2>&1 was lost when it was reworked. Bring it back to avoid
messages like this in builds with non-git layers:
fatal: Not a git repository (or any of the parent directories): .git
JIRA: SB-6295
> metadata_scm.bbclass: restore capture of stderr

- meta-mel/fsl-arm/recipes-kernel/linux/files/0001-module.c-change-the-load_module-optimization-to-0.patch
- meta-mel/fsl-arm/recipes-kernel/linux/linux-ls1_3.12.bbappend
JIRA: SB-5400
This will ensure that kernel modules will have stable
symbols that allow proper debugging.
> linux-ls1: Change optimization level of load_module

- meta-mentor-staging/recipes-graphics/mesa/mesa_11.0.4.bb
Moving GLES3 headers to libgles2-mesa-dev package fixes the build
issue caused by Qt Creator while building Qt examples in ADE.
SB-6330
> mesa: Move GLES3 headers to libgles2-mesa-dev package

- meta-mel/fsl-ppc/recipes-kernel/linux/files/0001-kernel-module-change-the-optimization-level-of-load_.patch
- meta-mel/fsl-ppc/recipes-kernel/linux/linux-qoriq_3.12.bbappend
This will provide a stable debug symbol with GCC-5.2.
JiraID: SB-5400
> linux-qoriq: module.c: change load_module() optimization to 0

- meta-mentor-staging/recipes-support/ctdb/ctdb_2.5.1.bbappend
Since recipe does not provide configuration files needed to
start the service successfully, disable the service to
quiet failure message.
JIRA: SB-6335
> ctdb: disable servcie at startup

- meta-mentor-staging/recipes-multimedia/pulseaudio/pulseaudio_6.0.bbappend
We need the pulseaudio-module-bluetooth-discover even in the case of bluez5
because it in turn loads the correct version of bluez-discover module. And
in case of bluez5, installing just pulseaudio-module-bluetooth-discover is
not sufficient, we need pulseaudio-module-bluez4-discover as well in that
case.
Jira: http://jira.alm.mentorg.com:8080/browse/SB-6280
> pulseaudio: include missing bluetooth modules

- meta-mel/conf/distro/include/mel.conf
- meta-mentor-staging/recipes-core/netbase/netbase_%.bbappend
- meta-mentor-staging/recipes-core/systemd/systemd_%.bbappend
Rather than hardcoding our hostname in /etc/hosts to ensure it resolves, we
can use the nss service/library via nsswitch.conf. systemd includes it
already, but needed to enable it, and the nss-myhostname package provides it
for sysvinit images. This is cleaner, more flexible, and avoids the assumption
that the hostname is always the MACHINE, which our netbase bbappend was
making.
> Switch to use of nss myhostname

- meta-mel/lib/recipetool/kernel.py
It turns out kernel-yocto.bbclass will use a defconfig as a baseline
configuration if it's installed to WORKDIR, so we can remove the check which
aborts this sub-command for those recipes. The configuration will likely be
altered from the baseline based on the scc files and configuration fragments,
but we can set the initial baseline configuration.
JIRA: SB-6350
> recipetool.kernel: enable defconfig for kernel-yocto

- meta-mentor-staging/recipes-support/talloc/talloc_2.1.1.bbappend
Toaster is not taking the layer priorities appropriately and
hence do_configure in waf-samba.bbclass is not taken. So the
only work around is to bring the do_configure into the bbappend
of talloc.
JIRA: SB-6364
> talloc: do_configure needs to be updated to work with toaster

- scripts/toaster_configuration
The layer information in toasterconf.json file is in the reverse
order compared to bblayers.conf. Hence toaster creates BBLAYERS
in the reverse order. This was the root cause for SB-6364.
JIRA: SB-6372
> toaster: Fix layers created in toasterconf.json file

- meta-mel/fsl-arm/recipes-kernel/linux/files/0005-kernel-module.c-Remove-optimization-for-complete_for.patch
- meta-mel/fsl-arm/recipes-kernel/linux/linux-ls1_3.12.bbappend
JIRA: CB-5785
This will disable optimization for complete_formation function and
will retain local variable in contexts.
> linux-ls1: kernel/module: Remove optimization for complete_formation

- meta-mel/conf/distro/include/mel.conf
Export COREBASE, TOPDIR as OE_TOPDIR, and WORKDIR as OE_WORKDIR into the
devshell. This makes it easier to copy files back out of the devshell to your
layers or build directory.
[YOCTO #7670]
> mel: export path vars into the devshell

- scripts/setup-ubuntu
* Windows ADE need zip packaged to be available on host.
SB-6361
> setup-ubuntu: Add zip package which is needed for Windows ADE

- meta-mel/conf/local.conf.append.cyclone5
Since this snippet gets appended to local.conf, where the user/customer
will see it, it would be appropriate to add this comment so they know
why it's being done.
> local.conf.append.cyclone5: Add comment about u-boot

- meta-mel/intel/recipes-graphics/xorg-xserver/xserver-xf86-config/intel-corei7-64/xorg.conf
- meta-mel/intel/recipes-graphics/xorg-xserver/xserver-xf86-config_0.1.bbappend
JIRA: SB-6507
This will allow default modules to be loaded and lets
display stay online without going into stand-by mode.
> MinnowMAX: Add default xorg.conf

- scripts/bb-determine-layers
- scripts/setup-mel-builddir
Previously, rng-tools 4 from meta-oe was used in preference to oe-core's 5. This isn't ideal, to handle the priority consistently. Technically there is a reason one might want to use meta-oe as higher priority than oe-core even with it just being a pool of extra recipes, and that reason is that those extra recipes may require specific versions of things, but I think we can deal with that theoretical possibility if and when it comes up, and we want to track oe-core as closely as possible.
> Improve priority override handling

- meta-mel/conf/local.conf.append.intel-corei7-64
JIRA: SB-6722
This will pull only minimal subset of wireless firmware
instead of all available firmware files.
> intel-corei7-64: Replace linux-firmware with firmware-wireless

- meta-mel/intel/recipes-kernel/linux/linux-yocto_4.1.bbappend
This adds git shallow mirror tarball support.
> MinnowMAX: linux-yocto: Add git shallow support

- meta-mel/intel/scripts/mkefidisk.sh
Fix bashism when writing to startup.nsh. The back slash
are not taken care on dash. With this change it is taken
care.
JIRA: SB-6725
> mkefidisk.sh: Fix bashism when writing to startup.nsh

- meta-mel/conf/local.conf.append.intel-corei7-64
Add vfat support in MACHINE_FEATURES
JIRA: SB-6727
> local.conf.append.intel-corei7-64: Add vfat support

- meta-mel/conf/local.conf.append.cyclone5
Use _append because we want to preserve the IMAGE_FSTYPE value assigned
with ?= operator.
> cyclone5: Use _append instead of += in IMAGE_FSTYPES

- meta-mel/conf/local.conf.append.intel-corei7-64
JIRA: SB-6703
This is needed for partitioning media device on
host while formatting and preparing a device.
> intel-corei7-64: wic: install parted-native tool

- meta-mel/scripts/lib/wic/canned-wks/minnowmax-sd-4g.wks
- meta-mel/scripts/lib/wic/canned-wks/minnowmax-sd-8g.wks
JIRA: SB-6703
Add 4GB & 8GB WKS files for SD Card WIC image
creation.
> minnowmax: Add 4g/8g WKS files for WIC support

- meta-mel/intel/scripts/mkefidisk.sh
Remove echo with printf for reusability of the script.
Also remove checks for particular shell. This one line
change should fix the issue.
SB-6725
> mkefidisk.sh: Replace echo with printf

- meta-mel/meta-altera/recipes-graphics/wayland/weston_1.8.0.bbappend
Add missing dependencies libevdev and libinput to fix
build-deps QA Issues.
> weston: fix build-deps qa issues

- meta-mel/conf/local.conf.append.cyclone5
- meta-mel/meta-altera/recipes-core/images/console-image.bbappend
- meta-mel/meta-altera/recipes-sato/images/core-image-sato.bbappend
Conditionally add Java support to console image or
core-image-sato if ENABLE_JAVA is set to "1" in local.conf.
JIRA: SB-6588
> add java support for console and core-image-sato for cyclone5

- meta-mel/recipes-multimedia/mplayer/mplayer2_git.bbappend
- meta-mentor-staging/openembedded-layer/recipes-multimedia/mplayer/mplayer2/0001-demux_ogg-partially-port-libtheora-glue-code-to-Theo.patch
- meta-mentor-staging/openembedded-layer/recipes-multimedia/mplayer/mplayer2_git.bbappend
- meta-mentor-staging/openembedded-layer/recipes-multimedia/webm/libvpx_1.4.0.bbappend
This fixes issues while building/deploying mplayer2 which is now a required package for Cedar (asyncs).
> mplayer2 support

- meta-mel/conf/distro/include/mel.conf
- meta-mentor-staging/classes/bootimg-wic.bbclass
do_image_wic needs to depend upon do_bootimg when both are used.
> Fix wic image type with bootimg images

- meta-mel/conf/local.conf.append.intel-corei7-64
Since we are using wic.bz2, sysroot needs the pbzip2
command for compression of wic image.
> minnowmax: install required compression command

- meta-mel/meta-altera/recipes-graphics/wayland/weston_1.8.0.bbappend
Use correct conditional syntax for appending to the DEPENDS
variable. Earlier syntax was overriding the items previously
assigned to DEPENDS thus causing build-deps warnings and build
failures resulting from missing dependencies.
libinput, which also pulls in libevdev, is already in DEPENDS
in the main recipe, so no need to add these packages here
again.
JIRA: SB-6825
> weston: fix build failure due to wrong syntax

- meta-mel/conf/local.conf.append.cyclone5
* Set PREFERRED_PROVIDERs for make-native and java2-runtime to
quiet build time NOTEs.
* openjdk-7-jre requries x11 as a distro feature but we disable
it while building weston-image. Update the comment to remove
weston-image from the list of Java supported images.
* Fix typos:
s/JAVA/Java
s/java/Java
JIRA: SB-6820
> cyclone5: set preferred providers to quiet notes

- meta-mentor-staging/classes/bootimg-wic.bbclass
Rather than relying on the order of anonymous python executions meeting our
expectations, avoid the do_image_wic existance check entirely. It's not
needed, as running the addtask when the task doesn't exist isn't actually
harmful.
> bootimg-wic: remove the do_image_wic check

- meta-mel/conf/local.conf.append.intel-corei7-64
JIRA: SB-6983
Since we have different mechanism employed for WIC
image creation for minnowmax due to processing method
involved in generating live boot image, deploy the
WIC image exclusively in release artifacts so that
we have bootable rootfs in binary folder.
> intel-corei7-64: bundle wic image in release-artifacts

- meta-mentor-staging/recipes-kernel/lttng/lttng-tools/0001-Fix-regression-tests.patch
- meta-mentor-staging/recipes-kernel/lttng/lttng-tools_2.6.0.bbappend
run-ptest of lttng-tools when executed was not landing
back to shell prompt. Hence cherry-pick'ed the upstream
patch. This patch fixes the issue related to landing
back to shell prompt after execution of the test suite.
JIRA: SB-6972
> lttng-tools: Add upstream patch for regression test

- meta-mel/intel/recipes-graphics/mesa/mesa_10.6.3.bbappend
Adding GLES3 headers to libgles2-mesa-dev solves
the problem when user tries to verify Qt5 examples
using Qt Creator.
JIRA: SB-6993
> mesa: Add GLES3 headers to libgles2-mesa-dev

- meta-mel/meta-altera/recipes-bsp/u-boot/u-boot-socfpga_2013.01.01.bbappend
- meta-mel/scripts/mk-cyclone5-boot-part.sh
* Preserve the u-boot ELF files in deploy folder.
* Correct the SPL binary file-name in sd-card preparation script.
> Cyclone5 u boot fixes

- meta-mel/conf/local.conf.append.cyclone5
Although we only need to support mounting of already created file-systems,
we are adding tools to create and modify file-systems for consistency with
other BSPs in Cedar release. This should be removed in Dogwood release.
> cyclone5: add tools to create and modify file-systems

- meta-mentor-staging/recipes-gnome/gobject-introspection/gobject-introspection_1.46.0.bbappend
This was resulting in non-deterministic builds where g-ir-doc-tool may or may
not exist depending on whether python-mako was built previously. Add
a PACKAGECONFIG so the dependency is explicit.
> gobject-introspection: fix floating dep on python-mako

- meta-mentor-staging/recipes-devtools/dmidecode/dmidecode_3.0.bbappend
It was putting its AUTHORS, README, and CHANGELOG in the root of
/usr/share/doc.
> dmidecode: move docs into a subdir of docdir

- meta-mentor-staging/meta-ti/recipes-ti/devtools/ti-cgt6x_8.0.3.bbappend
This was an old workaround which isn't needed now.
> ti-cgt6x: drop

- meta-mel/conf/local.conf.append.cyclone5
mpv depends on packages that require commercial license, so it is not
enabled by default.
> mpv: add mechanism to include mpv in build

- meta-mel/conf/distro/include/mel.conf
Upstream renamed the variable.
> mel: INITRD_IMAGE -> INITRD_IMAGE_LIVE

- meta-mel/conf/local.conf.append.cyclone5
Certain gstreamer plugins and components have license restrictions and
cannot be included in MEL build by default.
> gstreamer: add mechanism to include plugins with commercial license

- meta-mel/conf/local.conf.append.intel-corei7-64
linux-firmware-i915 is needed for the graphics, according to meta-intel, so
firmware-wireless is no longer sufficient. Either we switch back to
linux-firmware, or also split off i915 into its own recipe the way we did
the wireless firmware.
Without this, both recipes end up building, conflicting, and resulting in
warnings/errors in the build.
> Switch back to linux-firmware for minnowmax

- scripts/setup-mel-builddir
meta-haswell-wc is an extra level deep in meta-intel, so we need to check one
level deeper for layers. If we recurse into `*/*/*` rather than `meta*/*/*`, the
layer search can take quite a long time due to searching into downloads/ and
cached-binaries/, unless we add exclusions.
> setup-mel-builddir: recurse an extra level in meta* dirs

- meta-mentor-staging/classes/bootimg-wic.bbclass
The bootimg class no longer exists, so we can't use that to determine
whether to run the addtask.
> bootimg-wic: fix the class

- meta-mel/conf/distro/include/mel.conf
Currently, bitbake is erroring with a taskbase hash mismatch due to the ade
version string changing between the main bitbake process which checks
sstate and the worker process that runs the task.
So, exclude the datetime from the checksums to avoid this mismatch. This
means a bitbake of populate_ade won't re-run every time, but when it does
re-run, the version will still increment. This retains the properties we
need of the versioning while fixing the bitbake error.
> mel: exclude DATETIME_SECS from checksums

- scripts/bb-determine-layers
- scripts/setup-mel-builddir
- setup-environment
This is based on some cleanup and refactoring work I had done back in february of 2014, but which was never polished off and finished. I've now done so.
- Refactor bb-determine-layers to make it easier to submit setup script improvements to oe-core in the future
- Rather than hardcoding the dep on the 'mel' layer, instead search for and include the layers that provide `$MEL_DISTRO`, which will make it easier for mel-based products
- Display the layers which are found, and if -v is passed, display the layer paths which were found
- Add more status output so the user knows what the script is doing
- Return a correct exit code from the setup script so the user can respond to a failure from setup-mel-builddir
- Add an arg to bb-determine-layers so we can include the layers needed for a given …
> Setup script improvements

- meta-mel/scripts/mk-cyclone5-boot-part.sh
Checking the UID environment variable doesn't work with dash, so use the
'whoami' command.
> mk-cyclone5-boot-part.sh: modify the way we check root access

- meta-mel-support/recipes-core/meta/archive-release.bb
- meta-mel/conf/distro/include/mel.conf
Include probe configuration files for a particular machine if they are
present in meta-mentor-private. If the files are not there or
meta-mentor-private layer isn't included, they will be silently skipped.
> archive-release: include probe configuration files

- meta-mentor-staging/recipes-sato/webkit/webkitgtk_%.bbappend
Upstream handles this automatically, and removing it doesn't result in any
build warnings now.
> webkitgtk: drop the manual dbg packaging bits

- meta-mentor-staging/classes/bootimg-wic.bbclass
This kills errors seen when building a non-wic hddimg.
> bootimg-wic: only add dep if do_image_wic exists

- meta-mentor-staging/recipes-kernel/lttng/lttng-tools_2.6.0.bbappend
0001-Fix-regression-tests.patch is not architecture specific so remove
the x86-64 override.
JIRA: http://jira.alm.mentorg.com:8080/browse/SB-7174
> lttng-tools: remove the override

- meta-mel/lib/recipetool/kernel.py
The expand argument is no longer optional.
> recipetool.kernel: fix getVarFlag use in kernel_add_fragments

- meta-mel/intel/recipes-kernel/linux/linux-yocto_4.4.bbappend
They were being applied to 4.1 only, from the cedar release, but 4.4 is
default now, so apply our changes to both.
> For MinnowMAX, also apply our changes to linux-yocto 4.4

- meta-mel/conf/local.conf.append.cyclone5
Update the disclaimer text about the license restricted components. We
got this text approved from the legal department.
I have also moved the variable for multimedia packages with the MPV selection variable so that it would be more convenient for the user to find the variable without looking at the more complex code that follows.
> local.conf.append.cyclone5: Update disclaimer text

- meta-mel-support/recipes-core/meta/archive-release.bb
- meta-mel-support/recipes-core/packagegroups/packagegroup-role-nas.bb
- meta-mel-support/recipes-core/packagegroups/packagegroup-role-print-server.bb
- meta-mel-support/recipes-core/packagegroups/packagegroup-role-router.bb
- meta-mel-support/recipes-core/packagegroups/packagegroup-tools-audio.bb
- meta-mel-support/recipes-core/packagegroups/packagegroup-tools-benchmark.bb
Upstream no longer requires this for recipes which have no sources, and
poky/LICENSE has changed, so all these would need updating to fix the build
anyway.
> Drop unneeded LICENSE / LIC_FILE_CHKSUM

- meta-mentor-staging/recipes-devtools/syslinux/syslinux_6.03.bbappend
This reverts commit 5b7608cbac007fe5e0e5622c0514bd47a8d416d7.
The changes to LD were made upstream with commit
http://cgit.openembedded.org/openembedded-core/commit/meta/recipes-devtools/syslinux?id=c4897af85eace49e3c27aebc1448227105286e30
and all other variables fixed with the meta-mentor commit
in question also show up correctly.
> Revert "syslinux: obey our binutils vars"

- meta-mentor-staging/openembedded-layer/recipes-benchmark/lmbench/lmbench_3.0-a9.bbappend
1. We don't use this to ship lmbench configurations anymore.
2. It hardcodes an assumption that the hostname matches up with machine name.
> lmbench: drop the MACHINE config bits

- meta-mel-support/recipes-kernel/firmware-wireless/firmware-wireless_git.bb
This works around a do_populate_lic limitation. do_populate_lic apparently
expects the license files to always have unique basenames, particularly for
NO_GENERIC_LICENSE, but this wasn't the case here.
A yocto bug has been opened to track this limitation.
[YOCTO #9663]
JIRA: SB-7212
> firmware-wireless: quiet warnings from do_populate_lic

- meta-mentor-staging/meta-arago-extras/recipes-connectivity/obex/obexd_0.34.bbappend
- meta-mentor-staging/xilinx/recipes-bsp/platform-init/platform-init.bbappend
These recipes in meta-arago-extras and meta-xilinx use invalid files:// urls
in their LIC_FILES_CHKSUM.
> platform-init,obexd: fix odd files:// bugs

- meta-mel/conf/distro/include/mel.conf
As we prefer wic images for our BSPs, we can automatically enable such images
when a wks file exists for this BSP. If it exists, then either the WKS_FILE
has been changed (presumably by the BSP), or the default path which includes
the MACHINE exists. In either case, we can assume the existence of such a file
indicates wic support is available for this BSP, so use it.
> mel: enable wic fstypes if a wks exists

- meta-mel/classes/wic_wks_template.bbclass
- meta-mel/conf/distro/include/mel.conf
This will hopefully be merged upstream soon and we can drop it from here, but
in the meantime we can start making use of it.
These files are treated as the contents of a bitbake variable, so usual
bitbake variable references are supported. I considered using another
templating mechanism, for example the one used by yocto-layer, but then we'd
end up largely mapping metadata variables to template fields anyway, which is
a pointless indirection. Let bitbake expand the variables directly instead.
This feature lets us, for example, reference ${APPEND} in --append, and avoid
hardcoding the serial console tty in the wks file, and let the user's changes
to APPEND affect wic the way they do the other image construction mechanisms.
The template is read in and set in a variable at parse time, so …
> mel: add support for .wks.in templates

- meta-mel-support/conf/layer.conf
This layer exists to provide additional recipes for use by Mentor Graphics,
where it's not appropriate to keep them in meta-mel (for yocto compliance
reasons) or meta-mentor-staging (not for upstream), so we don't want appends
collecting here.
> meta-mel-support: remove bbappend from layer.conf

- meta-mentor-staging/recipes-multimedia/mplayer/mpv_0.15.0.bb
* Inherit pythonnative to fix manpage compilation error. Without
this bitbake uses system python instead of the sysroot one and
is unable to locate required modules.
* Add PACKAGECONFIG for package jack to fix build-deps QA Warning.
* Set SIMPLE_TARGET_SYS before running the configuration script in
do_configure. This got left out when bits were copied from mplayer2
recipe.
> mpv: fix manpage compilation error

- meta-mel/conf/local.conf.append.imx7dsabresd
- meta-mentor-staging/fsl-arm/recipes-graphics/directfb/directfb_1.7.4.bbappend
- meta-mentor-staging/recipes-core/systemd/systemd-serialgetty.bbappend
- meta-mentor-staging/recipes-core/systemd/systemd-serialgetty/serial-getty@.service
meta-fsl-arm "jethro" provides imx7dsabresd machine file.
. directfb is removed in meta-fsl-arm stating that the project is dead upstream
. set preferred provider to uboot-imx instead of uboot-fslc
. systemd workaround for the random bug when boot hangs at serial-getty service.
Signed-off-by:  Adnan Ali <Adnan_Ali@mentor.com>
> initial support for Imx7 based sabresd board

- conf/local.conf.sample
This file currently lives in meta-mel, and our setup scripts can be used with
other distros by setting MEL_DISTRO , so meta-mel might or might not be
currently in BBLAYERS. Switch to include so it's non-fatal if it's missing.
> local.conf.sample: use include, not require for drop-toolchain-from-sdk

- meta-mel/conf/distro/include/mel.conf
- meta-mentor-staging/openembedded-layer/recipes-core/plymouth/plymouth_%.bbappend
We aren't using dracut for initramfs construction, so there's no need to pull in the dependency and therefore the meta-initramfs layer.
> plymouth: disable dracut

- meta-mel/conf/distro/include/mel.conf
This ensures vmlinux ends up in tmp/deploy/images/${MACHINE}, next to the
kernel and disk images, which is useful for debugging.
> mel: add vmlinux to KERNEL_IMAGETYPES by default

- meta-mel/conf/distro/include/mel.conf
libjpeg-turbo is default in oe-core now.
> mel: drop the libjpeg-turbo pref

- meta-mentor-staging/recipes-devtools/ruby/ruby_%.bbappend
rdoc gets unhappy if this already exists, so remove it before building.
Without this, it's possible to hit this error:
Directory .ext/rdoc already exists, but it looks like it isn't an RDoc
directory.
> ruby: ensure that .ext/rdoc is gone in compile

- meta-mentor-staging/recipes-kernel/lttng/files/0001-Fix-ctf_string-should-handle-NULL-pointers.patch
- meta-mentor-staging/recipes-kernel/lttng/lttng-modules_git.bbappend
The issue has been recently fixed upstream and the fix is available in
LTTng modules version 2.7.4, but not in version 2.7.3 that we are currently
using in Dogwood. Back-porting the patch for now.
Upstream commit: http://git.lttng.org/?p=lttng-modules.git;a=commit;h=8e4b115ba22066b923d36ff230a7c155f59f03de
Jira: http://jira.alm.mentorg.com:8080/browse/SB-7450
> lttng-modules: Fix crash in LTTng kernel tracing

- meta-mentor-staging/openembedded-layer/recipes-extended/cmpi-bindings/cmpi-bindings/Find-PythonInterp-before-PythonLibs.patch
- meta-mentor-staging/openembedded-layer/recipes-extended/cmpi-bindings/cmpi-bindings_git.bbappend
A newer host python (i.e. 3.5) was being preferred over the python we built,
causing failures.
> cmpi-bindings: use python-native

- meta-mel-support/recipes-bsp/96boards-tools/96boards-tools_0.7.bb
resize-helper will resize the rootfs partition and filesystem to the available
capacity, which is invaluable for sd card images, where the size may not
necessarily be known at image creation time.
> 96boards-tools: add recipe for resize-helper

- meta-mel/classes/layerdirs.bbclass
meta-yocto's layer.conf exists only to allow parsing of old build dirs, but as
it doesn't set BBFILE_COLLECTIONS, including it will cause our
layerdirs.bbclass to error. Fix that by handling the var being unset.
> layerdirs: handle empty BBFILE_COLLECTIONS

- meta-mentor-staging/qt4-layer/recipes-qt4/qt4/qt4-native_%.bbappend
We don't care whether qt4-native is stripped, so this quiets the sysroot strip
warnings.
> qt4-native: add already-stripped to INSANE_SKIP

- meta-mentor-staging/meta-java/recipes-core/xml-commons/xpp2_%.bbappend
- meta-mentor-staging/meta-java/recipes-core/xml-commons/xpp3_%.bbappend
This was breaking on hosts with dash as /bin/sh.
> xpp[23]: fix/remove bashism

- scripts/setup-rh
To install python34, we have to install epel-release first.
This fixes builds on centos7.
JIRA: SB-7503
> setup-rh: install python34, wget, perl-Thread-Queue

- meta-mel/conf/distro/include/mel.conf
Align the external toolchain with the internal one. This is also needed for
Sourcery Analyzer with lttng-ust.
JIRA: SB-7585
> mel: add -Wl,--build-id=sha1 to LDFLAGS

- meta-mel/conf/include/wic-ppc.inc
dtb paths are now prefixed with 'fsl/' in meta-fsl-ppc machine
files. Update ${IMAGE_BOOT_FILES} accordingly.
JIRA: SB-7588
> wic-ppc.inc: Use correct dtb path

- meta-mel/openembedded-layer/recipes-multimedia/mplayer/mplayer2_git.bbappend
For MEL on the required BSPs we now use mpv which is
the better suited option so the changes for mplayer2
are not needed anymore and are irrelevant.
> mplayer2: drop changes from our layer

- meta-mel/conf/local.conf.append
These are used by mel.conf, so this is really where they belong.
> meta-mel: add local.conf.append with ADE vars

- meta-mel-support/recipes-kernel/firmware-wireless/firmware-wireless_git.bb
Update source and destination paths for licenses in
hack_around_do_populate_lic_limitations function. With this
change the do_unpack doesn't fail to unpack.
> firmware-wireless: Update source and destination paths for licenses

- meta-mel-support/recipes-core/meta/archive-release.bb
For git repositories, which use commit counts for versions, we want to limit
the commit count to the current path, so it doesn't increase due to changes in
unrelated layers.
JIRA: SB-7773
> archive-release: limit version to the sub-repo

- setup-environment
customer.conf was being checked in $layerdir/.. ($MELDIR), but the
CUSTOMER-custom directory was found relative to $PWD. Fix this by searching
both locations for both, preferring $PWD to $MELDIR, the same way we do our
layer searching.
JIRA: SB-6369
> setup-environment: check both $MELDIR & $PWD for customer bits

- meta-mel-support/recipes-core/plymouth/plymouth-mel.bb
The license-checksum checks are run through populate_lic_qa_checksum()
which does not handle INSANE_SKIP. We drop the checking altogether
by removing it from the ERROR_QA list.
JIRA Ticket: SB-7753
> plymouth-mel: correctly handle license-checksum error

- scripts/toaster_configuration
As per the latest changes in the upstream django fixutres are used
to populate the default values for toaster instead of fixtures.
This script has been modified for the same. A new custom.xml
file will be generated which will be read by toaster and pre populate
the default values for our local changes.
JIRA: SB-7649
> toaster_configuration: update this script to generate custom fixtures

- meta-mentor-staging/recipes-devtools/ruby/ruby_%.bbappend
We can remove ruby bbappend from meta-mentor-staging
> ruby: Remove ruby bbappend

- scripts/toaster_configuration
Remove orm.bitbakeversion from the fixtures. No need to redefine
it. This was missed in my previous commit for this file.
> toaster_configuration: Remove orm.bitbakeversion from fixtures

- meta-mentor-staging/recipes-multimedia/gstreamer/gstreamer1.0-libav_%.bbappend
This recipe can be removed safely as the changes are
already available upstream:
http://git.openembedded.org/openembedded-core/commit/?id=4438a1125bb15ed19c78833f4d8a5b108cd91d30
> gstreamer1.0-libav: This change can be removed safely

- meta-mentor-staging/recipes-multimedia/mpeg2dec/mpeg2dec_0.4.1.bbappend
This recipe can be removed safely. With upstream
meta-altera, tried to build it. But that didn't
showed up any warning.
> mpeg2dec: Recipe can be removed safely

- meta-mentor-staging/networking-layer/recipes-kernel/netmap/netmap-modules_%.bbappend
This reverts commit b1e6474ad959ba343f27194a37b7b0252f803092.
The problem has been addressed upstream in meta-oe with the following commit
https://github.com/openembedded/meta-openembedded/commit/80cf5e0ee961436fbcb2fa2c03cb709f79fa9e3c
> Revert "netmap-modules: work around python 3 issue with bb.utils.vercomp

- meta-mentor-staging/xilinx/recipes-bsp/platform-init/platform-init.bbappend
This change has been merged upstream. Hence
we can drop this change safely.
> platform-init: Change have been merged upstream

- meta-mentor-staging/classes/sdk_auto_relocate.bbclass
The -i (inline) and -e (expression) options of sed command cannot be
combined. Passing them as -ie creates a backup of the original file with
'e' appended to the file name.
JIRA: http://jira.alm.mentorg.com:8080/browse/SB-7175
> sdk_auto_relocate.bbclass: fix 'sed' command

- meta-mel/classes/user_features.bbclass
Currently, the items used in _append/_prepend/_remove are not
deterministically ordered, as they're using sets and don't sort them before
setting the variables. Correct this by sorting the sets, which avoids
unnecessary config file reparsing due to ordering changes.
> user_features: fix non-deterministic ordering

- meta-mentor-staging/recipes-multimedia/x264/x264_git.bbappend
This change got merged upstream. Hence we can
safely remove this change from the layer.
Upstream commit: http://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=aa7f7b63485b8c4d33491b9cd467fc4487a281c7
JIRA: SB-8059
> x264: This change can be removed safely

- meta-mentor-staging/recipes-core/psplash/files/psplash-quit.service
- meta-mentor-staging/recipes-core/psplash/files/psplash-start.service
- meta-mentor-staging/recipes-core/psplash/psplash_git.bbappend
The MEL distro configuration (mel.conf) allows specifying
the SPLASH variable to select between different packages
that provide the mechanism for displaying a splash. psplash
is one of these packages so we shouldn't remove this.
This reverts commit 413cbf8.
> Revert "pasplash: Remove psplash from the layer"

- meta-mentor-staging/recipes-kernel/perf/perf.bbappend
We need to revert this patch. The local builds
for minnow max is still failing. There is an
upstream patch posted:
http://lists.openembedded.org/pipermail/openembedded-core/2016-October/127281.html
Once this get merged, we can safely remove our
changes for perf.
This reverts commit 31049561fdca150ece2e18856a94f05e8725b3fc.
> Revert "perf: Remove this change safely"

- scripts/setup-mel-builddir
If $MELDIR/../../toolchains exists, set CODEBENCH_PATH rather than
EXTERNAL_TOOLCHAIN.
JIRA: SB-7881
> Add bits to handle the new codebench layout

- scripts/toaster_configuration
This patch fixes the meta layer addition to toaster. Without
this patch the meta layer was added but was not visible in the
UI. With this change it gets fixed.
> toaster_configuration: Fix the meta layer addition to toaster

- meta-mel-support/recipes-core/packagegroups/packagegroup-tools-benchmark.bb
The older, obsolete iperf v2 fails to build with GCCv6.  Upgrade
to v3 to resolve this build failure.
Signed-off-by: Drew Moseley <drew_moseley@mentor.com>
> iperf: Upgrade to iperf3

- meta-mentor-staging/classes/win_sdk_cull.bbclass
Some files are populated by find command that do not actually exist.
The issue is in case (upper/lower). Though manually running the command
does not reproduce this. No idea why this is happening, but this workaround
seems harmless to me. Submitting this PR for comments.
> win_sdk_cull.bbclass: Workaround invalid filenames

- meta-mel/recipes-core/psplash/mel/psplash-final.service
- meta-mel/recipes-core/psplash/psplash_git.bbappend
This adds the ability to launch the splash screen again
when the system is going to reboot, halt or shutdown
state.
> psplash: add service to launch splash on reboot, halt and shutdown

- meta-mel/conf/distro/include/mel.conf
There is a new splash image introduced in psplash along with
some cosmetic changes to reflect proper copyright information.
To revert back to plymouth, set the following:
SPLASH ?= "plymouth"
> mel.conf: switch to psplash from plymouth

- conf/local.conf.sample
We're using 64-bit toolchains in MEL now.
JIRA: SB-8249
> local.conf.sample: drop the SDKMACHINE default of i686

- pre-setup.t4240rdb-64b
Remove pre-setup.t4240rdb-64b from meta-mentor.
Move to meta-mentor-bsp/t4240rdb-64b once meta-fsl-networking has been
updated for this BSP.
JIRA: SB-8266
> pre-setup.t4240rdb-64b: move to meta-mentor-bsp

- pre-setup.ls1021atwr
JIRA: SB-8266
This belongs to BSP layer and should not reside here, add it to
internal bsp layer dependency of ls1021atwr.
> ls1021atwr: move pre-setup changes to bsp layer

- meta-mel/recipes-core/psplash/mel/psplash-quit.service
- meta-mel/recipes-core/psplash/mel/psplash-start.service
The psplash application checks for the TMPDIR environment
variable when starting and picks up /tmp as its temp dir
if this variable is not set. The /tmp gets mounted
pretty late in the boot process and on some faster booting
systems a failure can be seen where psplash-quit fails to
communicate with psplash-start because of a failure while
creating the communication pipe under this TMPDIR.
We now make use of the /run dir as the TMPDIR which is
available quite early in the boot process and avoids such
scenarios.
Also cleanup the psplash-quit service to drop the TimeoutSec
setting which is not applicable when the service is of type
oneshot.
> psplash-*.service: adjust TMPDIR

- scripts/list-recipes
- scripts/setup-mel-builddir
- scripts/toaster-layers-recipes-config.py
- scripts/toaster_configuration
This patchset has 2 commits.
First commit modifies 2 files:
a) setup-mel-builddir
b) toaster_configuration
and creates a new file toaster-layer-recipes-config.py
The change made here is to address the following:
1) Populate toaster db with the recipes and layers
2) Cosmetic change to rename the release name from
"Local Yocto Project" to "Mentor Embedded Linux"
To populate the toaster db the data is read from:
BUILDDIR/conf/recipes-list.txt
Second commit has changes for generating recipes-list.txt.
> Toaster script update to populate layers and recipes

- scripts/toaster_configuration
Add MGLS_LICENSE_FILE to toaster configuration
> toaster_configuration: Add MGLS_LICENSE_FILE from to config

- scripts/toaster_configuration
Once the toaster-setup-environment script is successfully
started, user should be able to see the browser opened
at the machine where toaster's setup script is sourced.
> toaster_configuration: Enable auto launch of browser

- scripts/toaster_configuration
Remove all complexities done using sed and grep.
Just use MGLS_LICENSE_FILE from the env directly.
> toaster_configuration: Use MGLS_LICENSE_FILE from env

- meta-mel-support/recipes-core/meta/archive-release.bb
This was needed when the srcrevs for autorev were supplied by the db, but now
we're supplying those via a .conf generated by buildhistory-collect-srcrevs,
so we no longer need to change this caching policy.
> archive-release: drop the srcrev cache policy change

- meta-mel/conf/distro/include/mel.conf
- meta-mentor-staging/classes/bbpath-intercepts.bbclass
- meta-mentor-staging/postinst-intercepts/update_gio_module_cache
We need to correct the ownership of the generated cache file, but only if a
cache file was generated (which is not the case when the modules dir is
empty).
JIRA: SB-8312, SB-8314
> update_gio_module_cache: fix postinst owner adjustment

- meta-mentor-staging/classes/bbpath-intercepts.bbclass
Having the cleandirs on do_rootfs resulted in the path being cleaned after
assemble_intercepts was run, and an empty intercepts dir being passed to the
rootfs construction, so no intercepts were run at all. Bitbake handles
cleandirs/dirs on a per-function, not per-task, basis, so it belongs on the
prefunc.
Thanks to Abdur Rehman for investigating this and identifying the root cause.
JIRA: SB-8314
> bbpath-intercepts.bbclass: set cleandirs on assemble_intercepts

- meta-mel/classes/user_features.bbclass
Rather than altering at ConfigParsed time, use _append/_remove directly.
> user_features: avoid timing-dependent variable changes

- meta-mel-support/recipes-devtools/binutils/binutils_2.17.50.0.12.bb
- meta-mel/classes/incompatible-recipe-check.bbclass
- meta-mel/conf/distro/include/gdbserver-gplv3.inc
- meta-mel/conf/distro/include/mel.conf
- meta-mel/recipes-core/packagegroups/packagegroup-core-tools-profile.bbappend
- meta-mentor-staging/openembedded-layer/recipes-support/lvm2/lvm2_%.bbappend
This fixes the issues other than the rootfs resizing, as the old parted as
different commands and syntax, so resize-helper needs to be altered to support
it.
> Fix issues with the non-GPLv3 builds

- meta-mentor-staging/openembedded-layer/recipes-benchmark/iperf/iperf/0001-Ensure-we-check-for-stdbool.h.patch
- meta-mentor-staging/openembedded-layer/recipes-benchmark/iperf/iperf_2.0.5.bbappend
iperf was conditionally checking for the size of bool based upon
ac_cv_header_stdbool_h, but wasn't actually calling AC_CHECK_HEADERS to make
sure that variable is set. Explicitly check for stdbool.h with
AC_CHECK_HEADERS and operate based upon that result.
Also correctly quote the first AC_DEFUN argument, while I'm here, to avoid the
warning from autoconf.
This issue was causing failures for MEL builds.
JIRA: SB-8356
> iperf: ensure we check for stdbool.h

- meta-mentor-staging/recipes-devtools/python/python3/0001-site.py-obey-sys.lib-for-sitepackages.patch
- meta-mentor-staging/recipes-devtools/python/python3/correct-python3-lib-pathes-for-multilib-support.patch
- meta-mentor-staging/recipes-devtools/python/python3_3.5.2.bbappend
- Apply the pending oe-core patch to fix the encodings import
- Adjust site.py to search both sys.lib and 'lib', to align with the behavior
of the python 2.7 multilib patch and fix the import of non-core modules
Closes #905
JIRA: INTAMDDET-1723
> python3: fix two multilib issues

- meta-mel/conf/distro/include/mel.conf
Upstream now lowercases the NATIVELSBSTRING, but not the entries in
SANITY_TESTED_DISTROS, so do so ourselves to avoid untested warnings.
> mel: lowercase the SANITY_TESTED_DISTROS

- meta-mel/conf/distro/include/mel.conf
Now that it's written for all BSPs, the inherit can be moved here rather than
in the machine.conf.
Depends on https://github.com/MentorEmbedded/mel-meta-mentor-private/pull/83
> mel: inherit cb-mbs-options by default

- meta-mel-support/recipes-core/meta/archive-release.bb
* runqemu.in was added to SRC_URI using append and space was not added
at the beginning. So the URL got corrupted and it did not pick runqemu.in.
This resulted it failure when do_prepare_release accessed runqemu.in in
sed command. Got following error
sed: can't read /var/jenkins/workspace/mel/qemux86-64/build_qemux86-64/tmp
/work/qemux86_64-mel-linux/archive-release/1.0-r0/runqemu.in: No such file
or directory
Added a space while adding runqemu.in to correct SRC_URI so that it get picked.
> archive-release: Add space while appending runqemu.in in SRC_URI.

- meta-mel/conf/distro/include/mel.conf
After WKS_FULL_PATH is set to the generated path, but before it's been
written, the os.path.exists() will fail, resulting in a different checksum
during that period, so operate based on WKS_FULL_PATH being set instead.
JIRA: SB-8410
> mel: fix taskhash mismatch for wic templates

- meta-mel/lib/recipetool/kernel.py
Without this, we'd see failures like:
Traceback (most recent call last):
File ".../poky/scripts/recipetool", line 120, in <module>
ret = main()
File ".../poky/scripts/recipetool", line 109, in main
ret = args.func(args)
File ".../meta-mentor/meta-mel/lib/recipetool/kernel.py", line 12, in kernel_add_fragments
rd = _parse_recipe(args.recipe, tinfoil)
File ".../meta-mentor/meta-mel/lib/recipetool/kernel.py", line 75 in _parse_recipe
tinfoil.config_data)
File ".../poky/meta/lib/oe/recipeutils.py", line 59, in parse_recpe
parser = bb.cache.NoCache(cooker.databuilder)
AttributeError: 'str' object has no attribute 'databuilder'
JIRA: SB-8415
> recipetool.kernel: align with newappend / oe.recipeutils

- meta-mel/lib/recipetool/kernel.py
This was fallout from python3, I believe.
Traceback (most recent call last):
File ".../poky/scripts/recipetool", line 120, in <module>
ret = main()
File ".../poky/scripts/recipetool", line 109, in main
ret = args.func(args)
File ".../meta-mentor/meta-mel/lib/recipetool/kernel.py", line 173, in kernel_set_configs
args.name = get_next_fragment_name(src_uri)
File ".../meta-mentor/meta-mel/lib/recipetool/kernel.py", line 160, in get_next_fragment_name
num = fragnums[0] + 1
IndexError: list index out of range
> recipetool.kernel: fix kernel_set_configs

- scripts/setup-rh
- scripts/setup-ubuntu
CodeBench toolchains are 64-bit now, so we no longer need this.
JIRA: SB-8429
> setup-{rh,ubuntu}: drop 32-bit libs

- scripts/toaster_configuration
Fix DL_DIR path and remove EXTERNAL_TOOLCHAIN path from toaster
configuration
> toaster_configuration: Fix DL_DIR path and remove EXTERNAL_TOOLCHAIN

- meta-mentor-staging/recipes-connectivity/connman/connman_%.bbappend
- meta-mentor-staging/recipes-support/rng-tools/rng-tools_%.bbappend
JIRA-ID: SB-8351
during initialization of connman sufficient entropy is needed, rng-tools
provide entropy, boot hang issue occured during early init of connman and
late init of rng-tools. so to fix the boot hang issue early init rng-tools
and do late init of connman.
previous init sequence:
etc/rc5.d/S05connman -> ../init.d/connman
etc/rc5.d/S30rng-tools -> ../init.d/rng-tools
updated init sequence:
/etc/rc5.d/S03rng-tools -> ../init.d/rng-tools
/etc/rc5.d/S95connman -> ../init.d/connman
> connman:rng-tools: fix sysvinit boot hang issue

- meta-mel/recipes-core/meta/meta-environment.bbappend
This was breaking do_generate_contents, due to the lack of forced expansion of
SDK_MULTILIB_VARIANTS for its default.
JIRA: SB-8469
> meta-environment: fix MULTILIB_VARIANTS recursion

- meta-mentor-staging/recipes-multimedia/alsa/alsa-utils/0001-alsa-utils-interrupt-streaming-via-signal.patch
- meta-mentor-staging/recipes-multimedia/alsa/alsa-utils_1.1.2.bbappend
JIRA: SB-8412
aplay/arecord (alsa-utils v1.1.2) cannot interrupt streaming
via CTRL-C. Fixed the issue by properly handling 'in_aborting'
flag in appropriate functions.
Upstream-Status: Pending
Signed-off-by: Anant Agrawal <Anant_Agrawal@mentor.com>
Signed-off-by: Mikhail Durnev <mikhail_durnev@mentor.com>
> alsa-utils: interrupt streaming via signal

- meta-mentor-staging/classes/bbpath-intercepts.bbclass
This was intended to dump the intercepts being used to the do_rootfs log, but
ended up printing a repr() of a generator, which was useless.
> bbpath-intercepts: fix broken debug output

- meta-mentor-staging/recipes-core/libxml/libxml2/CVE-2016-5131.patch
- meta-mentor-staging/recipes-core/libxml/libxml2_2.9.4.bbappend
Affects libxml2 <= 2.9.4
JIRA: SB-7870, SB-8431
CVE: CVE-2016-5131
Upstream-Status: Accepted [https://git.gnome.org/browse/libxml2/commit/?id=d8083bf77955b7879c1290f0c0a24ab8cc70f7fb]
> libxml2: Security fix for CVE-2016-5131

- meta-mentor-staging/recipes-core/udev/udev-extraconf/mount_modified.sh
- meta-mentor-staging/recipes-core/udev/udev-extraconf_%.bbappend
Use the modified udev mount.sh script file so that USB mass storage
device is mounted according to Label ID instead of device ID.
JiraID: SB-8404
Signed-off-by: Yasir-Khan <yasir_khan@mentor.com>
Signed-off-by: Sujith H <Sujith_Haridasan@mentor.com>
> udev-extraconf: use Label ID for mounting USB mass storage

- scripts/toaster-layers-recipes-config.py
Instead of passing layer_and_recipes to iterator, it's
better to convert it into list and pass the keys explicitely.
This fixes the issue caused:
Creating toaster configuration
Traceback (most recent call last):
File "/home/qatools/akif/mpsoc_tc3/mel/2017.02.67/meta-mentor/scripts/toaster-layers-recipes-config.py", line 43, in <module>
for layername in layer_and_recipes:
RuntimeError: OrderedDict mutated during iteration
JIRA: SB-8480
> toaster-layers-recipes-config: Fix issue for Ubuntu 16.04

- scripts/toaster-layers-recipes-config.py
Removing the extra list created del_layers. Instead in the loop,
removing the elements.
> toaster-layers-recipes-config: Fix the iteration mess done

- scripts/toaster_configuration
There is a potential bug in the virtualenv residing in
RHEL 7.3 version. The bug is listed here:
https://github.com/pypa/virtualenv/issues/463
So inorder to overcome this issue, a work around created.
JIRA: SB-8485
> toaster_configuration: Fix for RHEL7 using virtualenv

- meta-mel/conf/distro/include/mel.conf
JIRA: SB-8437
fix for RHEL distro not sanity tested warning.
WARNING: Host distribution "RedHatEnterpriseWorkstation-7.3" has not been
validated with this version of the build system; you may possibly
experience unexpected failures. It is recommended that you use a tested
distribution.
> mel.conf: add RHEL to sanity tested distro

- scripts/toaster_configuration
Remove MGLS_LICENSE_FILE from toaster UI. This variable needs to
be exported in the shell to use it.
JIRA: SB-8481
> toaster_configuration: Remove MGLS_LICENSE_FILE from toaster UI

- meta-mentor-staging/openembedded-layer/recipes-multimedia/mplayer/mpv_0.15.0.bbappend
Add PACKAGECONFIGs for drm and gbm video output features.
JIRA: SB-8551
> mpv: fix build-deps warnings for mesa and libdrm

- meta-mentor-staging/recipes-core/meta/nativesdk-sdk-relocate.bb
The native_sysroot path of sdk-relocate script was not updated
and hence we need to fix it appropriately.
JIRA: SB-8537
> nativesdk-sdk-relocate: Fix native_sysroot path of sdk-relocate

- meta-mel/conf/distro/include/mel.conf
Additional dependencies for deployed files are often pulled in via
do_image_wic[depends], to ensure the files are available for IMAGE_BOOT_FILES,
but this bypasses the do_image[recrdeptask] on do_populate_lic. Add it for
do_image_wic as well.
Ideally, EXTRA_IMAGEDEPENDS and IMAGE_DEPENDS_wic would also pull in
do_deploy, not just do_populate_sysroot, so we could avoid explicitly having
to list these things in `do_image_wic[depends]`.
JIRA: SB-8574
> mel: pull in do_populate_lic for do_image_wic deps

- meta-mel/recipes-core/psplash/psplash_git.bbappend
Yocto compliance requires BSP layers to only affect builds for their machines,
so all changes need to be conditional.
> psplash: add missing overrides

- meta-mel-support/conf/layer.conf
Given DEFAULT_PREFERENCE is lower priority than layer priority, we need some
way to default the preferences for the alternatives bits added in this layer,
so set weak defaults in the layer.conf.
This makes it possible to include the layer when DISTRO isn't mel without risking breakage of the build due to the unspecified preferences.
> mel-support: set default preferences for alternatives

- meta-mel-support/recipes-bsp/96boards-tools/96boards-tools/resize-helper.sh.in
- meta-mel-support/recipes-bsp/96boards-tools/96boards-tools_0.7.bb
fix for sd card resize issue with sysvinit as init manager.
JIRA: SB-8570
> 96boards-tools: add sysvinit support resize-helper.sh

- scripts/toaster-layers-recipes-config.py
- scripts/toaster_configuration
The current mechanism relies on folder names for
identification of a particular layer. This is not
suitable as folder names can be same over different
layers and tends to pollute the toaster setup as
it gets conflicting entries.
We change the behavior to make use of the real layer
name (BBFILE_COLLECTIONS) from each layer's layer.conf
which are bound to be unique for a correct bitbake
environment setup.
JIRA Ticket: SB-8582
> toaster: use layer names from layer.conf

- meta-mel/conf/distro/include/mel.conf
Plenty of machines are now adding wic to IMAGE_FSTYPES themselves. We don't
want or need to duplicate that, and IMAGE_FSTYPES is generally in the
machine's control anyway, so let them do it. Keep wic.bmap, as that's more of
a distro choice, and doesn't result in duplication.
JIRA: SB-8529
> mel: only add wic.bmap, not wic.bz2

- meta-mel/conf/include/wic-common.inc
Move dosfstools and mtools deps to bsp specific local.conf.append files
in meta-mentor-bsp. These tools are only common in systems that use dos
boot partitions so its better to set these on per BSP basis.
wic.bz2 is not needed in IMAGE_FSTYPES anymore as we are using wic now.
> wic-common.inc: move bits to meta-mentor-bsp

- meta-mel-support/recipes-core/meta/archive-release.bb
We're using image fstypes data, inherit the class in case variables from it
are needed for IMAGE_FSTYPES. In the case of current mel, wic.bmap is added to
IMAGE_FSTYPES based upon WKS_FULL_PATH, which is defined in image_types.
JIRA: SB-8529
> archive-release: inherit image_types.bbclass

- meta-mel/classes/resize-rootfs-gplv3.bbclass
- meta-mel/conf/distro/include/mel.conf
Rootfs resizing relies on a script which needs recent parted, which is GPLv3,
so we can't build in non-GPLv3 without disabling it or reworking the script.
JIRA: SB-8334
> Warn and disable rootfs resizing for non-GPLv3 builds

- meta-mel-support/recipes-support/bmap-tools/bmap-tools_2.5.bb
- meta-mel/conf/distro/include/mel.conf
We are downgrading bmap-tools recipe from the version
available at poky, which is 3.2. The reason is it generates
wic.bmap file with version 2 which is not supported in Ubuntu
14.04. So if we keep version 2.5 then it works on Ubuntu 14.04
and 16.04.
JIRA: SB-8621
> bmap-tools: Downgrade bmap-tools recipe to version 2.5

- meta-mentor-staging/fsl-ppc/recipes-dpaa/usdpaa/files/0001-usdpaa-do-not-hardcode-flags-for-powerpc64.patch
- meta-mentor-staging/fsl-ppc/recipes-dpaa/usdpaa/usdpaa_git.bbappend
instead of hardcoding flags. Similar change was made for powerpc 32 bit
targets in meta-fsl-ppc commit id 520c753.
JIRA: SB-8643
> usdpaa: Use TARGET_CC_ARCH for powerpc64

- meta-mel-support/recipes-support/bmap-tools/bmap-tools/Fiemap-synchronize-the-file-before-invoking-the-ioct.patch
- meta-mel-support/recipes-support/bmap-tools/bmap-tools_2.5.bb
This was causing .bmap files to be written with zero blocks in the map in some
cases, which caused failures for `bmaptool copy`. We encountered this when
building on Ubuntu 14.04 LTS hosts while using bmap-tools version 2.5. The
patch is cherry-picked from the bmap-tools 3.0 branch.
JIRA: SB-8678
> bmap-tools: apply workaround for FIEMAP issue

- meta-mentor-staging/recipes-support/ca-certificates/ca-certificates_20160104.bbappend
update-ca-certificates creates symlinks in $D/etc/ssl/certs for the content in
$D/usr/share/ca-certificates, but somehow those links end up with wrong
ownership, and pseudo.log indicates it got confused -- there are symlink and
inode mismatches for all the files. Yet nothing special is happening here,
it's a shell script run by a postinst at do_rootfs time, under pseudo. Work
around the issue with a chown for now.
JIRA: SB-8525
> ca-certificates: work around pseudo bug

- meta-mel/conf/distro/include/mel.conf
- meta-mel/conf/distro/include/wic-bmap.inc
If a wic image type is enabled, also enable wic.bmap. We use an event handler,
as we can't reference IMAGE_FSTYPES from inline python in the same variable,
and while we can reference WKS_FULL_PATH, then the value in the config
metadata would be different than in image recipes. This wouldn't normally be
a problem, but toaster is using the config metadata value.
JIRA: SB-8685
> Use an event handler to add wic.bmap to IMAGE_FSTYPES

- meta-mentor-staging/recipes-connectivity/openssh/openssh/sandbox-x32-workaround.patch
- meta-mentor-staging/recipes-connectivity/openssh/openssh_7.3p1.bbappend
This patch is from debian, see https://bugs.debian.org/849923.
On Linux x32, the clock_gettime VDSO currently falls back to the x86-64
syscall, so allow that as well as its x32 sibling.
Without this, ssh connections are immediately terminated when attempting to
use privsep sandbox (which is the default) on x32.
JIRA: SB-8593
> openssh: work around clock_gettime kernel bug on Linux x32

- meta-mel/classes/resize-rootfs-gplv3.bbclass
JIRA: http://jira.alm.mentorg.com:8080/browse/SB-8734
The Minnowmax BSP uses -sd.wks.in file name, while other BSP's
use ${MACHINE}.wks as file name in general. So expand the file
check condition to include ".wks" file name as well.
> resize-rootfs-gplv3: Warn for all WKS files

- meta-mel/conf/distro/mel-lite.conf
We only test MEL Lite on latest Ubuntu build hosts.
> mel-lite.conf: adjust SANITY_TESTED_DISTROS

- meta-mentor-staging/recipes-kernel/lttng/lttng-modules/nmi-safe_clock_on_32-bit_systems.patch
- meta-mentor-staging/recipes-kernel/lttng/lttng-modules/show_warning_for_broken_clock_workaround.patch
- meta-mentor-staging/recipes-kernel/lttng/lttng-modules/work-around_upstream_Linux_timekeeping_bug.patch
- meta-mentor-staging/recipes-kernel/lttng/lttng-modules_git.bbappend
Import following patches from upstream to fix incorrect timestamps seen
in lttng traces:
* 1d2aa29 Fix: work-around upstream Linux timekeeping bug
* 5b06448 Fix: show warning for broken clock work-around
* 1620024 Fix: nmi-safe clock on 32-bit systems
JIRA: SB-8881
> lttng-modules: import patches to fix clock issues

- scripts/setup-mel-builddir
- setup-environment
meta-mentor-private only includes stuff related to ADE and
PDK license verification both of which are not supported
on MEL Lite so various issues are seen.
We now disable inclusion of meta-mentor-private in bblayers
rather than adjusting each feature according to DISTRO so
it can be maintained much cleanly.
> setup-environment/-mel-builddir: exclude mentor-private on mel-lite

- meta-mentor-staging/recipes-kernel/lttng/lttng-modules/0001-Fix-preemptible-and-migratable-context-error-handlin.patch
- meta-mentor-staging/recipes-kernel/lttng/lttng-modules_git.bbappend
Backport the following upstream commit to fix  preemptible and migratable
context error handling;
https://github.com/lttng/lttng-modules/commit/d0e59d6f099f4663cc62bffb59d960cd4235064f
Jira: jira.alm.mentorg.com:8080/browse/SB-8925
> lttng-modules: Pull in upstream commit to fix error handling

- meta-mel/conf/distro/include/mel.conf
do_image_complete requires the licenses, so we need to make sure that
the do_image_complete task of the image recipe starts after
do_populate_lic is executed for all the packages to be included in
that image.
http://jira.alm.mentorg.com:8080/browse/SB-8951
> mel: add recursive dependency of do_image_complete on do_populate_lic

- scripts/setup-rh
- scripts/setup-ubuntu
CB Lite is a 32 bit toolchain and we provide installers for
MEL Lite with the same so these are still needed.
This reverts commit 2e3857c5c75ee5606bfe5352d9863863a9e3a2f9.
JIRA Ticket: SB-8954.
> Revert "setup-{rh,ubuntu}: drop 32-bit libs"

- meta-mel-support/recipes-core/meta/archive-release.bb
This lets bitbake handle the task scheduling more intelligently, letting multiple parts of the archival run in parallel, and means we can both replace individual component tasks with python implementations, or easily add our own unique components for our distro. Also clean some legacy bits up a bit while we're here. This is needed to prep for future changes to mel.
> Break up archive-release into granular tasks

- scripts/setup-mel-builddir
Once we're in prompt_choice, we can no longer test stdin or stdout to see if
it's a tty, since stdin is used to feed the prompt choices, so test for it
outside the function and pass an argument to force non-interactive mode when
appropriate.
> setup-mel-builddir: fix tty handling for the prompt

- meta-mel-support/recipes-core/meta/archive-release.bb
Paths in this file can apparently be relative to OEROOT/COREBASE. Without this
fix, it can fail with stock oe-core setup scripts (which can still be useful for
debugging).
> archive-release: handle the 'shortcut' form of templateconf.cfg

- meta-mel/mel-support/recipes-core/meta/archive-release.bbappend
This ensures that do_archive_mel_layers won't fail miserably when dealing with
layers/bitbake which are either submodules or work trees created with
git-worktree.
> archive-release: handle submodules/worktrees

- meta-mel-support/recipes-core/meta/archive-release.bb
Without this, we can hit failures due to the cleandirs in unpack/patch
removing their parent directories.
> archive-release: run the tasks after do_patch

- meta-mel/classes/layerdirs.bbclass
- meta-mel/mel-support/recipes-core/meta/archive-release.bbappend
mel inherits it, so it's not an issue for us -- this is just a correctness fix.
> archive-release: handle layerdirs not being in INHERIT

- meta-mel/mel-support/recipes-core/meta/archive-release.bbappend
This was causing failures for regular builds.
> archive-release: fix non-submodule/worktree handling

- scripts/release/mel-checkout
- scripts/setup-mel-builddir
Unsetting it causes failures in some shells.
> Drop the unset of OPTIND

- scripts/release/setup-environment
- If we pass `-b .` after `$@`, then it won't be obeyed when a MACHINE is
explicitly specified, as getopts won't handle options after arguments
- Since we moved `-b .` to before `$@`, we need to ensure that any explicitly
passed `-b` isn't passed along to the underlying setup-environment script
> release/setup-environment: fix passing of -b to setup-env

- meta-mel/recipes-core/images/core-image-minimal-initramfs.bbappend
* Provided openssh package by adding ssh-server-openssh in IMAGE_FEATURS
> core-image-minimal-initramfs: Provide openssh to intiramfs.

- meta-mentor-staging/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
Upstream has bumped the 'openssl' recipe to 1.1.
> qtbase: pull in openssl10, not openssl

- meta-mel/recipes-core/initrdscripts/files/init-boot.sh
Following warnings are observed on booting
core-image-minimal-initramfs:
mkdir: can't create directory '/proc': File exists
mkdir: can't create directory '/sys': File exists
This commit fixes these warnings.
Jira ID: http://jira.alm.mentorg.com:8080/browse/SB-9640
> init-boot.sh: fix runtime warnings

- meta-mel/conf/distro/include/mel.conf
We need SOURCERY_BASE_VERSION to be expandable so the sdk can be built
properly, whether SOURCERY_VERSION is defined or not.
JIRA: SB-8875
> mel: add default for SOURCERY_VERSION

- meta-mentor-staging/recipes-bsp/96boards-tools/96boards-tools/0001-96boards-tools-resize-helper.service-fix-for-auto-re.patch
- meta-mentor-staging/recipes-bsp/96boards-tools/96boards-tools_%.bbappend
JIRA: SB-10112
Upstream-Status: pending
we need PART_ENTRY_NUMBER filled with correct values to fix the resizing
error: partition dosen't exist,
this job will be done by udevadm, so to get expected inputs from it require
systemd-udev-settle.service
This error is so far observed only on below set of sd cards:
i. 8 gb+ class 10 sd cards
ii. 8 gb+ micro sd cards with sd card holder
> 96boards-tools: resize-helper.service: fix for auto-resizing sd card

- meta-mel/conf/distro/include/mel.conf
- scripts/git-make-shallow
This is failing in some cases, and I'm not 100% confident it's even doing its
job properly, and in the failing case, the repo still ends up shallow, so drop
it for now and revisit a better check for the future.
> git-make-shallow: remove the questionable sanity check

- scripts/setup-mel-builddir
This improves readability, by using ${TOPDIR} rather than a full absolute path
for layers relative to TOPDIR. It should ideally also adjust paths relative to
COREBASE/OEROOT/MELDIR, but that's less of a concern given the new mel
installer setup, and adding more generic determination of relative paths would
add more complexity to the scripts.
> setup-mel-builddir: use ${TOPDIR} in BBLAYERS

- meta-mel-support/recipes-core/meta/archive-release.bb
* There was a scenario where first archive-release was excuted with
meta-virtualization. First execution ran fine. The build was
reconfigured and meta-virtualization was removed from setup-environment
command. This was done to pull non GPLv3 sources and meta-virtualization
does not have non GPLv3 recipes. When archiev-release was executed
prepare_release exited with code 128. After enabling a log it was found
that virtualization-layer was present in downloads it was not there in
layermap.txt as it was remove from build configuration. Following log
was received.
| + touch downloads/virtualization-layer/gitshallow_github.com.docker.
distribution.git_28602af-1_docker.1.13.tar.gz.done
| + read source
| + cd downloads/virtualization-layer
| + cd -
| ++ sed -n 's/^virtualization-layer|//p' …
> archive-release: Fix prepare_release exiting with code 128.

- meta-mentor-staging/openembedded-layer/recipes-connectivity/krb5/krb5_1.15.1.bbappend
* yacc utility is required to build some package
* added bison-native package which contain yacc utility
Signed-off-by: sajjad238 <sajjad_ahmed@mentor.com>
> krb5 dependency fix

- meta-mentor-staging/recipes-devtools/python/python3-jsonschema_%.bbappend
vcversioner is needed at build time, so we need to depend on the native recipe
to be able to import the module, not the target recipe.
JIRA: MEIF-855
> python3-jsonschema: dep on python3-vcversioner-native

- meta-mel/classes/deploy-license-manifest.bbclass
The upstream commit
http://cgit.openembedded.org/openembedded-core/commit?id=6d969bacc718e21a5246d4da9bf9639dcae29b02
changed the image deployment directory from DEPLOY_IMAGE_DIR
to IMGDEPLOYDIR so we need to conform to the change for
license manifest deployment in order to cope with issues
such as a non-existent deployment dir when license deployment
is done.
> deploy-license-manifest.bbclass: use IMGDEPLOYDIR

- meta-mentor-staging/recipes-connectivity/dhcp/dhcp/0001-dhcp-correct-the-intention-for-xml2-lib-search.patch
- meta-mentor-staging/recipes-connectivity/dhcp/dhcp_4.3.4.bbappend
A missing case breaks the build when libxml2 is
required and found appropriately. The third argument
to the function AC_SEARCH_LIB is action-if-found which
was mistakenly been used for the case where the library
is not found and hence breaks the configure phase
where it shoud actually pass.
We now pass on silently when action-if-found is
executed.
Already accepted upstream: http://cgit.openembedded.org/openembedded-core/commit/?id=a17f3ec910366e9e7551fa24fbc07929b9584341
JIRA: SB-10251
> dhcp: fix build issue with libxml2 support

- meta-mel-support/recipes-core/meta/archive-release.bb
The bmap-tools project distributes a self-contained bmaptool binary which
includes the entirety of the bmap-tools python package, so we can download and
distribute that, or download and distribute a wrapper which does so, rather
than requiring the user install it or attempt to do so in the distro setup
scripts (i.e. setup-ubuntu).
This script is under the GPLv2, so redistribution shouldn't be a problem,
license wise.
JIRA: SB-10713
> archive-release: download and ship bmaptool

- scripts/setup-mel-builddir
- setup-environment
These vars are always set by setup-environment right now, so changing to
- resulted in not including layers we want to include by default. I intend to
shortly refactor setup-environment similar to how I recently refactored
setup-mel, we can fix this issue after that.
> setup-{environment,mel-builddir}: use :- not - until we rework the logic

- meta-mentor-staging/recipes-core/udev/udev-extraconf/mount_modified.sh
The automounter udev script attempts to mount the block devices under
/run/media/partition-label. If two devices have same partition-label,
they will be mounted on the same location.
This causes two types of known issues:
1. MEL installation fails if a MEL image is already installed on a
media other than where attempted to install such as HDD/eMMC/SSD/USB
that is attached during installation.
2. Unmount fails on a device if attempted using the device node
e.g. "/dev/sda1" with the 'umount' command.
These changes fix such issues.
Associated issues: INTAMDDET-2258, INTAMDDET-2259
Signed-off-by: Arsalan-Awan <Arsalan_Awan@mentor.com>
> Fixed overlapping mounts causing unmount and installation failures

- meta-mentor-staging/recipes-devtools/gcc/gcc_%.bbappend
This is no longer needed, as the external toolchain no longer sets
TARGET_PREFIX.
> gcc: drop TARGET_SYS workaround

- meta-mentor-staging/recipes-devtools/gcc/gcc_%.bbappend
The fix for preventing unused duplicate toolchain files for gcc, g++,
gcc-nm, gcc-ar and gcc-ranlib actually caused the x86 target toolchain
to be built so that it was able to produce 32-bit binaries only. This is
because the value passed to the tootlchain configuration option --target
ended being i686-pc-linux-gnu, inherited from the external toolchain.
Rather than trying to fix the values of TARGET_SYS and TARGET_PREFIX
from the mix of external toolchain and built toolchain, intead just
remove unused files from the rootfs. They are all of the name format:
${TARGET_SYS}-${TARGET_PREFIX}-<executable>
are the only files with that name format in the /usr/bin directory, and
are copies of existing files with the correct names from the same
directory.
Signed-off-by: Benjamin Walsh …
> gcc: fix target GCC being built for 32-bit x86 targets

- meta-mel-support/recipes-core/images/development-image.bb
- meta-mel-support/recipes-core/images/mel-image.inc
- meta-mel-support/recipes-core/images/production-image.bb
- meta-mel/classes/image-sanity-incompatible.bbclass
- meta-mel/conf/local.conf.append
Also adds and uses image-sanity-incompatible.bbclass, which may be
upstream-suitable, depending on interest.
Further improvements are likely, for example a default non-root user, prevent
root login at console, etc.
> Add initial production-image, development-image

- meta-mel/recipes-support/consolekit/consolekit/0001-Ensure-filesystems-are-still-mounted-when-consolekit.patch
- meta-mel/recipes-support/consolekit/consolekit_%.bbappend
/var/volatile could have disappeared, and that is where ConsoleKit logs
its start/stop/restart entries.
Signed-off-by: Benjamin Walsh <Benjamin_Walsh@mentor.com>
> ConsoleKit: ensure fs is still mounted when logging stop/restart

- scripts/release/manifest-remove-existing
Remove all entries from all manifests in MANIFEST_DIR which were
included in any manifests in EXISTING_MANIFEST_DIR.
JIRA: SB-11140
> manifest-remove-existing: add script for update release manifests

- meta-mel/conf/distro/include/mel.conf
MEL was always asking for a bind mount on ${ROOT_HOME} (/home/root by
default). The user-data feature enabled by swupdate is asking for a bind
mount on /home, but is also making sure that, if ${ROOT_HOME} is
/home/root, to not ask for a second bind mount on /home/root. However,
it does nothing to prevent a bind mount on both /home and /home/root.
What can happen is that /home/root gets a bind mount first, then /home
gets a bind mount. When this happens, the var-volatile* services handle
the mounting part correctly, copying data from the mounted directory to
the mount point as necessary, and the operation works as expected.
However, the umounting is broken in this case. The system thinks that
/home/root is still a mount point, while it is now a directory under the
/home mount point. When …
> volatile-binds: let user-data handle ROOT_HOME bind when enabled

- meta-mel/conf/distro/include/mel.conf
That trailing space was causing a failure if the entry ended up as the
last in the list, which happends when user-data is not in
COMBINED_FEATURES.
Also remove a confusing comment.
Signed-off-by: Benjamin Walsh <Benjamin_Walsh@mentor.com>
> mel.conf: fix list when root-home is last in list

- meta-mentor-staging/recipes-core/initrdscripts/files/0001-initrdscripts-init-live.sh-Fixed-mounts-fail-to-move.patch
- meta-mentor-staging/recipes-core/initrdscripts/initramfs-live-boot_1.0.bbappend
When there are spaces in the mount points of devices e.g.:
a partition mounted at "/run/media/My Root Partition-sda1",
the initrd fails to move such mount points over to the
corresponding directories at /media under the real root filesystem,
and the mount points would appear at the same location as they were
mounted on when detected by initrd, for example:
here: "/run/media/My Root Partition-sda1"
instead of here: "/media/My Root Partition-sda1"
This causes issues such as:
* The disks/partitions cannot be formated with any filesystem
using e.g. mkfs.ext4 or mke2fs in general. When tried to do so
by making sure the device is not mounted, it failed with
errors such as:
> /dev/sda1 is apparently in use by the system; will not make a
filesystem here!
> /dev/sda1: Device or resource busy while …
> initrdscripts/init-live.sh: Fixed mounts fail to move to real root fs

- meta-mel/conf/distro/include/mel.conf
Also add a fallback default for DISTRO_FEATURES_REMOVE to avoid referencing unset variables.
> mel: enable the wayland distro feature by default

- meta-mel/classes/remove-systemd-bind.bbclass
- meta-mel/conf/local.conf.append
- meta-mentor-staging/recipes-core/volatile-binds/volatile-binds.bbappend
systemd manages services by maintaining an elaborate tree under /etc/systemd.
When /etc/systemd is mounted as read-only, user cannot disable or enable services,
this caused error when opkg-configure tried to disable itself after first boot.
This fix mounts /etc/systemd in read-only mode allowing services to be disabled
or enabled at runtime.
Jira: http://jira.alm.mentorg.com:8080/browse/SB-11200
Signed-off-by: abdulkarim17 <hafizabdul_karim@mentor.com>
> volatile-binds: fix service disable in read-only file system

- meta-mentor-staging/classes/sdk_auto_relocate.bbclass
There was a mismatch between when the logic which disables if lib is
empty (packaging time) and when the variables that disable it are obeyed
(parse time). Ensure that they run at the same time to resolve this
mismatch and ensure the reloc is fully disabled appropriately in all
cases where it should be.
JIRA: SB-10686
> sdk_auto_relocate: run both aspects of enable/disable at the same time

- meta-mel/mel-support/recipes-core/meta/archive-release.bbappend
The hashes listed in the manifests for layers which are subdirectories and
which are shipped individually were changing on every build. This fixes that
issue.
JIRA: SB-11566
> archive-release: make git hashes deterministic for subdirs

- meta-mel/conf/distro/include/mel.conf
Gstreamer base plugin is added and ogg audio container (codec: vorbis) ogv video container (codec: theora) is tested successfully with the resulting image.
> SB-11567: Added gstreamer base plugin

- conf/local.conf.sample
As `_remove` cannot be undone given bitbake's current capabilities
(though I've discussed adding an API for this with Richard in the past,
so we may add it in the future), add a variable indirection
(`TOOLCHAIN_HOST_REMOVE`) to enable one to undo the
`TOOLCHAIN_HOST_TASK_remove`.
JIRA: SB-11062
> local.conf.sample: add var indirection for use of _remove

- meta-mel/classes/image-sanity-incompatible.bbclass
- meta-mel/conf/local.conf.append
- meta-mentor-staging/recipes-kernel/perf/perf.bbappend
The gplv2 binutils does not support aarch64, so the gplv3 version is built and
installed with tools-profile on that architecture by default, even in
a non-gplv3 build. This is kept in local.conf next to the bits which install
binutils with tools-profile by default, to keep it both user-visible and easy
to disable.
Also show a warning when whitelisted incompatible packages are installed in an
image, to ensure the user stays aware of it.
JIRA: SB-11714
> Allow gplv3 binutils for aarch64, for tools-profile

- meta-mel/mel-support/recipes-core/meta/archive-release.bbappend
This is a list of layers to exclude from archival and layer manifests,
by name, not path.
JIRA: SB-11813
> archive-release: support RELEASE_EXCLUDED_LAYERNAMES

- meta-mentor-staging/virtualization-layer/recipes-containers/docker/docker_git.bbappend
* While running following command on the target
docker pull ubuntu
this error pops up
Get https://registry-1.docker.io/v2/: x509: failed to load system roots and no roots provided
This is due to the reason that certificates are missing on the target.
docker recipe is not depending on ca-certificate. Add ca-certificates in
rdepends to resolve the issue.
> docker_git: Fix runtime issue for failed to load system roots issue.

- setup-environment
In the case of the new git delivery mechanism, TOPDIR==MELDIR, so we end
up with `${TOPDIR}` references in BBLAYERS, but `configured_layers` in
setup-environment wasn't converting that to a reference to BUILDDIR, and
hence failed to find any layers for handling layer.conf.append or
post-setup-environment, resulting in much configuration missing from
local.conf. This broke builds of just about all of our BSPs.
JIRA: SB-11836
> setup-environment: handle ${TOPDIR} in BBLAYERS

- conf/local.conf.sample
- meta-mel/conf/distro/include/mel.conf
The variable for accepting the eula has changed names, so we needed
to update our sample.
> local.conf.sample: fsl -> xilinx

- scripts/setup-rh
- setup-environment
epel-release's packages cause problems on some rhel/centos systems
depending on the particular versions of the dependencies which are
installed. We have multiple open bugs relating to this. Rework to use pyenv
to install python3.
JIRA: SB-11887
> setup-rh: rework to use pyenv for python3

- meta-mel/lib/bblayers/dl.py
Due to how we were splitting the string entries in bitbake's generated
depgraph, we ended up with a recipe name of 'glib-2' and a task name of
'0.do_fetch', which resulted in leaving out downloads for any recipe
with a period in its name. Fix the splitting.
JIRA: SB-11889
> bitbake-layers.dump-downloads: fix bug with recipe names with a period

- conf/local.conf.sample
* Now we build glibc from sources. No need to set anything in local.conf.
So remove old lines from local.conf.sample file.
> local.conf.sample: Remove the lines related to rebuilding glibc

- meta-mentor-staging/classes/xsctyaml.bbclass
This class is copied from xilinx-tools layer because
the following fix is required.
This change is requested to be merged in upstream.
See: https://lists.yoctoproject.org/pipermail/meta-xilinx/2018-August/004018.html
PYTHON_SITEPACKAGES_DIR is set to /usr/lib64/python3.5/site-packages
but python native is at /usr/lib/ not in /usr/lib64. Which causes
the following error:
ERROR: fsbl-2018.2+gitAUTOINC+6e82c0183b-r0 do_create_yaml: Error executing a python function in exec_python_func() autogenerated:
The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function:
0001:
*** 0002:do_create_yaml(d)
0003:
File: '/data/hkarim/elm-06/meta-xilinx-tools/classes/xsctyaml.bbclass', lineno: 64, function: do_create_yaml
0060: …
> xsctyaml.bbclass: Fix PYTHON_SITEPACKAGES_DIR

- meta-mel/conf/distro/include/mel.conf
* PDK_DISTRO_VERSION is used to checkout license. Faced the following error
ERROR: MEL PDK license check failed: error: (null)
cs-license failed, aborting
Reverted old value of PDK_DISTRO_VERSION. Set ARCHIVE_RELEASE_VERSION to
3 number scheme temprarily.
> mel.conf: Reverted PDK_DISTRO_VERSION changes due to license failuer.

- conf/local.conf.sample
Drop x11-mini from the features list as it is an old remnant
of cleanup. The feature is now known as x11-base but that is
explained in OE's sample files listed in the definition of
features here.
The graphics feature does not always default to wayland/weston
but rather that decision is taken looking at the MACHINE_FEATURES
which is what provided by the vendor support.
> local.conf.sample: drop x11-mini, clarify 'graphics' feature

- scripts/release/setup-mel
- scripts/release/setup-workspace
The setup-builddir script created a builddir itself if
one wasn't provided by the user and then it would call
setup-environment for it. This causes ambiguities where
a user would want to setup different builds using the
same workspace.
Now we drop the calls to setup-environment and do not
create a builddir from these scripts so the old mechanism
of calling setup-environment separately can be used as
earlier and avoid confusions. The setup-builddir script
is renamed to setup-workspace so the intent is clear.
> setup-mel/setup-builddir: only setup a workspace

- meta-mel/mel-support/recipes-core/meta/archive-release.bbappend
* setup-builddir script was rename in following commit
setup-mel/setup-builddir: only setup a workspace
Need to update in archive-release recipe as well so that correct script is bundled.
> mel-support:archive-release: Rename setup-builddir to archive-release

- scripts/release/mel-checkout
- scripts/release/setup-mel
- scripts/release/setup-workspace
The idea here is to tie a workspace to a particular BSP that is used to initially create the specific workspace. Although this is in contrast with how workspaces are usually used but our metadata that is checked out into a workspace is actually tied to a BSP already. If we don't follow this route (tying workspace to BSP) there can be a situation where a user might create build directories using this particular metadata and then runs setup-mel with a different machine/manifest on this workspace, in this scenario all the earlier created build directories would go out of sync and can cause known/unknown failures.
> [RFC] Tie workspace to machine/BSP

- meta-mel/conf/distro/include/mel.conf
The user may well want to have the option to use or install any or
multiple locales, and not generating fr-fr and de-de breaks the ability
to run the bash ptests.
JIRA: SB-11898
> mel: drop the pointless GLIBC_GENERATE_LOCALES override

- meta-mel/conf/distro/include/mel.conf
> mel.conf: Add ubuntu-18.04 to mel supported hosts.

- scripts/release/setup-workspace
Originally, this script was a wrapper script, so used non-standard
argument handling to allow it to pass unrecognized arguments through to
the underlying script directly. Since it was reworked to only set up the
workspace, this is no longer the case, so the old argument handling is
not appropriate. Rework to use getopts and properly show errors/usage on
incorrect arguments.
JIRA: SB-11943
> setup-workspace: rework argument handling

- scripts/release/mel-checkout
This allows `${MELDIR}/downloads` to be used either directly as DL_DIR
or as mirror, whereas the uninative tarballs were only found for the
former previously.
JIRA: SB-11940
> mel-checkout: link uninative downloads to toplevel

- meta-mel/conf/distro/mel-lite.conf
- meta-mel/sourcery/recipes-sourcery/glibc-sourcery/glibc-sourcery.bbappend
The CB Lite tools for current release are based off of
glibc 2.28 so make adjustments accordingly.
> MEL Lite use glibc 2.28

- meta-mentor-staging/scripts/relocate_sdk.sh
When we adjusted the environment setup script to use scriptdir to make
CodeBench happy, we inadvertently broke relocation, as relocate_sdk.sh
didn't handle it. Fix by evaluating the line we need.
JIRA: SB-12005
> relocate_sdk.sh: fix native_sysroot

- meta-mentor-staging/recipes-core/udev/udev-extraconf/systemd-udevd.service
- meta-mentor-staging/recipes-core/udev/udev-extraconf_%.bbappend
Automounting does not work cleanly in case systemd as well as
udev rules are being used simultaneously and in most cases
race conditions and unknown behavior can come up.
In case we're running on top of systemd we need to make sure
that systemd-udevd knows that udev is in play as well and
mounting should be done using shared flags. Also as we're
using mount from sources other than systemd-mount in our
current scripts this is the most manageable fix to automounting
problems.
JIRA: SB-12028.
> udev-extraconf: force systemd-udevd to use shared MountFlags

- conf/local.conf.sample
- meta-mentor-common/classes/image-root-password.bbclass
WIP, do not merge yet. I don't believe this is a good approach, defaulting to
an insecure random password for root in production-image is problematic. I'd
rather arrange for a warning to be emitted when production-image is built when
the user hasn't set ROOT_PASSWORD, indicating that they won't be able to login
as root by default.
> Add support for ROOT_PASSWORD, change behavior when empty for production-image

- meta-mentor-staging/conf/layer.conf
Shutting up warnings from layers that lacked the variable.
JIRA: SB-12065
> staging/layer.conf: add terrible layerseries compat hack

- conf/local.conf.sample
* In local.conf INITRAMFS_IMAGE and INITRAMFS_IMAGE_BUNDLE variables were being
set for encrypted-fs. For generating normal INITRAMFS the location of the vars
were mattering alot. If those were added after the lines where INITRAMFS_IMAGE
and INITRAMFS_IMAGE_BUNDLE were being set for encrypted-fs then it worked fine.
But we those were added earlier then encrypted-fs vars were overwriting it. So
commented out line which were added for encrypted-fs. Add core-image-minimal-initramfs
in those lines. Now in order to generate encrypted-fs or normal initramfs one
has to uncomment following lines
#INITRAMFS_IMAGE = "${@bb.utils.contains('EXTRA_IMAGE_FEATURES', 'encrypted-fs', 'dmcrypt-initramfs-image', 'core-image-minimal-initramfs', d)}"
#INITRAMFS_IMAGE_BUNDLE = "1"
* SB-12074
Signed-off-by: …
> local.conf.sample: Fix initramfs image file creation in deploy folder.

- meta-mentor-staging/recipes-devtools/python/python-native/0001-python-native-fix-one-do_populate_sysroot-warning.patch
- meta-mentor-staging/recipes-devtools/python/python-native_2.7.14.bbappend
Fix below warning:
WARNING: Skipping RPATH /usr/lib64 as is a standard search path for
work/x86_64-linux/python-native/2.7.15-r1.1/recipe-sysroot-native/
usr/lib/python2.7/lib-dynload/_bsddb.so
setup.py will check db.h under include_dirs, for native build,
/usr/lib64 will be insert to postion 0 of include_dirs, so
it's priority is higher then our sysroot, cause db.h sysroot
is ignored, and rpath set to /usr/lib64. and this cause warning
when do_populate_sysroot. use append to fix it.
Signed-off-by: Changqing Li <changqing.li@windriver.com>
> python-native: fix one do_populate_sysroot warning

- meta-mentor-staging/conf/layer.conf
Adding to the tradition set in 3c373331, fix QA warning
WARNING: Layer qt5-layer should set LAYERSERIES_COMPAT_qt5-layer in its conf/layer.conf file to list the core layer names it is compatible with.
> staging/layer.conf: hack around LAYERSERIES_COMPAT for qt5-layer

- meta-mel-support/recipes-core/images/mel-image.inc
If GPLv3 license is allowed to be used, haveged is added as an entropy
source so that if user does not use random input sources like keyboard
and mouse, MEL image still has a random number's source.
> mel-image.inc: Add haveged as entropy source.

- meta-mel/lib/bblayers/dl.py
- meta-mel/lib/bblayers/mel_utils.py
For OSS approvals we need to provide list of items that are
being built/distributed along with their version and license
information. This now adds a command 'dump-licenses' to
bitbake-layers to aid this requirement.
> bblayers/dl: add command for dumping license information

- meta-mel/conf/distro/include/mel.conf
- meta-mentor-staging/classes/cachefixes.bbclass
- meta-mentor-staging/postinst-intercepts/update_font_cache
- meta-mentor-staging/postinst-intercepts/update_gio_module_cache
- meta-mentor-staging/postinst-intercepts/update_pixbuf_cache
- meta-mentor-staging/postinst-intercepts/x86-64/update_font_cache
- meta-mentor-staging/recipes-devtools/qemu/qemuwrapper-cross_%.bbappend
- meta-mentor-staging/recipes-graphics/fontconfig/fontconfig_%.bbappend
This series applies a couple patches from oe-core which fixes the
update_font_cache failures seen on x86-64 and elsewhere relating to multilibs,
adjusted to work in meta-mentor-staging without overriding the classes in
question. We no longer see warnings for this postinst intercept with this
applied.
JIRA: SB-12123
> update_font_cache: fix warnings

- meta-mentor-staging/recipes-core/busybox/busybox/reboot.cfg
- meta-mentor-staging/recipes-core/busybox/busybox_1.27.%.bbappend
996247ba7dfffbeb444f793f7e105fcfb5ffa939 in upstream oe-core
moved the power flags (POWEROFF, HALT, REBOOT) to a fragment
init.cfg which is only included when busybox is selected as
the init_manager. This assumption is incorrect in scenarios
where installation mechanism is provided through live images
and almost all the initramfs scripts use the reboot command at
the end of installation. Without this change we see
reboot: not found
> busybox: enable reboot support

- meta-mel-support/recipes-kernel/firmware-wireless/firmware-wireless_git.bb
* Add ath10k from 'linux-firmware' to 'firmware-wireless' repo
* Update the source_rev
* SB-12145
> ath10k: Add ath10k support in firmware-wireless

- scripts/toaster_configuration
BBLAYERS is now set using a weak assignment rather than a
strict one. See 6ac988dcad81b6bfa38e15446618184258d23eba
in meta-mentor. Without this the BBLAYERS variable isn't
parsed and picked up correctly.
JIRA: SB-12165.
> toaster_configuration: conform to new mechanism of BBLAYERS

- meta-mel/conf/distro/include/mel.conf
- Removed ubuntu-14.04
- Also match centos-7, not just centos-7.*
- Also match rhel, not just redhatenterprise
> mel.conf: update supported distros for elm

- meta-mentor-staging/recipes-core/initrdscripts/files/0001-initramfs-framework-finish-move-mounts-to-rootfs-bef.patch
- meta-mentor-staging/recipes-core/initrdscripts/initramfs-framework_1.0.bbappend
Operations such as mkfs fail on devices that are not
switched to the actual rootfs before switch_root is
called. The kernel interprets these devices as still
being used even after unmounting and errors such as
below are seen when the target is fully booted
root@v1000:~# umount /dev/sdb1
root@v1000:~# mkfs.ext4 /dev/sdb1
mke2fs 1.43.8 (1-Jan-2018)
/dev/sdb1 contains a ext4 file system
last mounted on Wed Nov 28 07:33:54 2018
Proceed anyway? (y,N) y
/dev/sdb1 is apparently in use by the system; will not make a filesystem here!
> initramfs-framework: move storage mounts to actual rootfs

- meta-mel/conf/distro/include/mel.conf
* PDK_LICENSE_VERSION_DATE is updated to Dec 6th as final RC for elm release.
> mel.conf: Update PDK_LICENSE_VERSION_DATE to final RC date.

- meta-mel/mel-support/recipes-core/meta/archive-release.bbappend
This case now archives the git repo as a whole, but filters its contents to
only include the indiv layers in the repo, no other content.
> archive-release: don't individually archive non-topdir indiv layers in git repos

- scripts/release/setup-workspace
- scripts/setup-mel-builddir
- setup-environment
The workspace setup script needs to pass on information regarding mel-lite variant to the workspace itself so once the scripts from the workspace are executed they can detect the presence of the distro. Furthermore, the setup scripts inside the workspace are fixed to handle the mel-lite and codebench-lite cases.
> Fix mel-lite and codebench-lite handling in setup scripts

- meta-mel-support/recipes-core/images/mel-image.inc
util-linux was enabled recently:
5b0efbdc6710cef767334eedea55b99dfc798f15
which provides more than 15 sub-packages, most of which are already
provided by busybox which are being used by default in oe-core.
Since we only need mkfs, this commit enables only that instead of all 
the util-linux-* packages, which are not only redundant, but also may 
cause conflicts and errors such as following:
fdisk from util-linux, when run like e.g.:
$ fdisk /dev/sda
at its start causes the kernel to generate remove+change+add events for 
all the existing partitions of /dev/sda. This triggers the udev
automount.rules to start the mount.sh for all the partitions, hence
remounts all the existing partitions before we could create new ones.
Hence this disables util-linux-fdisk as well, still leaving us with …
> util-linux: disable redundant packages leaving only mkfs as required

- meta-mel/conf/distro/mel-lite.conf
We're only supporting Ubuntu 18.04 for the MEL Lite ELM
release.
JIRA: INTAMDDET-2611.
> mel-lite.conf: fix SANITY_TESTED_DISTROS for elm release

- meta-mel/conf/distro/include/mel.conf
This essentially reverts 56cb67a401135d7f9c70511053c2284435f5f4d7 as
the intent of KERNEL_IMAGETYPES has changed. i.e. adding vmlinux to
KERNEL_IMAGETYPES ends up in tmp/deploy/images/${MACHINE} but also
ends up in the rootfs of the image being built where it is not needed
for any MEL requirements, and as a side-effect, it results in
increasing the size of the image by a considerable amount:
root@snowyowl:~# du -h /boot/vmlinux-4.14.71-yocto-standard
598.5M  /boot/vmlinux-4.14.71-yocto-standard
This happens because oe-core/meta/classes/kernel.bbclass takes all
the KERNEL_IMAGETYPES and creates PACKAGES and sets the kernel-image
package to RDEPENDS on kernel-image-<KERNEL_IMAGETYPES> pkgs:
root@snowyowl:~# opkg info kernel-image-4.14.71-yocto-standard
Package: …
> mel.conf: remove vmlinux from KERNEL_IMAGETYPES to reduce image size

- scripts/setup-mel-builddir
This is a behavioral change that could be noticed by customers, but it's fairly unlikely that anyone is relying on the current behavior, as as noted by the opener of the issue, the existing behavior is a potential source of confusion, so let's go ahead and include it in the asyncs.
> setup-mel-builddir: make the -l argument cumulative

- meta-mel-support/recipes-core/meta/archive-release.bb
Absence of conf-notes.txt, causes installer based setup-environment
scripts to have incomplete logs.
JIRA Issue: http://jira.alm.mentorg.com:8080/browse/SB-12522
> archive-release: include conf-notes.txt

- conf/local.conf.sample
MACHINE_BOOT_FILES variable is used to add bsp specific images to
BOOT partition. This variable adds its contents to IMAGE_BOOT_FILES
at the end in case of ultrazed.
Instead of manually adding contents of MACHINE_BOOT_FILES into
IMAGE_BOOT_FILES, directly place desired image to IMAGE_BOOT_FILES.
Jira Issue: http://jira.alm.mentorg.com:8080/browse/SB-12576
> local.conf: replace MACHINE_BOOT_FILES variable

- meta-mentor-staging/recipes-core/glibc/glibc-locale_%.bbappend
Work around long standing periodic host-user-contaminated QA failure by
explicitly correcting the ownership.
See `glibc-locale: Rewrite do_install using install utility instead of cp`
on the oe-core mailing list for discussion. This should be dropped when
a real fix is implemented.
JIRA: SB-12560
> glibc-locale: work around host-user-contaminated QA failure

- scripts/release/mel-checkout
qemu is less likely to be the user's selection than their BSP, so prefer
the latter via the typical decorate-sort-undecorate.
JIRA: SB-12559
> mel-checkout: move qemu manifests to the end when prompting

- conf/local.conf.sample
IMAGE_BOOT_FILES is being assigned in machine file and being appended
in local.conf.
Bitbake parses local.conf earlier and parses machine file later.
Also, += operator appends the corresponding variable instantly during
the parse.
And _append operator appends the variable after parsing all the recipes
completely.
In case we place += operator in local.conf and same variable is being
assigned (using = operator) in other recipe, we will get our local.conf
append overwritten due to later assignment. This overwrite is simply
avoided by using _append instead of += operator.
Jira Issue: http://jira.alm.mentorg.com/browse/SB-12629
> local.conf: replace += with append_ operator

- conf/local.conf.sample
- meta-mel/files/debugging.cfg
- meta-mentor-common/classes/kernel-config-debugging.bbclass
Right now the following are added, which can be easily expanded if
needed:
* KGDBOC
* Kernel debugging and debug info
* CPU_IDLE and DEBUG_SET_MODULE_RONX have been unset
> kernel-config-debugging.bbclass: class to add kernel debugging kconfigs

- scripts/setup-ubuntu
The utility is used by the Host Security Tool's command line
variant.
> setup-ubuntu: install realpath

- scripts/setup-ubuntu
This reverts commit 0b063172d1b4036226f156c22580c64802904d4b.
The HST script requiring this dependency has been changed to work
without this.
https://stash.alm.mentorg.com/projects/CB/repos/cb_iot/pull-requests/40/overview
> Revert "setup-ubuntu: install realpath"

- meta-mentor-staging/virtualization-layer/recipes-containers/docker-compose/python3-docker-compose_1.16.1.bbappend
docker-compose needs a number of python3 runtime dependencies. The
packages python3-misc and python3-modules provide those dependencies.
The bbappend is being applied to current version of python3-docker-
compose so that it is reviewed later on as well if these dependencies
are fixed by upstream in the later versions or not.
> python3-docker-compose: add missing dependencies

- scripts/release/mel-checkout
Just like codebench, we're now introducing a tools directory
which will contain different tools. So force a link creation
inside workspace such that it can be utilized from inside.
Ref: http://confluence.alm.mentorg.com:8090/display/MEIF/MEIF+Host+Tool+Restructuring
> mel-checkout: create link for tools dir if available

- conf/local.conf.sample
- meta-mel/conf/distro/include/mel.conf
- meta-mentor-common/classes/kernel-config-encryptfs.bbclass
**encryptfs.bbclass: conditionally add fragment** 
kernel-config-encryptfs.bbclass adds kerenl configs required by
encrypted file system support. And this class is inherited in
kernel recipe class. This class adds the kernel configs in all
cases, even if encrypted-fs is not enabled as a feature.
This commit adds this kernel fragment to SRC_URI only if the
encrypted-fs is enabled in the USER_FEATURE variable.
Otherwise doesn't add it.
**local.conf: set encrypted-fs as a user feature**
encrypted-fs was previously being used as an EXTRA_IMAGE_FEATURE.
But machine related kernel configurations cannot be made on the
basis of an image feature. Since in most of the imx bsps, we
encountered hardware crypto failure, kernel configurations needed
to be set on the basis of encrypted-fs. And that's …
> Encrypted-fs support updates.

- meta-mentor-staging/recipes-core/glibc/glibc-locale_%.bbappend
Explicitly disable host-user-contaminated to further work around the
pseudo bug. With pseudo acting up, even if the ownership is correct, it
may well think it is not, so just sidestep the issue until upstream
fixes the root cause.
JIRA: SB-13459
> glibc-locale: explicitly disable host-user-contaminated

- meta-mel-support/conf/layer.conf
- meta-mentor-staging/conf/layer.conf
We aren't currently providing any additional common license files, so
don't need to adjust this. Adding paths without having the licenses
directory is now fatal.
> layer.conf: drop LICENSE_PATH

- meta-mel/conf/distro/include/mel.conf
mel.conf: include mel-security-selinux.conf
* remove selinux and smack common config file mel-security.conf and add selinux config file mel-security-selinux.conf
related PR in mel-meta-mentor-security: https://github.com/MentorEmbedded/mel-meta-mentor-security/pull/100
Signed-off-by: Haseeb Ashraf <Haseeb_Ashraf@mentor.com>
> mel.conf: include mel-security-selinux.conf

- meta-mel/conf/distro/include/mel.conf
* ENABLE_EGLFS is no longer available
* Move vulkan back to default distro features
> mel.conf: Remove ENABLE_EGLFS flag

- meta-mel-support/recipes-core/images/mel-image.inc
An append requires a space and otherwise would mess up
the whole variable.
> mel-image.inc: fix IMAGE_FEATURES append

- meta-mel/conf/distro/include/mel.conf
this entry is being added through volatile-binds
recipe in mentor-bsp layer
Jira: https://jira.alm.mentorg.com/browse/SB-14619
> mel.conf: remove root-home volatile bind

- meta-mentor-staging/multimedia-layer/recipes-multimedia/fluidsynth/fluidsynth_1.1.10.bbappend
there is an additional '-' slipped into when checking pulseaudio
typo: --Denable-pulseaudio=OFF
fix: -Denable-pulseaudio=OFF
JIRA-ID: SB-15256
> fluidsynth: fix typo in PACKAGECONFIG[pulseaudio]

- meta-mel/recipes-core/images/mel-initramfs-image.bb
This was intended to only be run for non-initramfs images, but
mel-swupdate.conf adjusts IMAGE_FSTYPES in a way that results in the
default removal no longer applying, so do so explicitly here.
> mel-initramfs-image: disable zapped root password qa check

- meta-mentor-staging/openembedded-layer/recipes-extended/haveged/haveged/0001-fix-ordering-cycle-with-private-tmp.patch
- meta-mentor-staging/openembedded-layer/recipes-extended/haveged/haveged_1.9.9.bbappend
The haveged systemd service file creates a dependency chain in a
way that at times breaks journald services and hence we don't get
anything from the journal logs after boot.
The backport copes with this issue by fixing the service file. This
is a backport of
https://github.com/jirka-h/haveged/commit/2098470a38e16173c23d176fe87c64754c2000e5
> staging: haveged: backport patch for systemd dependency issues

- meta-mel/conf/distro/include/mel.conf
Remove Vulkan from the default MEL default distro feature list.
This change also helps to compile qt5 packages.
> Remove vulkan from mel default distro features list

- meta-mel/recipes-core/images/mel-initramfs-image.bb
selinux context labeling is only required for rootfs, "selinux_set_labels" call can be removed from IMAGE_PREPROCESSOR_COMMAND from the mel-initramfs-image recipe.
JIRA: https://jira.alm.mentorg.com/browse/SB-14198
Signed-off-by: sajjad238 <sajjad_ahmed@mentor.com>
> mel-initramfs-image: remove selinux labelling for initramfs

- meta-mel/lib/bblayers/mel_utils.py
This was incorrectly passing an additional argument to get_variable_items_files
which could not be send across the connection to the server, resulting in a pickle
failure traceback.
JIRA: SB-15436
> bblayers.mel_utils: fix dump-downloads

- meta-mel/recipes-core/packagegroups/packagegroup-core-tools-profile.bbappend
* MEL FLEX does not need systemtap. It brings boost which takes
lots of resources while building. So Remove systemtap from build.
> packagegroup-core-tools-profile: Remove systemtap.

- meta-mel/conf/distro/include/mel.conf
This is already inherited where it's used.
> mel: remove unnecessary INHERIT of cb-mbs-options

- meta-mel/recipes-core/images/mel-initramfs-image.bb
Adds initramfs-module-udev to the PACKAGE_INSTALL for the start/stop udev
daemon script in the initramfs
Signed-off-by: ekalemen <eugeny_kalemenev@mentor.com>
> mel-initramfs-image: add initramfs-module-udev to packages

- conf/local.conf.sample
* 9b616 was added for SB-11691. Now SA rework their script.
See SA-4899 and SA-4905. Now binutils package is not
needed. So reversing the commit.
> local.conf.sample: Reversing commit 9b616.

- meta-mentor-staging/security/recipes-ids/tripwire/tripwire_%.bbappend
The twcfg.txt contains a number of spaces before the '=' sign
for each entry hence our current sed expression fails to update
the EDITOR entry as it intends to.
Fix the expression to check for any number of spaces before the
'=' sign for the entry.
> tripwire: fix sed for changing EDITOR

- meta-mentor-staging/fsl-bsp-release/recipes-bsp/imx-vpu/imx-vpu_%.bbappend
Multimedia+graphics+qt5-mel builds fail with an external toolchain due to this recipe always installing to '/usr/lib'.
> imx-vpu: correct install paths

- meta-mentor-staging/security/recipes-ids/tripwire/tripwire_%.bbappend
The main recipe deploys the installation script to /etc which
isn't meant for executables and doesn't work well when a read-only
or no-exec strategy is in place for /etc which can be the case
in many systems. This renders the installation script invalid
to be used with such strategy.
We now deploy the script to bindir which is always an executable
location by any specification so it can be executed.
> tripwire: deploy installation script to an appropriate location

- meta-mentor-staging/security/recipes-security/scapy/python3-scapy_%.bbappend
This fixes a runtime issue where scapy complains
ModuleNotFoundError: No module named 'fcntl'
> python3-scapy: add a required runtime dependency on fcntl

- meta-mel/mel-support/recipes-core/meta/archive-release.bbappend
* Flex installer were missing setup-debian script. Add it in
MEL_SCRIPTS_FILES so that it can be bundled with installer.
* SB-15578
> archive-release: Add setup-debian script to MEL_SCRIPTS_FILES.

- meta-mel/conf/distro/include/mel.conf
* Remove ubuntu 16 and rhel 7. Add ubuntu 20, debina 10, rhel 8
and redhatenterprise 8.
* SB-15559
> mel.conf: Update supported host list for Fir release.

- meta-mel-support/recipes-core/meta/archive-release.bb
- meta-mel-support/recipes-core/meta/archive-release/runqemu.in
- meta-mel/conf/distro/include/mel.conf
JIRA: SB-15569
This avoids shipping tar.bz2 where we can, prefers ext4 to ext3, fixes runqemu so it works at all (doesn't really belong in this pull request, but it's related), avoids shipping buildhistory, and moves to an explicit list of files to include from DEPLOY_DIR_IMAGE, and if a wic image type is enabled, those are the only types we ship.
> Sanitize included image types for installation

- meta-mel/recipes-support/boost/boost_%.bbappend
* boost takes lots of system resources. Somethimes it give memory error.
Setting PARALLEL_MAKE to 4 so that it does not cosume all of the
system resources.
> boost: Set PARALLEL_MAKE to -j 4.

- meta-mel/classes/codename_is_corename.bbclass
- meta-mel/conf/distro/include/mel.conf
This class implements a sanity check which only makes sense when this DISTRO always defines its DISTRO_CODENAME to match up with the Yocto release codename. If DISTRO_CODENAME is not listed in LAYERSERIES_CORENAMES, we abort.
Example output:
```
This version of mel is incompatible with this version of openembedded-core (code name gatesgarth). Please use matching layer branches or update Mentor Embedded Linux Flex OS.
```
JIRA: SB-15572
> Add and use codename_is_corename.bbclass

- scripts/release/mel-checkout
- scripts/release/setup-workspace
- scripts/setup-mel-builddir
- setup-environment
We're moving to a 'toolchains' link and TOOLCHAINS_PATH rather
than 'codebench' and CODEBENCH_PATH.
JIRA: SB-15621
> Move from CODEBENCH_PATH to TOOLCHAINS_PATH

- meta-mentor-staging/recipes-core/systemd/systemd-boot/0001-Use-an-array-for-efi-ld-to-allow-for-ld-arguments.patch
- meta-mentor-staging/recipes-core/systemd/systemd-boot_%.bbappend
The previous method to implement this in the recipe passed only the first LD argument as efi-ld, then added the remainder of the TUNE_LDARGS to LDFLAGS, but this breaks builds, as TUNE_LDARGS is to be passed to *ld*, not *gcc*, but LDFLAGS are flags used when linking with gcc. Fix this by using an array for efi-ld as is done for efi-cc.
JIRA: SB-15603
> systemd-boot: use an array for efi-ld to allow ld args

- scripts/setup-debian
- scripts/setup-rh
- scripts/setup-ubuntu
This is used by the `make headers` target in the kernel builds for linux-libc-headers. For non-imx, we use the external recipe and don't call this target, but on imx we build linux-imx-headers and can run into a build failure on hosts lacking rsync.
JIRA: SB-15635
>  setup-*: add rsync

- scripts/setup-rh
* On RHEL 8 rpcgen was needed on the host for few imx BSPs. Added in
setup script so that it can be installed on host.
* SB-15706
> setup-rh: Fix MEL build issue on RHEL 8 due to missing rpcgen.

- meta-mentor-staging/recipes-core/udev/udev-extraconf/0001-udev-extraconf-mount.sh-ignore-lvm-in-automount.patch
- meta-mentor-staging/recipes-core/udev/udev-extraconf_%.bbappend
Failure message is shown in boot logs when trying to
mount lvm on emmc while booting from sdcard. This
simply skips lvm while automounting to avoid failure
message in boot logs.
Fixes: https://jira.alm.mentorg.com/browse/SB-15734
Signed-off-by: Ansar Rasool <ansar_rasool@mentor.com>
> udev-extraconf/mount.sh: ignore lvm in automount

- meta-mentor-staging/recipes-core/udev/udev-extraconf/0003-udev-extraconf-mount.sh-only-mount-devices-on-hotplu.patch
This fixes auto-mounting issue where a manually
unmounted disk would get auto-mounted simply by running
tools such as fdisk from the util-linux package which
generate a BLKRRPART ioctl in order to support any of
their features.
JIRA Ticket: SB-15741
Signed-off-by: ekalemen <eugeny_kalemenev@mentor.com>
> udev-extraconf: fix systemd automount issue

- conf/local.conf.sample
This corrects the comment for tools-benchmark to remove netperfc
as netperfc has been removed from tools-benchmark.
Fixes: https://jira.alm.mentorg.com/browse/SB-15735
Signed-off-by: Ansar Rasool <ansar_rasool@mentor.com>
> local.conf.sample: remove netperfc from tools-benchmark

- meta-mentor-staging/recipes-devtools/gdb/gdb/0001-gdbserver-handle-running-threads-in-qXfer-threads-re.patch
- meta-mentor-staging/recipes-devtools/gdb/gdb_9.1.bbappend
This fixes an issue where gdbserver is fixed to handle
running threads in various cases. This backport was
provided by the CB team.
Fixes: SB-16178.
> gdb: incorporate a backport provided by the CB team

- meta-mel/recipes-kernel/lttng/lttng-modules/lttng-module-fix-writeback-Fix-sync.patch
- meta-mel/recipes-kernel/lttng/lttng-modules_%.bbappend
This fixes the compilation error for lttng-module
after pulling the LTS update.
Signed-off-by: ansar-rasool <ansar_rasool@mentor.com>
> lttng-modules: fix error due to LTS updates

- meta-mel/conf/distro/include/mel.conf
This was only needed when using an external toolchain which didn't include the build id by default. This is not the case with a Yocto-built toolchain, so we no longer need it.
> mel: drop build-id

- scripts/setup-mel-builddir
> setup-mel-builddir: remove unhandled -t argument from getopts call

- scripts/setup-mel-builddir
We have a requirement where upstream Yocto BSPs should be able to
build with MEL out of the box. Sourcing setup-environment at this
point for an upstream machine adds the MEL common BSP layer to
bblayers automatically which is not correct as that particular
machine is not a MEL BSP. However, we do need this for qemu BSPs
as we use the same upstream machine name but create a layer for
our modifications.
> setup-mel-builddir: do not depend on mentor-bsp for every machine

- scripts/setup-ubuntu
This is not needed, and we aren't installing it for debian or rh.
> setup-ubuntu: drop python 2

- meta-mel/recipes-core/psplash/mel/psplash-quit.service
Removing type=oneshot and "default" way of starting the service.
JIRA: https://jira.alm.mentorg.com/browse/SB-16089
Signed-off-by: Arulpandiyan Vadivel <arulpandiyan_vadivel@mentor.com>
> psplash: fix failed starting Terminate Psplash Boot Screen

- meta-mel/conf/distro/include/mel.conf
> mel.conf: do not fetch anti-virus db at compile time in clamav

- conf/local.conf.sample
- scripts/setup-mel-builddir
- move mel-debugging machine feature from meta-mentor to meta-mentor-bsp
- conditionalize inclusion of machine layer on qemu as other upstream BSPs should be handled differently
- utilize the feature-mel-bsp
> [dunfell] mel-debugging / mel-bsp / inclusion of layers for upstream BSPs

- meta-mel/conf/distro/include/sourcery-version-check.inc
We don't need to abort the build if we have 12.0.4 but it wants 12.0.0.
JIRA: SB-16597
> sourcery-version-check.inc: ignore the minor version

- meta-mentor-staging/qt5-layer/recipes-qt/qt5/qtbase/Fix-note-alignment.patch
- meta-mentor-staging/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
This cherry-picks the fix from upstream qtbase git to fix a warning seen by `readelf -n` due to an alignment issue with the note.
JIRA: SB-16601
> qtbase: fix abi tag note alignment for some targets

- meta-mentor-staging/lib/oe/__init__.py
- meta-mentor-staging/lib/oe/rootfs.py
The rootfs generation mechanism removed sysV style scripts
for the run-postinsts when they were unneeded but misssed
the same case for systemd type systems. This caused the
systemd service to run unnecessarily which can cause
uninteded long booting times on platforms that do not have
enough hardware resources.
Fixes: https://jira.alm.mentorg.com/browse/SB-15658
> [dunfell] rootfs.py: fix for disabling run-postinsts on systemd

- meta-mentor-staging/lib/oe/rootfs.py
This aligns the approach that got accepted upstream so it would
make sense to pick that up right now.
Ref: https://git.openembedded.org/openembedded-core/commit/meta/lib/oe?id=627fb3181edd71502fbdf96549c41b2dea027250
> staging/rootfs.py: align run-postinsts handling with upstream

- meta-mel-support/recipes-devtools/python/python3-unidiff/run-ptest
- meta-mel-support/recipes-devtools/python/python3-unidiff_%.bbappend
- meta-mel-support/recipes-devtools/python/python3-unidiff_0.6.0.bb
- meta-mel/conf/distro/include/mel.conf
- meta-mel/recipes-devtools/python/python3_%.bbappend
- scripts/patchinfo
This aligns with the behavior of meta-codebench-toolchain for python3 clearing, as suggested by @jeremy-robinson. In this case patchinfo is used, solely because the other script from the other layer is more specific to their requirements rather than general purpose.
> python3: use patchinfo to write python3-patches.txt for release-downloads

- meta-mentor-staging/recipes-connectivity/openssh/files/add-test-support-for-busybox.patch
- meta-mentor-staging/recipes-connectivity/openssh/files/fix-potential-signed-overflow-in-pointer-arithmatic.patch
- meta-mentor-staging/recipes-connectivity/openssh/openssh_8.5p1.bb
This CVE has an impact before version 8.5 so updating
to 8.5p1 version fixes this issue.
Signed-off-by: Karim, Hafiz Abdul <HafizAbdul_Karim@mentor.com>
> openssh:  fix CVE-2021-28041 by updating the package

- meta-mentor-staging/openembedded-layer/recipes-dbs/postgresql/files/0001-Add-support-for-RISC-V.patch
- meta-mentor-staging/openembedded-layer/recipes-dbs/postgresql/files/0001-Improve-reproducibility.patch
- meta-mentor-staging/openembedded-layer/recipes-dbs/postgresql/files/not-check-libperl.patch
- meta-mentor-staging/openembedded-layer/recipes-dbs/postgresql/files/postgresql-profile
- meta-mentor-staging/openembedded-layer/recipes-dbs/postgresql/files/postgresql-setup
- meta-mentor-staging/openembedded-layer/recipes-dbs/postgresql/files/postgresql.init
- meta-mentor-staging/openembedded-layer/recipes-dbs/postgresql/files/postgresql.pam
- meta-mentor-staging/openembedded-layer/recipes-dbs/postgresql/files/postgresql.service
- meta-mentor-staging/openembedded-layer/recipes-dbs/postgresql/postgresql.inc
- meta-mentor-staging/openembedded-layer/recipes-dbs/postgresql/postgresql_12.5.bb
* Get the recipe from meta-oe dunfell branch.
* Updated version to 12.5 to get fix for CVE-2020-25694, CVE-2020-25695, CVE-2020-25696
Signed-off-by: Noor Ahsan <noor_ahsan@mentorg.com>
> postgresql: Add 12.5 version to fix CVEs

- meta-mentor-staging/networking-layer/recipes-support/tcpdump/tcpdump/add-ptest.patch
- meta-mentor-staging/networking-layer/recipes-support/tcpdump/tcpdump/avoid-absolute-path-when-searching-for-libdlpi.patch
- meta-mentor-staging/networking-layer/recipes-support/tcpdump/tcpdump/fix-CVE-2020-8037.patch
- meta-mentor-staging/networking-layer/recipes-support/tcpdump/tcpdump/run-ptest
- meta-mentor-staging/networking-layer/recipes-support/tcpdump/tcpdump/unnecessary-to-check-libpcap.patch
- meta-mentor-staging/networking-layer/recipes-support/tcpdump/tcpdump_4.9.3.bb
This upgrade the tcpdump package to version 4.9.3 in order to
fix several CVEs that are reported against version less than
4.9.3. The recipe along with patches has been picked up from
meta-networking zeus branch.
Additionally we fix a CVE that was reported by the cve-check
tool against package version 4.9.3.
JIRA: https://jira.alm.mentorg.com/browse/SB-16881
> staging/tcpdump: upgrade to 4.9.3

- conf/local.conf.sample
The runner is already included via `RRECOMMENDS_${PN}-ptest`, so we don't need to explicitly include it.
> local.conf.sample: remove unneeded ptest-runner line

- meta-mentor-staging/openembedded-layer/recipes-devtools/nodejs/nodejs/0001-Disable-running-gyp-files-for-bundled-deps.patch
- meta-mentor-staging/openembedded-layer/recipes-devtools/nodejs/nodejs_8.16.1.bb
This upgrades the nodejs package to 8.16.1 from 8.9.4 to
resolve a number of CVEs that were reported against the
older version. The backporting effort for the CVE fixes
on the older version out weighs the work that we are
expecting here so we simply upgrade the package.
Fixed CVEs:
CVE-2019-9511
CVE-2019-9512
CVE-2019-9513
CVE-2019-9514
CVE-2019-9515
CVE-2019-9516
CVE-2019-9517
CVE-2019-9518
JIRA: https://jira.alm.mentorg.com/browse/SB-16893
> staging/openembedded-layer/nodejs: upgrade to 8.16.1

- meta-mel/mel-support/recipes-core/meta/archive-release.bbappend
For public layers where we aren't filtering the files in the layer, there's no need to create our own commit, we can directly point to the upstream commit.
> archive-release: skip committing for public layers

- meta-mentor-staging/selinux/recipes-security/selinux/libselinux-python_3.0.bbappend
This fixes the error below:
gcc: error: unrecognized command line option
‘-fmacro-prefix-map=/path/to/build/libselinux-python/3.0-r0=/usr/src/debug/libselinux-python/3.0-r0’
Without inheriting the config, supposedly a wrong compiler is used.
Backport from:
http://git.yoctoproject.org/cgit/cgit.cgi/meta-selinux/commit/recipes-security/selinux?h=dunfell&id=c9de7989464c7cd774e25d23496ed63ffc4ecdf6
Signed-off-by: ansar-rasool <ansar_rasool@mentor.com>
> mentor-staging/selinux: fix build error due to missing target config 

- meta-mentor-staging/recipes-kernel/powertop/files/0001-configure.ac-ax_add_fortify_source.patch
- meta-mentor-staging/recipes-kernel/powertop/files/0002-configure-Use-AX_REQUIRE_DEFINED.patch
- meta-mentor-staging/recipes-kernel/powertop/powertop_2.10.bbappend
Error:
aclocal: error: too many loops
aclocal: Please contact bug-automake@gnu.org.
JIRA-ID: SB-17299
Fix:
Backport https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/
?h=dunfell&id=d4b4bf172f260ee2d95088368c56de0e2155ffe2
> powertop_2.10: add patches to fix aclocal error

- meta-mel/conf/distro/mel.conf
The risk here is low, the disk space usage isn't terrible (adds 730KiB to our
development-image), the runtime impact is low, and the ptest failures go down by
enabling it.
JIRA: SB-15753
> mel: enable pam by default

- meta-mel/conf/distro/include/mel.conf
- scripts/setup-ubuntu
locale-gen creates temporary files in /etc and fails to
do so if not run with sudo.
Bumps the SCRIPTS_VERSION so the changes are picked up in the
next installer.
JIRA: https://jira.alm.mentorg.com/browse/SB-17257
> setup-ubuntu: run locale-gen with sudo and bump SCRIPTS_VERSION

- scripts/release/mel-checkout
Due to an interaction between the argument processing for the main script and that of the prompt_choice function, `$2` was never seen (the shift removed it), and thus no default was set for the prompt.
JIRA: SB-17182
> mel-checkout: fix prompt default when passing -a

- meta-mentor-staging/licenses/Hewlett-Packard
This fixes
WARNING: ti-cgt-pru-native-2.3.2-r0 do_populate_lic: ti-cgt-pru-native: No generic license file exists for: Hewlett-Packard in any provider
and is a backport of
http://git.yoctoproject.org/cgit/cgit.cgi/meta-ti/commit/?id=97441a763e8568cf477a0e45ce1d86cb6b8e7e4a
JIRA: https://jira.alm.mentorg.com/browse/SB-17191
> [sumo] staging: licenses: add license for HP

- meta-mel/conf/distro/include/mel.conf
INCOMPATIBLE_LICENSE can have any variant of GPLv3 license
names i.e. GPL-3.0 or GPLv3.
Fixes: https://jira.alm.mentorg.com/browse/SB-17451
> [sumo] mel.conf: check for GPLv3 variants for QEMUDEPS

- meta-mel/conf/distro/include/mel.conf
This simplifies the checking of GPLv3 incompatibility for
inclusion of tools in the QEMUDEPS.
Suggested-by: Christopher Larson <chris_larson@mentor.com>
> [sumo] mel.conf: simplify license checking for QEMUDEPS

- meta-mel/recipes-devtools/llvm/llvm_%.bbappend
* llvm was consuming alot of resources due to which we were getting following
g++: fatal error: Killed signal terminated program cc1plus
Reduced PARALLEL_MAKE value to 8 when we are running on 9 cpu core machine.
> llvm: Fix Killed signal error on 8 core machine for llvm

- meta-mentor-staging/openembedded-layer/recipes-extended/libmodbus/libmodbus/local-tcp-test
- meta-mentor-staging/openembedded-layer/recipes-extended/libmodbus/libmodbus/run-ptest
- meta-mentor-staging/openembedded-layer/recipes-extended/libmodbus/libmodbus_%.bbappend
The current version uses our own script, but ideally we should likely patch the existing scripts to address any issues, patch the makefile to add an install-ptest rule, and ship the script and Makefile. This will do for the moment.
JIRA: MELMR-280
> libmodbus: add initial ptest

- meta-mentor-staging/recipes-devtools/perl/perl/perl-rdepends.txt
This removes SPDX header from perl-rdepends.txt file to fix
following build failure for perl package.
ERROR: perl-5.30.1-r0 do_package: Error executing a python function in exec_python_func() autogenerated:
The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
0001:
*** 0002:split_perl_packages(d)
0003:
File: '/data/ansar/fir_async2/oe-core/meta/recipes-devtools/perl/perl_5.30.1.bb', lineno: 335, function: split_perl_packages
0331:            module = splitline[0] + '-native'
0332:            depends = "perl-native"
0333:        else:
0334:            module = splitline[0].replace("RDEPENDS_perl", "RDEPENDS_${PN}")
*** 0335:            depends = splitline[2].strip('"').replace("perl-module", …
> mentor-staging/perl-rdepends.txt: remove spdx license header to fix build failure

- meta-mel/lib/bblayers/mel_utils.py
This adds --append (-a) and --sourceinfo (-s) flags to mel_utils.py/dump-licenses.
JIRA: SB-18234
See commits for details.
Usage:
--append
$ bitbake-layers dump-licenses development-image
$ bitbake-layers dump-licenses development-image -c populate_sdk -a
--sourceinfo
$ bitbake-layers dump-licenses development-image -s
$ bitbake-layers dump-licenses development-image -c populate_sdk -a -s
> Improve dump-licenses adding --append and --sourceinfo flags

- meta-mel-support/recipes-bsp/96boards-tools/96boards-tools_0.12.bb
This is breaking the build when sysvinit is available in distro
features.
Jira ID: SB-18221
> 96boards-tools: fix a typo for sysvinit case

- meta-mel-support/recipes-bsp/96boards-tools/96boards-tools_0.12.bb
This sed is from legacy implementation and no longer applies to the
current disk-resizer script in the 96boards-tools source
> 96boards-tools: remove unused sed from the recipe

- meta-mel/lib/recipetool/kernel.py
- scripts/capdebuginfo
- scripts/multi-machine
- scripts/setup-mel-builddir
- scripts/setup-rh
- scripts/setup-ubuntu
These scripts are licensed under GPLv2 rather than MIT
so fix the SPDX license identifier accordingly.
> [dunfell] scripts: recipetool: fix SPDX license identifier

- meta-mel/recipes-core/packagegroups/packagegroup-base.bbappend
Since we only require client capabilites we do not need to
install complete nfs-utils which comes with server capibilties
causing failures due to absend NFSD server configs as we do
not need them.
JIRA-ID: SB-18414
Signed-off-by: Muhammmad Hamza <muhammad_hamza@mentor.com>
> packagegroup-base: Use nfs-utils-client instead of nfs-utils

- meta-mel/lib/bblayers/mel_utils.py
"bitbake-layers dump-licenses <recipe> --sourceinfo" dumps a wrong
value for packages having no SRC_URI i.e. "*-external" packages.
This fixes that.
Signed-off-by: Arsalan H. Awan <Arsalan_Awan@mentor.com>
> mel_utils/dump-licenses: fix wrong su dump for pkgs having no SRC_URI

- meta-mel/conf/distro/include/mel.conf
This is a workaround for https://github.blog/2021-09-01-improving-git-protocol-security-github/, to avoid needing to update bitbake to pick up the fix there.
> mel: set https protocol for all github urls

- meta-mel/conf/distro/include/mel.conf
This reverts commit 3063301fb263114a1c403c20abc560e92e2a5924.
This isn't needed, as the default MIRRORS already falls back to https.
> Revert "mel: set https protocol for all github urls"

- meta-mel-support/recipes-core/meta/archive-release.bb
- meta-mel/conf/distro/mel.conf
- meta-mel/lib/bblayers/mel_utils.py
- meta-mel/mel-support/recipes-core/meta/archive-release.bbappend
- scripts/release/mel-checkout
This includes a couple fixes and a couple enhancements, none of which will have any effect except in particular cases or when opted in.
- Avoid conflict between `templates` and `images` artifacts in archive-release
- Allow archival of local git repos that have no origin remote
- Include `${VENDOR}.conf` from mel for later vendor config support
- Allow shipment of xlayers.conf to customize default layer inclusion beyond that of the BSP, DISTRO, and MEL default optional layers
> A few misc commits from recent POC

- meta-mel/conf/distro/include/mel-arm-tuning.inc
- meta-mel/conf/distro/mel.conf
This avoids unnecessary toolchain component rebuilds and increases reuse and
compatibility amongst compatible machines. Imported, then tweaked to also apply
to aarch64 and our DISTRO.
Imported from https://github.com/96boards/meta-rpb/blob/master/conf/distro/include/arm-defaults.inc
Imported from https://github.com/Angstrom-distribution/meta-angstrom/blob/master/conf/distro/include/arm-defaults.inc
> mel: use common compatible tuning values for arm & aarch64

- meta-mel/conf/distro/mel.conf
- meta-mel/mel-support/recipes-core/meta/archive-release.bbappend
- scripts/release/mel-checkout
Use SOURCE_DATE_EPOCH if needed to improve reproducibility of generated commits, and use bundles rather than pack files which give us consistent reproducible output and avoids file duplication between releases and updates.
> archive-release: improve reproducibility

- meta-mel/conf/distro/mel.conf
- meta-mentor-common/classes/required_toolchain_config.bbclass
This aborts the MEL Flex build if the user is attempting to build a configuration which isn't one of the supported codebench toolchain configurations. This will keep internal toolchain builds aligned with external toolchain builds. It also means that attempts to build unsupported architectures like mips will fail at this time.
> mel: only support the tunings aligned with the external toolchain

- meta-mel/lib/bblayers/mel_utils.py
For a single configuration build the dependency graph does
not contain any configuration prefixes and the implementation
handled it correctly with this assumption. However, in case of
a multiconfig build the components (PNs/recipes) get prefixed
with mc:<config>:component which is something not taken care of
and hence the download dumping fails with a KeyError. The most
recent failure was seen with TI Jacinto7 platform builds which
failed with
Traceback (most recent call last):
File "/var/jenkins/workspace/mel_fir_singo_main_incremental/buildtype/mel/label/mel-u18-64/machine/j7-evm-aitronx/repotop/bitbake/bin/bitbake-layers", line 95, in <module>
ret = main()
File "/var/jenkins/workspace/mel_fir_singo_main_incremental/buildtype/mel/label/mel-u18-64/machine/j7-evm-aitronx/repotop/bitbake/bi …
> mel_utils/dump-downloads/dump-licenses: support multi-config scenarios

- meta-mel/conf/distro/include/mel.conf
With recent versions of git, attempting to operate on a git repository owned by
one user as another user will fail. As our builds run under pseudo in some
contexts, this fails. This issue in tasks can be worked around with a git
wrapper script, and is worked around upstream, but that does not resolve the
issue with metadata_scm.bbclass, as it isn't run with the correct PATH. It's a
non-issue upstream as they already made this change to force immediate expansion
of these variables in the right context, so apply that here also.
JIRA: SB-19344
> mel: work around safe dir issue with METADATA_*

- meta-mel/conf/distro/include/mel.conf
We now use FIT uImage for all our U-Boot based BSPs which incorporates
the separate initramfs section, so there is no need to bundle initramfs
with the kernel as well
JIRA ID: SB-17288
> [fir_async2_next]: mel.conf: Unbundle initramfs from the kernel image

- meta-mel/recipes-kernel/lttng/lttng-modules/0001-fix-random-tracepoints-removed-in-stable-kernels.patch
- meta-mel/recipes-kernel/lttng/lttng-modules_%.bbappend
This fixes compilation error after latest LTS updates of
kernel where trace/events/random.h file is dropped in
kernel which is unused mostly. This file was being included
here in lttng-modules which causes compilation failure with LTS kernel. This
drops the inclusion of dropped file.
Reference upstream kernel commit:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-4.14.y&id=707c01fe19eb2128374d1a71b7b6d1c9ee2d379f
Signed-off-by: Ansar Rasool <ansar_rasool@mentor.com>
> [sumo] lttng-modules: fix compilation failure after kernel update
